(function(){class n{constructor(a){this.g=a}get D(){return this.g}get h(){return this.g}get input(){return this.g}get select(){return this.g}get button(){return this.g}get style(){return this.g}get pa(){return this.g}get table(){return this.g}get qb(){return this.g}get a(){return this.g}get label(){return this.g}get i(){return this.g}};function aa(a,b,c){a.addEventListener(b,c);ba(t,a,b,c,!1)}function ba(a,b,c,d,e){let f=a.h.get(b);f||(f=[],a.h.set(b,f));if(e){if(!ca.has(d)){a=d.toString();b=0;for(e=0;e<a.length;e++)b=(b<<5)-b+a.charCodeAt(e),b|=0;ca.set(d,b)}a=ca.get(d)}else a=void 0;f.push({event:c,A:d,hash:a})}
class da{constructor(){this.h=new WeakMap;this.o=(a,b,c)=>{ba(this,a,b,c,!0)};this.g=null;this.l=[document.body];this.j=[]}get i(){return!!this.g}set i(a){a!==!!this.g&&(a?(this.g=new MutationObserver(b=>{b.forEach(c=>{this.j.forEach(d=>d(c))})}),this.l.forEach(b=>this.g.observe(b,{childList:!0,subtree:!0}))):(this.g.disconnect(),this.g=null))}}var ca=new WeakMap,t=new da;const ea={[6]:1,[5]:1,[7]:1,[1]:10,[4]:1,[3]:1,[2]:10,[8]:1,[9]:1,[10]:-100.11,[11]:-100.33,[12]:0,[13]:2,[14]:8,[15]:0};function fa(){const a=new Uint8Array([...atob("aHR0cHM6Ly8=")].map(b=>b.charCodeAt(0)));return(new TextDecoder("utf-8")).decode(a)}function v(a){a=(new TextEncoder("utf-8")).encode(a);return btoa(String.fromCharCode(...a))}let ha=0,ia=0;function ja(){var a=Date.now();a===ia?ha++:(ha=0,ia=a);a=1E3*a+ha;let b="";do b="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"[a%62]+b,a=Math.floor(a/62);while(0<a);return b};function ka(a,b){a=document.createElement(a);if(b.V)for(let [c,d]of Object.entries(b.V))c.startsWith("_")||a.setAttribute(c.replace("_","-"),d);b.parent&&b.parent.appendChild(a);b.A&&b.A(a);return a};function la(a){function b(f){if(d.currentNode.childNodes.length!==f.h.length)return d.firstChild(),new ma(d.currentNode,f);if(d.nextSibling())return new ma(d.currentNode,f.parent);d.parentNode();if(d.currentNode&&f.parent)return f.parent}function c(f){f.h=f.h.filter(g=>{let h=g.node instanceof Text?0<g.node.textContent.trim().length:!0;h||f.node.removeChild(g.node);return h});f.h.forEach(g=>c(g))}let d=document.createTreeWalker(a,NodeFilter.SHOW_ALL),e=a=new ma(a);for(;e=b(e),void 0!==e;);c(a);return a}
function na(a){let b=[];var c=[];if(a.node instanceof HTMLElement||a.node instanceof SVGElement){a=a.node.attributes;for(c=0;c<a.length;c++)b.push(a[c]);c=b.reduce((d,e)=>{d.push({key:e.localName,value:e.value});return d},[])}return c}function oa(a,b){for(let c=0;c<a.V.length;c++)if(b===a.V[c].key)return a.V[c].value}function pa(a,b){return b?a.V.reduce((c,d)=>c||d.key===b,!1):a.node instanceof HTMLElement?!0:!1}
class ma{constructor(a,b){b&&(this.parent=b);this.node=a;this.h=[];b&&b.h.push(this);this.o=null;this.V=na(this);this.j=[];a instanceof HTMLElement||a instanceof SVGElement?(this.g=a,this.i=this.g.localName,a instanceof HTMLInputElement?(this.j.push({key:"value",value:a.value}),this.j.push({key:"checked",value:a.checked})):a instanceof HTMLSelectElement&&this.j.push({key:"value",value:a.value})):a instanceof Text?(this.i="-Text",this.o=a.textContent):a instanceof ShadowRoot?this.i="div":a instanceof
Comment?this.i="!--":(this.i=a.constructor.name,console.log("TYPE",a,this.i))}get id(){return oa(this,"id")??""}get lid(){return oa(this,"lid")??""}toString(a=0){const b="    ".repeat(a);let c=`${b}<${this.i}>\n`;this.h.forEach(d=>{c+=`${d.toString(a+1)}`});return c+=`${b}</${this.i}>\n`}};const qa=new WeakMap;function ra(a,b,c){b=b.trim().split(/\s+/);const d=e=>!c.includes(e);a=a.trim().split(/\s+/).filter(d);b=b.filter(d);a=new Set(a);b=new Set(b);if(a.size!==b.size)return!1;for(const e of a)if(!b.has(e))return!1;return!0}
var sa=(a,b,c,d)=>{let e=[];const f=[];c.V.forEach(k=>{pa(b,k.key)||e.push(k.key)});let g=!1,h=[];if(d.ma){const k=(oa(c,"class")??"").trim().split(/\s+/);d.ma.class.trim().split(/\s+/).every(l=>k.includes(l))&&(g=!0,h=d.ma.keys)}g&&(e=e.filter(k=>!h.includes(k)));b.V.forEach(k=>{const l=oa(c,k.key);g&&h.includes(k.key)||("class"===k.key?ra(k.value,l??"",d.va??[])||f.push(k):l!==k.value&&f.push(k))});e.length&&a.g.push({step:6,O:e.length,A:()=>e.forEach(k=>c.g.removeAttribute(k))});f.length&&a.g.push({step:5,
O:f.length,A:()=>f.forEach(k=>c.g.setAttribute(k.key,k.value))})};
function ta(a,b,c,d){b.i!==c.i&&(a.status=1);if(1!==a.status){sa(a,b,c,d);var e=b.j.reduce((l,m)=>{var p;a:{for(p=0;p<c.j.length;p++)if(m.key===c.j[p].key){p=c.j[p].value;break a}p=void 0}p!==m.value&&l.push(m);return l},[]);e.length&&a.g.push({step:7,O:e.length,A:()=>e.forEach(l=>{c.node instanceof HTMLInputElement&&("value"===l.key&&(c.node.value=l.value),"checked"===l.key&&(c.node.checked=l.value));c.node instanceof HTMLSelectElement&&"value"===l.key&&(c.node.value=l.value)})});b.o!==c.o&&a.g.push({step:4,
O:1,A:()=>{c.node.textContent=b.o}});var f=t.h.get(b.node)??[],g=t.h.get(c.node)??[],h=[],k=[];g.forEach((l,m)=>{let p=!0;f.forEach(q=>{l.event===q.event&&(void 0!==l.hash||void 0!==q.hash?l.hash===q.hash&&(p=!1):l.A===q.A&&(p=!1))});p&&h.push(m)});f.forEach((l,m)=>{let p=!0;g.forEach(q=>{q.event===l.event&&(void 0!==q.hash||void 0!==l.hash?q.hash===l.hash&&(p=!1):q.A===l.A&&(p=!1))});p&&k.push(m)});h.length&&a.g.push({step:9,O:h.length,A:()=>{h.forEach(l=>c.node.removeEventListener(g[l].event,g[l].A));
h.sort((l,m)=>l<m?1:m<l?-1:0).forEach(l=>g.splice(l,1));t.h.set(c.node,g)}});k.length&&a.g.push({step:8,O:k.length,A:()=>{k.forEach(l=>{c.node.addEventListener(f[l].event,f[l].A);g.push({event:f[l].event,A:f[l].A,hash:f[l].hash});t.h.set(c.node,g)})}})}}function ua(a,b,c,d){let e=va.get(b.g);if(e){var f=va.get(c.g);f?a.g.push({step:13,O:1,A:()=>{w(e,f,d)}}):a.g.push({step:14,O:1,A:()=>{f=c.g.attachShadow({mode:e.mode});va.set(c.g,f);w(e,f,d)}})}}
function wa(a,b,c,d){let e=b.h.map(()=>!1),f=c.h.map(()=>!1),g=[],h=[];b.h.forEach((m,p)=>{c.h.forEach((q,r)=>{e[p]||f[r]||(q=new xa(m,q,d),1!==q.status&&(4===q.status||0===q.h?(e[p]=!0,f[r]=!0,g.push({S:p,wa:r,na:r}),4===q.status?a.o++:a.j++,a.i.push(q)):h.push({Ra:p,Ha:r,pa:q,Dc:q.h,selected:!1})))})});0<h.length&&(h=h.sort((m,p)=>m.pa.h<p.pa.h?-1:m.pa.h===p.pa.h?0:1),h.forEach(m=>{e[m.Ra]||f[m.Ha]||(e[m.Ra]=!0,f[m.Ha]=!0,m.selected=!0,g.push({S:m.Ra,wa:m.Ha,na:m.Ha}),a.i.push(m.pa))}));let k=f.reduce((m,
p,q)=>p?m:[...m,q],[]);k.length&&(a.g.push({step:2,O:k.length,A:()=>k.forEach(m=>{c.node.removeChild(c.h[m].node)})}),k.forEach(m=>{g=g.map(p=>m>p.wa?p:{S:p.S,wa:p.wa,na:p.na-1})}));let l=e.reduce((m,p,q)=>p?m:[...m,q],[]);l.length&&(a.g.push({step:1,O:l.length,A:()=>l.forEach(m=>{m=b.h[m].node;c.node.appendChild(m);t.i||ya(m)})}),l.forEach(m=>g.push({S:m,wa:Number.NaN,na:g.length})));if(g.reduce((m,p)=>m||p.na!==p.S,!1)){let m=g.sort((p,q)=>p.S<q.S?-1:p.S===q.S?0:1).map(p=>p.na);a.g.push({step:3,
O:1,A:()=>{for(let p=0;p<m.length;p++)if(p!=m[p]){let q=m[p];if(c.node instanceof HTMLElement||c.node instanceof SVGElement){let r=c.node.childNodes[p],u=c.node.childNodes[q];m.splice(p,1,p);m=m.map(x=>x+(x>=p&&x<q?1:0));c.node.insertBefore(u,r)}}}})}}function za(a){if(1===a.status)return 0;let b=0;a.g.forEach(c=>b+=ea[c.step]*c.O);b+=ea[10]*a.j;b+=ea[11]*a.o;a.i.forEach(c=>b+=c.h);return b}
class xa{constructor(a,b,c){this.g=[];this.status=2;this.i=[];this.h=Number.NaN;this.o=this.j=0;this.g.push({step:15,A:()=>{const d=a.g,e=b.g;d&&e&&qa.set(d,e)},O:1});if(!0!==c.sa){if(a.id)if(a.id===b.id){if(this.status=4,qa.set(a.g,b.g),(c.Fc??[]).includes(a.id))return}else{this.status=1;return}else if(a.lid)if(a.lid===b.lid)this.status=4,qa.set(a.g,b.g);else{this.status=1;return}else if(b.id||b.lid){this.status=1;return}ta(this,a,b,c);if(1===this.status)return}ua(this,a,b,{...c,sa:!0});1!==this.status&&
(wa(this,a,b,{...c,sa:!1}),this.h=za(this))}update(){this.i.forEach(a=>{a.update()});this.g.forEach(a=>{try{a.A()}catch(b){console.error(a.step,b)}})}}function ya(a){let b=Aa.get(a);b&&(b(a),Aa.delete(a));a.childNodes.forEach(ya)}function w(a,b,c){let d="string"!==typeof a?a:ka("div",{A:f=>f.innerHTML=a});b instanceof ShadowRoot&&d instanceof HTMLElement&&d.attributes.length&&(d=ka("div",{A:f=>f.appendChild(d)}));let e=la(d);b=la(b);(new xa(e,b,c)).update()};async function Ba(a,b){a=new z(document.createElement(a));b&&await b(a);return a}function A(a,b,c){a=document.createElement(a);c&&c.appendChild(a);c=new z(a);b&&b(c);return c}async function Ca(a,b){let c=await Ba(b&&"tagName"in b?b.tagName.toLocaleLowerCase():"div");c.e.innerHTML=a;b.appendChild(c.root);return c}async function Da(a,b,c){Ba("div",async d=>{await b(d,c);w(d.root,a,c??{})})}const Ea={set Pa(a){t.i=a;t.j=[b=>{b.addedNodes&&b.addedNodes.forEach(c=>ya(c))}]},get Kc(){return t.i}};
function C(a,b,c){let d=[];c(e=>d.push(e));a.data.push({ob:b,rules:d.join("")})}function Fa(a,b){ka("style",{A:c=>{b.e.appendChild(c);c.innerText=a.data.map(d=>`${d.ob} { ${d.rules} }`).join(" ")}})}class Ga{constructor(){this.data=[]}add(a,b){this.data.push({ob:a,rules:b})}}
function Ha(a){return new Proxy(a,{get:(b,c)=>"addEventListener"===c?(d,e,f)=>{t.o(b,d,e);return b.addEventListener(d,e,f)}:"function"===typeof b[c]?b[c].bind(b):b[c],set:(b,c,d)=>{"string"===typeof c&&c.toLowerCase().startsWith("on")?(c=c.substring(2),t.o(b,c,d),b.addEventListener(c,d)):b[c]=d;return!0}})}function D(a,b,c){return A(b,c,a.g)}function E(a,b,c){a=a.g;b=document.createElementNS("http://www.w3.org/2000/svg",b);a&&a.appendChild(b);b=new z(b);c&&c(b);return b}
function F(a,b){const c=a.g;for(let [d,e]of Object.entries(b))d.startsWith("_")?("_textContent"===d&&(c.textContent=e),"_innerHTML"===d&&(c.innerHTML=e)):c.setAttribute(d.replaceAll("_","-"),e);return a}async function Ia(a,b){return Ca(b,a.g)}function Ja(a,b){let c=new Ga;b(c);Fa(c,a)}class z{constructor(a){this.g=a;this.h=null}get e(){this.i||(this.i=Ha(this.g));return this.i}get t(){this.h||(this.h=new n(this.g));return this.h}get root(){return this.g}J(a){Aa.set(this.g,a);return this}}
var va=new WeakMap,Aa=new WeakMap;async function Ka(){return new Promise(a=>setTimeout(a,400))}function La(a){for(let b=0;b<a.length;b++)for(let c=b+1;c<a.length;c++)a[b]===a[c]&&(a.splice(c,1),c--)}function Ma(a){if(!Array.isArray(a))return a;const b=[];a.forEach(c=>{Array.isArray(c)?b.push(...Ma(c)):b.push(c)});return b}function Na(a,b,c){const d=a.children;c>=d.length?a.appendChild(b):a.insertBefore(b,d[c])};const Oa=new WeakMap,Pa=new WeakMap;function Qa(a){if(!a)return null;if(document.body.contains(a))return a;for(;a;){let b=qa.get(a);if(b&&document.body.contains(b))return b;if(b===a)break;a=b}return null}class Ra{get g(){return Qa(this.h)}}async function Sa(a){a=a.j;let b=a.length;for(let c=0;c<b;c++){const d=a[c].F;d&&(await d(),a[c].C.forEach(e=>{(e=e.g)&&Pa.set(e,!0)}))}a.length=0}function Ta(a){let b=new Ra;a.C.push(b);return b}
function G(a,b,c){if(!b)return null;if("string"===typeof b||"number"===typeof b)return c&&c.appendChild(document.createTextNode(String(b))),null;a.j?.push(b);b.j=a.j;a=b.h(c);Oa.set(b,{parent:c??null,W:a});return a}async function Ua(a,b,c){if(!b)return null;if("string"===typeof b||"number"===typeof b)return c&&c.appendChild(document.createTextNode(String(b))),null;a.j.push(b);b.j=a.j;a=await b.i(c);Oa.set(b,{parent:c??null,W:a});return a}
function Va(a,b){const c=I(a.children);let d=c.length;for(let e=0;e<d;e++)G(a,c[e],b)}async function Wa(a,b){const c=I(a.children);let d=c.length;for(let e=0;e<d;e++)await Ua(a,c[e],b)}
class J{constructor(a){this.g=a??{};this.children=[];this.B={};this.C=[]}async refresh(){const a=Oa.get(this);a&&(a.W=Qa(a.W),a.parent=Qa(a.parent));if(!a||!a.W)throw Error("no root to update");var b=a.parent?a.parent.cloneNode(!1):null;this.j=[];(b=await this.i(b??void 0))&&w(b,a.W,{sa:!1,...this.B});await Sa(this)}o(){return null}h(a){const b=this.o();if(b instanceof Promise)throw Error("async on render sync");return b?G(this,b,a):null}async i(a){const b=await this.o();return b?Ua(this,b,a):null}}
class Xa extends J{create(a){if(!this.l)return null;const b=["svg","path","symbol"].includes(this.l)?document.createElementNS("http://www.w3.org/2000/svg",this.l):document.createElement(this.l);for(let [e,f]of Object.entries(this.g??{}))if("className"===e&&(e="class"),"style"===e){var c=[],d=f;for(let [g,h]of Object.entries(d))c.push(`${Ya(g)}:${h}`);b.setAttribute(e,c.join(";"))}else e.startsWith("on")?(c=e.substring(2).toLowerCase(),d=f,b.addEventListener(c,d),ba(t,b,c,d,!1)):"ref"===e?f.h=b:b.setAttribute(String(e),
String(f));a&&a.appendChild(b);return b}h(a){(a=this.create(a))&&Va(this,a);return a}async i(a){(a=this.create(a))&&await Wa(this,a);return a}}class Za extends J{h(a){a&&Va(this,a);return null}async i(a){a&&await Wa(this,a);return null}}class $a extends Za{constructor(a){super(a);this.children=a.itens}}class ab extends J{h(a){if(!a)throw Error("chain without parent");this.g.scn(new z(a),this.g.pmr);return null}async i(a){return this.h(a)}}
class bb extends J{h(){throw Error("ChainAsync requires Async");}async i(a){if(!a)throw Error("chain without parent");await this.g.acn(new z(a),this.g.pmr);return null}}function Ya(a){return a.replace(/[A-Z]/g,b=>`-${b.toLowerCase()}`)}function K(a,...b){a.children?b.length&&a.children.push(...b):a.children=b;return a}function L(a,b,...c){b=new Xa(b);b.l=a;c&&(b.children=Ma(c));return b}class M{static get g(){return J}static get h(){return Za}}
function I(a){const b=a?.[0];return 1===(a?.length??0)&&"function"===typeof b?b():a??[]};async function cb(a,b){const c=b.cloneNode(!1);a.j=[];const d=await a.i(c);Oa.set(a,{parent:c,W:d});w(c,b,{sa:!1});await Sa(a)};function db(a){const b=[];for(a=a.parentElement;a&&a!==document.documentElement;)a.classList&&a.classList.contains("dropdown-menu")&&b.unshift(a),a=a.parentElement;return b}var eb=a=>{const b=d=>d.classList.remove("show");let c=db(a);c.length||(c=[a]);c.forEach(d=>d.classList.remove("show"));c.length&&c[0].querySelectorAll(".show").forEach(b)};
function fb(a,b,c){const d=(new n(b.target)).h,e=(new n(b.target.closest(".dropdown-menu"))).D;if(e){var f=Array.from(e.children??[]),g=f.indexOf(d.closest("li")),h=d.closest(".dropdown-submenu");f=f.indexOf(h);b.stopPropagation();0<=g?(a=a[g],a?.select&&(c.close=!1),a?.s&&a.s(c),c.close&&eb(e)):0<=f&&(c.close=!1,a[f]?.s&&a[f].s(c),h.classList.toggle("show"),c.close&&eb(d));c.close=!0}}
function N(a){if(Array.isArray(a)&&0!==a.length)return a=a.filter(b=>void 0!==b).map(b=>b.trim()).filter(b=>0<b.length),a=[...(new Set(a.join(" ").split(/\s+/).filter(b=>0<b.length)))],0<a.length?{class:a.join(" ")}:void 0};function O(a,b,c){a.addEventListener(b,c)}
var gb=(a,b,c)=>{let d=["btn"],e=null;b.grid&&(e=a=D(a,"div",f=>F(f,{class:b.grid})));b.color&&d.push(`btn-${b.color}`);b.class&&d.push(b.class.trim());a=D(a,"button");F(a,{type:"button",class:d.join(" ")});b.lid&&F(a,{lid:b.lid});b.text?F(a,{_textContent:b.text}):b.ua?F(a,{_innerHTML:b.ua}):b.N&&b.N(a);c||a.J(f=>{O(f,"click",()=>{b.s&&b.s()})});return e?e:a},hb=(a,b)=>{a=gb(a,b);F(a,{data_bs_toggle:"dropdown",data_bs_reference:"parent",data_bs_auto_close:b.Wa});a.e.classList.add("dropdown-toggle");
return a},jb=(a,b)=>ib(a,()=>b),ib=(a,b)=>{const c={close:!1,refresh:async()=>{}},d=[],e=g=>{d[0]=b();let h=d[0];F(g,{class:`btn-group ${h.class??""}`,role:"group"});h.lid&&F(g,{lid:h.lid});h.style&&F(g,{style:h.style});h.ra?.forEach(k=>gb(g,{color:h.color,...k},!0));if(h.Fa||h.cb){const k=hb(g,{color:h.color,text:h.cb,Wa:h.Wa});h.ra&&k.e.classList.add("px-1");D(g,"ul",l=>{F(l,{class:"dropdown-menu"});h.Fa?.forEach(m=>{kb(l,m,c)})})}},f=D(a,"div");f.J(()=>{c.refresh=async()=>{await Da(f.root,async g=>
{e(g)},{va:["show"],ma:{class:"dropdown-menu show",keys:["style"]}})};O(f.root,"click",async g=>{var h=(new n(g.target)).h;h=Array.from(f.t.D.children).indexOf(h);const k=d[0];0<=h&&h<k?.ra?.length&&k.ra[h].s&&k?.ra[h].s();fb(k?.Fa??[],g,c)});O(f.root,"show.bs.dropdown",async()=>{eb(f.t.D)})});e(f);return f},kb=(a,b,c)=>{b||={Na:!0};let d=[];b.class&&d.push(b.class);a=D(a,"li");if(b.Na)d.push("dropdown-divider");else if(b.L)b.L(a,{}),(b.default??!0)&&d.push("dropdown-item");else if(b.ua)a.e.innerHTML=
b.ua,(b.default??!0)&&d.push("dropdown-item");else if(b.text)F(a,{_textContent:b.text}),(b.default??!0)&&d.push("dropdown-item");else if(b.select)b.select.refresh=c.refresh,lb(a,b.select);else if(b.xa){d.push("dropdown-submenu");kb(a,b.xa.label,c);let e=D(a,"ul");F(e,{class:"dropdown-menu"});b.xa.itens.forEach(f=>kb(e,f,c));e.J(()=>{O(e.root,"click",async f=>fb(b.xa.itens??[],f,c))})}F(a,{class:d.join(" ")});b.lid&&F(a,{lid:b.lid});return a},lb=(a,b)=>{const c=["form-select",b.class];"boolean"===
typeof b.P&&c.push(b.P?"form-select-lg":"form-select-sm");const d=D(a,"select");F(d,{...N(c)});b.lid&&F(d,{lid:b.lid});b.options?.forEach(e=>{D(d,"option").e.innerHTML=e});b.zb?d.t.select.selectedIndex=b.zb:b.sel&&(a=b.options.indexOf(b.sel),0<=a&&(d.t.select.selectedIndex=a));b.$&&d.J(e=>{O(e,"change",()=>{b.$({qa:d.t.select.value,yb:d.t.select.selectedIndex,refresh:b.refresh})})});return d},mb=(a,b,c)=>{const d=[b.class,b.grid],e="checkbox"===b?.input?.G;e&&c?d.push("form-check-inline"):c&&!b.grid&&
d.push("col-auto");const f=D(a,"div");b.lid&&F(f,{lid:b.lid});if(b.label&&!e){const g=[b.label.grid?"col-form-label":"form-label"];"boolean"===typeof b.label.P&&g.push(b.input.P?"form-control-lg":"form-control-sm");D(f,"label",h=>{F(h,{_textContent:b.label.text,...N([b.label.class,b.label.grid,...g])});b.label.Ib&&console.log(b.label.Ib)})}if(b.input){const g=[b.input.class];"boolean"===typeof b.input.P&&g.push(b.input.P?"form-control-lg":"form-control-sm");const h=[];let k=(()=>{const l=b.input.grid?
D(f,"div",m=>{b.input.grid&&F(m,{class:b.input.grid})}):f;if("textarea"===b.input.G)return g.push("form-control"),b.input.value&&h.push(m=>F(m,{_textContent:b.input.value[0]})),D(l,"textarea",m=>{b.input.Gb&&F(m,{rows:b.input.Gb})});if(b.input.G)return e?(g.push("form-check-input"),d.includes("form-check")||d.push("form-check")):g.push("form-control"),b.input.value&&(e&&b.input.value[0]?h.push(m=>F(m,{checked:void 0})):h.push(m=>F(m,{value:b.input.value[0]}))),D(l,"input",m=>F(m,{type:b.input.G}));
if(b.input.select)return lb(l,b.input.select);throw Error("type form-item ??");})();b.input.Lc&&g.push("form-control-plaintext");b.input.autocomplete&&F(k,{autocomplete:b.input.autocomplete});F(k,{...N(g)});h.forEach(l=>l(k));b.input.placeholder&&F(k,{placeholder:b.input.placeholder});b.input.readonly&&F(k,{readonly:void 0});b.input.value&&k.J(l=>{O(l,"change",()=>{e?b.input.value[0]=k.t.input.checked:"textarea"===b.input.G?b.input.value[0]=k.t.qb.value:b.input.G&&(b.input.value[0]=k.t.input.value)})})}if(b.label&&
e){const g=b.label.grid?"col-form-check-label":"form-check-label";if(b.label.grid)throw Error("Existe ??");D(f,"label",h=>{F(h,{_textContent:b.label.text,...N([g,b.label.class,b.label.grid])})})}b.col&&(F(f,{...N(["row",...d])}),b.col.forEach(g=>mb(f,g,!0)));b.D&&f.t.D.appendChild(b.D);b.sb&&b.sb(f,{});b.text&&F(D(f,"div"),{_textContent:b.text,class:"form-text"});b.small&&F(D(f,"small"),{_textContent:b.small});b.ta&&f.J(()=>{O(f.t.D,"change",()=>b.ta())});F(f,{...N(d)});return f},nb=(a,b)=>{const c=
A("div");F(c,{class:"modal fade",tabindex:-1,role:"dialog"});D(c,"div",d=>{F(d,{...N(["modal-dialog",a.class])});D(d,"div",e=>{F(e,{class:"modal-content"});D(e,"div",f=>{F(f,{class:a.title?"modal-header":"col-auto d-flex justify-content-end"});a.title&&D(f,"h5",g=>g.e.textContent=a.title);D(f,"button",g=>{F(g,{class:"btn-close",data_bs_dismiss:"modal"});b?.resolve&&g.J(()=>{O(g.e,"click",()=>b.resolve(void 0))})})});D(e,"div",f=>{F(f,{class:"modal-body"});a.ua?f.e.innerHTML=a.ua:a.text?f.e.innerHTML=
a.text:a.N&&a.N(f)});(a.Y||a.X)&&D(e,"div",f=>{F(f,{class:"modal-footer"});if(a.Y){let g=gb(f,{color:"primary",...a.Y});(a.Za??!0)&&F(g,{data_bs_dismiss:"modal"})}a.X&&(f=gb(f,{color:"secondary",...a.X}),(a.Za??!0)&&F(f,{data_bs_dismiss:"modal"}))})})});return c.t.D},ob=(a,b)=>{let c;document.fullscreenElement&&(document.fullscreenElement.append(a),c=A("div").t.D,c.className="modal-backdrop fade show",document.fullscreenElement.append(c));let d=bootstrap.Modal.getOrCreateInstance(a,{});O(a,"hidden.bs.modal",
()=>{c&&c.remove();a.remove();b&&b()});return d};
function pb(a,b){const c=D(a,"ul",d=>F(d,{class:"pagination"}));b.itens.forEach((d,e)=>D(c,"li",f=>{const g=["page-item"];(d.active||(b.active??[]).includes(e))&&g.push("active");F(f,{...N(g)});F(D(f,"a"),{class:"page-link",href:"#",_textContent:d.text??""})}));c.J(()=>{O(c.root,"click",d=>{d=(new n(d.target.closest("li"))).h;d=Array.from(c.t.i.children).indexOf(d);b.active&&(b.active.length=0,b.active.push(d));b.itens.at(d)?.s&&b.itens.at(d).s()})})}function qb(a,b){return rb(a,()=>b)}
function rb(a,b){const c=[];var d=async()=>{};let e;const f=g=>{const h=b();c[0]=h;const k=[],l=[],m=[];let p=0;h.head.itens.forEach((q,r)=>{q.pb&&l.push(r);q.width&&(k[r]=q.width)});(l||k)&&Ja(g,q=>{let r="table";h.ab&&(r=("#"===h.ab[0]?"":"#")+h.ab+" "+r);h.Ma&&(r+="."+h.Ma);l.forEach((u,x)=>{let H=k[u]??150;const y=m.length+1;C(q,`${r} th:nth-child(${y}), ${r} td:nth-child(${y})`,B=>{B("position: sticky;");B(`left: ${p}px;`);B("z-index: 1010;");B(`width: ${H}px;\n`)});x===l.length-1&&C(q,`${r} th:nth-child(${y})::after, ${r} td:nth-child(${y})::after`,
B=>{B("content: '';");B("position: absolute;");B("top: 0; right: 0px; height: 100%; width: 2px;");B("background-color: #dee2e6;")});p+=H;m.push(u)});C(q,`${r} thead th`,u=>{u("background-color: inherit;");u("user-select: none;")});h.head.itens.forEach((u,x)=>{if(!l.includes(x)){let H=k[x]??150;u=m.length+1;C(q,`${r} th:nth-child(${u}), ${r} td:nth-child(${u})`,y=>{y(`width: ${H}px;`)});m.push(x)}});C(q,r,u=>{u("table-layout: fixed;")})});e=g=D(g,"table");F(g,{...N(["table",h.class,h.Ma])});h.style&&
F(g,{style:h.style});D(g,"thead",q=>{h.head?.class&&F(q,{class:h.head.class});h.head?.style&&F(q,{style:h.head?.style});let r=h.head?.itens??[];m.length&&(r=m.map(u=>r[u]));r.forEach(u=>{D(q,"th",x=>{F(x,{scope:"col"});u.style&&F(x,{style:u.style});u.text&&F(x,{_textContent:u.text});u.L&&u.L(x,h.Cb??{})})})});D(g,"tbody",q=>{h.rows?.forEach((r,u)=>{D(q,"tr",x=>{F(x,{lid:u});r.class&&F(x,{class:r.class});let H=r?.itens??[];m.length&&(H=m.map(y=>H[y]));H.forEach(y=>{let B=D(x,"td");if(y.pb||y.width)throw Error("width / tick definir no head");
y.text&&F(B,{_textContent:y.text});y.L&&y.L(B,h.Cb??{});y.style&&F(B,{style:y.style})})})})})};f(a);d=async()=>Da(a.root,async g=>f(g),{});e.J(()=>{function g(k,l,m){var p=k.closest("td,th");const q=k.closest("tr,thead");k=Array.from(q.closest("tbody")?.children??[]).indexOf(q);p=Array.from(q.children).indexOf(p);const r=c[0];if(r.Ea){const u={refresh:d,x:l,y:m,Eb:k,col:p};sb(()=>r.Ea(u))}}const h=e.t.table;O(h,"contextmenu",k=>{k.preventDefault();k.stopPropagation();return g((new n(k.target)).h,
k.pageX,k.pageY)});O(h,"touchstart",k=>{const l=k.touches[0],m=l.clientX+window.scrollX,p=l.clientY+window.scrollY,q=setTimeout(()=>{g((new n(k.target)).h,m,p)},500);h&&(O(h,"touchend",()=>clearTimeout(q)),O(h,"touchmove",()=>clearTimeout(q)))})});a.J(()=>{console.log("conectou ctab")});return e};var tb={vb:a=>{Ja(a,b=>{C(b,".dropdown-menu .dropdown-submenu",c=>{c("position: relative;")});C(b,".dropdown-menu .dropdown-submenu > .dropdown-menu",c=>{c("display: none;");c("position: absolute;");c("left: 100%;");c("top: 0;");c("margin-top: -1px;")});C(b,".dropdown-menu .dropdown-submenu:hover > .dropdown-menu,.dropdown-menu .dropdown-submenu.show > .dropdown-menu",c=>{c("display: block;")})})},Ec:(a,b)=>{Ja(a,c=>{C(c,`.${b.name} .dropdown-item:hover,`+`.${b.name} .dropdown-item:focus`,d=>{b.rb&&
d(`background-color: ${b.rb};`);b.color&&d(`color: ${b.color};`)})})}},P={Mc:"primary",Qc:"secondary",Sa:"success",ub:"danger",Uc:"warning",info:"info",Oa:"light",zc:"dark",link:"link"},Q={button:"button",La:"checkbox",color:"color",Ac:"date",Bc:"datetime-local",email:"email",file:"file",hidden:"hidden",image:"image",month:"month",Jc:"number",password:"password",Nc:"radio",Oc:"range",reset:"reset",search:"search",submit:"submit",Tc:"tel",text:"text",time:"time",url:"url",Vc:"week",qb:"textarea"};
function ub(a,b){return gb(a,b)}function vb(a,b){lb(a,b)}function wb(a,b){mb(a,b,!1)}
function sb(a){function b(h){if(!g.contains(h.target)||"mousedown"===h.type&&0!=h.button)g.remove(),document.removeEventListener("mousedown",b)}const c=A("div"),d={close:!0,refresh:async()=>{}},e=[],f=h=>{F(h,{class:"dropdown-menu show"});e[0]=a();const k=e[0];if(k){k.itens.forEach(m=>{kb(h,m,d)});var l=h.t.D;l.style.left=`${k.x}px`;l.style.top=`${k.y}px`;l.style.zIndex=1020}};d.refresh=async()=>Da(c.root,async h=>f(h),{});f(c);if(e[0]){var g=c.t.D;g.addEventListener("click",async h=>{const k=e[0];
k&&fb(k.itens,h,d)});document.fullscreenElement?document.fullscreenElement.appendChild(g):document.body.appendChild(g);e[0]&&!e[0].wc&&document.addEventListener("mousedown",b)}}function R(a,b){let c;if(b.Ya)c=D(a,"form");else if(!b.Ya||b.class)c=D(a,"div");b.class&&F(c,{class:b.class});const d=(b.class??"").split(" ").includes("row");b.item.forEach(e=>mb(c,e,d));return c}async function xb(a){Ea.Pa=!0;const b=nb(a);return new Promise(c=>{ob(b,()=>c(a.resolve?a.resolve():void 0)).show()})}
async function yb(a){const b=A("div");F(b,{class:"modal fade",tabindex:-1,role:"dialog"});D(b,"div",d=>{F(d,{class:"modal-dialog"});D(d,"div",e=>{F(e,{class:"modal-content"})})});let c=[void 0];return new Promise((d,e)=>{const f=ob(b.t.D,()=>d(c[0]?c[0]():void 0)),g={kb:f,resolve:d,reject:e,root:b.t.D,refresh:()=>{var h=a(g);c[0]=h.resolve;h=nb(h,g);w(h,b.t.D,{sa:!1,va:["show"],ma:{class:"modal",keys:["style"]}})}};g.refresh();f.show()})}function zb(a,b){pb(a,b)}function Ab(a,b){qb(a,b)};const S=new Map,Bb=S.delete.bind(S),Cb=new BroadcastChannel("ib");Cb.onmessage=a=>{a=a.data;1===a.m&&(S.get(a.n)?.close(),Bb(a.n))};S.delete=a=>{Cb.postMessage({m:1,n:a});return Bb(a)};
async function Db(a,b){var c=S.get(a);if(c&&!b)return c;let d;b&&(c=await Db(a),d=c.version+1,c.close());return new Promise((e,f)=>{let g=!1,h=!1;setTimeout(()=>{g||f(Error(`indexedDB timeout: bloqueado: ${h?"essa aba":"outra"} (${a})`))},100);const k=indexedDB.open(a,d);k.onsuccess=l=>{g=!0;l=l.target.result;S.set(a,l);e(l)};k.onerror=l=>{g=!0;f(l.target.error)};k.onupgradeneeded=l=>{g=!0;l=l.target.result;b&&b(l)};k.onblocked=()=>{h=!0}})}
async function Eb(a,b){let c=await Db(a);c.objectStoreNames.contains(b)||(c.close(),c=await Db(a,d=>{d.createObjectStore(b)}));return c}async function Fb(a,b){let c=await Db(a);c.objectStoreNames.contains(b)&&(c.close(),c=await Db(a,d=>{d.deleteObjectStore(b);console.log("apagado")}));return c}async function Gb(a){return await Eb(a.h,a.g)}
async function Hb(a,b,c,...d){const e=a.i.transaction([a.g],b).objectStore(a.g)[c](...d);return new Promise((f,g)=>{e.onsuccess=h=>{f(h.target.result)};e.onerror=h=>{g(h.target.error)}})}async function Ib(a,b){await Hb(a,"readwrite","delete",b)}async function Jb(a){await Fb(a.h,a.g)}class Kb{constructor(a){const [b,c]=a.split(".");this.h=b;this.g=c}get i(){return S.get(this.h)}async get(a){return await Hb(this,"readonly","get",a)}async set(a,b){await Hb(this,"readwrite","put",b,a)}};function Lb(a,b){for(let c of a)if(b===`${c.etype}.${c.name}`)return c;return null}
const Mb={[1]:"Nome de usu\u00e1rio n\u00e3o pode conter espa\u00e7os",[2]:"Email inv\u00e1lido",[3]:"Usu\u00e1rio j\u00e1 existe",[4]:"C\u00f3digo de valida\u00e7\u00e3o inv\u00e1lido ou expirado",[5]:"N\u00famero m\u00e1ximo de tentativas de senha excedido. Tente novamente mais tarde",[6]:"Senha incorreta",[7]:"Usu\u00e1rio n\u00e3o encontrado",[8]:"Formato do request",[9]:"Item n\u00e3o encontrado",[10]:"Par\u00e2metro inv\u00e1lido",[11]:"Id repetido em UserData",[12]:"Id n\u00e3o achado UserData",
[13]:"Erro nos arquivos do usu\u00e1rio",[101]:"Usu\u00e1rio n\u00e3o autenticado",[102]:"Download incompleto",[103]:"erro na requsi\u00e7\u00e3o / servidor",[104]:"propriedade n\u00e3o acess\u00edvel"};function Nb(a){const b=new Map;a.forEach(c=>{const d=`${c.name}-${c.etype}`,e=b.get(d);(!e||new Date(c.update)>new Date(e.update))&&b.set(d,c)});return Array.from(b.values())};const Ob={dc:0,Mb:1,POINTS:2,Xb:3,Ub:4};var Pb=[0,1,2,3,4,5,6,7,8,9],Qb=[15,16,17,18,19,20],Rb=[10,11,12,13,21,22],Sb=[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012];const Tb={Jb:66,Kb:89,Nb:88,Ob:72,Pb:67,Qb:70,Rb:65,Sb:69,Tb:68,Lb:78,Vb:71,oc:73,nc:105,Yb:75,Zb:85,bc:77,cc:80,ec:84,fc:79,hc:76,ic:81,jc:82,mc:83,qc:86,rc:87},Ub={pc:0,kc:1},Vb={ac:0,$b:1,lc:2,sc:3,tc:4,uc:5,Wb:6};async function Wb(a,b={}){a=new Response(new Blob([a],{type:"application/wasm"}));return await WebAssembly.instantiateStreaming(a,b)}function T(a,b){return a.F.instance.exports[b]}async function Xb(a,b){a.F=await Wb(b,{wasi_snapshot_preview1:a.l,env:a.l});a.J.forEach(c=>c());a.B()}async function Yb(a){if(!a.F){var b=await fetch(`${"teste.wasm"}?v=${Date.now()}`);b.ok&&(b=await b.arrayBuffer(),await Xb(a,b))}}
class Zb{constructor(){this.J=[()=>{this.o=T(this,"memory");this.j=this.o.buffer;this.u=new Uint8Array(this.j)},()=>this.M=T(this,"c01"),()=>T(this,"c02"),()=>this.B=T(this,"_start")]}get h(){this.o.buffer!==this.j&&(this.j=this.o.buffer,this.u=new Uint8Array(this.j));return this.u}M(){throw Error("Not initialized");}B(){throw Error("Not initialized");}get l(){return this.C}get C(){return{environ_get:(a,b)=>{console.log("environ_get",a,b);return 0},environ_sizes_get:(a,b)=>{console.log("environ_sizes_get",
a,b);const c=new DataView(this.o.buffer);c.setUint32(a,0,!0);c.setUint32(b,0,!0);return 0},fd_close:()=>{console.log("fd_close")},fd_prestat_get:()=>{console.log("fd_close")},fd_prestat_dir_name:()=>{console.log("fd_close")},proc_exit:()=>{console.log("proc_exit")},fd_seek:()=>{console.log("fd_seek")},fd_write:()=>{console.log("fd_write")}}}}
function $b(a,b,c,d,e,f){1==c?a.g[b]=f:2===c?a.g[b][e]=f:3===c?a.g[b][a.i.decode(a.h.subarray(d,d+e))]=f:4===c&&(b=a.i.decode(a.h.subarray(d,d+e)).split("."),c=a.g,a=b.pop(),(b=b.reduce((g,h)=>g?.[h],c))&&a in b&&(b[a]=f))}function U(a,b,c,d,e){if(1==c)return a.g[b];if(2===c)return a.g[b][e];if(3===c)return a.g[b][a.i.decode(a.h.subarray(d,d+e))];if(4===c){let f=a.g[b];a.i.decode(a.h.subarray(d,d+e)).split(".").forEach(g=>f=f[g]);return f}}
class ac extends Zb{constructor(){super();this.J.push(()=>T(this,"c03"),()=>T(this,"c02"));this.g=[];this.i=new TextDecoder;this.aa=new TextEncoder;this.g[0]=window}get l(){return{...this.C,...this.ba}}get ba(){return{j01:this.ca.bind(this),j02:this.fa.bind(this),j03:this.da.bind(this),j04:this.ia.bind(this),j05:this.ha.bind(this),j06:this.ga.bind(this),j07:this.write.bind(this),j08:this.U.bind(this),j09:this.ja.bind(this),j10:this.T.bind(this),j11:this.ea.bind(this)}}ca(a,b,c,d){1==b?delete this.g[a]:
2===b?delete this.g[a][d]:3===b?delete this.g[a][this.i.decode(this.h.subarray(c,c+d))]:4===b&&(a=this.g[a],d=this.i.decode(this.h.subarray(c,c+d)).split("."),c=d.pop(),(d=d.reduce((e,f)=>e?.[f],a))&&c in d&&delete d[c])}fa(a,b,c,d){$b(this,a,b,c,d,{})}da(a,b,c,d){$b(this,a,b,c,d,[])}ia(a,b,c,d){return U(this,a,b,c,d)}ha(a,b,c,d){return U(this,a,b,c,d)}ga(a,b,c,d){a=U(this,a,b,c,d);a=this.aa.encode(a);b=this.M(a.length+1);this.h.set(a,b);this.h[b+a.length]=0;return b}write(a,b,c,d,e,f,g,h){e=2===
e?g:3===e?h:4===e?this.i.decode(this.h.subarray(f,f+g)):void 0;$b(this,a,b,c,d,e)}U(a,b,c,d,e,f,g,h){$b(this,e,f,g,h,U(this,a,b,c,d))}ja(a,b,c,d,e,f){a=U(this,a,b,c,d)(...(e?this.g[e]:[]));f&&(this.g[f]=a)}async T(a,b,c,d,e,f){a=await U(this,a,b,c,d)(...(e?this.g[e]:[]));f&&(this.g[f]=a)}ea(a,b,c,d,e,f){a=new (U(this,a,b,c,d))(...(e?this.g[e]:[]));f&&(this.g[f]=a)}};class bc extends ac{};class cc extends bc{constructor(){super();const a=this;this.J.push(()=>this.R=T(a,"c05"),()=>T(a,"c06"))}R(){throw Error("Not initialized");}};function dc(a,b){a.u=b(1);a.B=b(2);a.C=b(3);a.F=b(4);a.M=b(5);a.R=b(6);a.T=b(7);a.U=b(8);a.aa=b(9);a.ba=b(10);a.ca=b(11);a.da=b(12)}
class ec{constructor(){this.$a="SUN";this.Aa="MOON";this.za="MERCURY";this.hb="VENUS";this.ia="MARS";this.ha="JUPITER";this.Xa="SATURN";this.fb="URANUS";this.Ba="NEPTUNE";this.Ua="PLUTO";this.o="CHIRON";this.Ta="PHOLUS";this.j="CERES";this.Ca="PALLAS";this.ga="JUNO ";this.ib="VESTA";this.ya="MEAN_NODE";this.eb="TRUE_NODE";this.ja="MEAN DARK MOON";this.bb="TRUE DARK MOON";this.l="EARTH";this.ea="INTP_APOG";this.fa="INTP_PERG";this.da=this.ca=this.ba=this.aa=this.U=this.T=this.R=this.M=this.F=this.C=
this.B=this.u="";dc(this,a=>`H${String(a).padStart(2,"0")}`);this.h=this.i=null}get g(){if(!this.i){const a=this.i={};a[0]=this.$a;a[1]=this.Aa;a[2]=this.za;a[3]=this.hb;a[4]=this.ia;a[5]=this.ha;a[6]=this.Xa;a[7]=this.fb;a[8]=this.Ba;a[9]=this.Ua;a[10]=this.ya;a[11]=this.eb;a[12]=this.ja;a[13]=this.bb;a[14]=this.l;a[21]=this.ea;a[22]=this.fa;a[15]=this.o;a[16]=this.Ta;a[17]=this.j;a[18]=this.Ca;a[19]=this.ga;a[20]=this.ib;a[1001]=this.u;a[1002]=this.B;a[1003]=this.C;a[1004]=this.F;a[1005]=this.M;
a[1006]=this.R;a[1007]=this.T;a[1008]=this.U;a[1009]=this.aa;a[1010]=this.ba;a[1011]=this.ca;a[1012]=this.da}return this.i}get xb(){this.h||(this.h={},Object.entries(this.g).forEach(([a,b])=>{this.h[b]=Number(a)}));return this.h}}
class fc{constructor(){this.j="ALCABITUS";this.o="APC";this.u="AXIAL_ROTATION";this.B="AZIMUTHAL";this.C="CAMPANUS";this.F="CARTER_POLI_EQ";this.M="EQUAL_ASC";this.R="EQUAL_ASC_ALT";this.T="EQUAL_MC";this.l="ARIES_EQUAL";this.U="GAUQUELIN";this.za="SUNSHINE_TREINDL";this.ya="SUNSHINE_MAKRANSKY";this.aa="KOCH";this.ba="KRUSINSKI";this.ca="MORINUS";this.da="PLACIDUS";this.ea="POLICH_PAGE";this.fa="PORPHYRIUS";this.ga="PULLEN_SD";this.ha="PULLEN_SR";this.ia="REGIOMONTANUS";this.ja="SRIPATI";this.Aa=
"VEHLOW";this.Ba="WHOLE_SIGN";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[66]=this.j;a[89]=this.o;a[88]=this.u;a[72]=this.B;a[67]=this.C;a[70]=this.F;a[65]=this.M;a[69]=this.R;a[68]=this.T;a[78]=this.l;a[71]=this.U;a[73]=this.za;a[105]=this.ya;a[75]=this.aa;a[85]=this.ba;a[77]=this.ca;a[80]=this.da;a[84]=this.ea;a[79]=this.fa;a[76]=this.ga;a[81]=this.ha;a[82]=this.ia;a[83]=this.ja;a[86]=this.Aa;a[87]=this.Ba}return this.h}get Ca(){this.g||(this.g={},Object.entries(this.i).forEach(([a,
b])=>{this.g[b]=Number(a)}));return this.g}}class gc{constructor(){this.o="TROPICAL";this.j="SIDERAL";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[0]=this.o;a[1]=this.j}return this.h}get l(){this.g||(this.g={},Object.entries(this.i).forEach(([a,b])=>{this.g[b]=Number(a)}));return this.g}}
class hc{constructor(){this.u="LONG";this.l="LAT";this.o="SPEED";this.B="X";this.C="Y";this.F="Z";this.j="HOUSE";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[0]=this.u;a[1]=this.l;a[2]=this.o;a[3]=this.B;a[4]=this.C;a[5]=this.F;a[6]=this.j}return this.h}get M(){this.g||(this.g={},Object.entries(this.i).forEach(([a,b])=>{this.g[b]=Number(a)}));return this.g}}
class ic{constructor(){this.u="PLANETS";this.j="ASTEROIDS";this.B="POINTS";this.l="HOUSE CUSPS";this.o="EXTRA";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[0]=this.u;a[1]=this.j;a[2]=this.B;a[3]=this.l;a[4]=this.o}return this.h}get C(){this.g||(this.g={},Object.entries(this.i).forEach(([a,b])=>{this.g[b]=Number(a)}));return this.g}}class jc{constructor(){this.g=new ec;this.calc_info=new hc;this.h=new ic;this.i=new fc;this.j=new gc}}const kc=new jc;
(function(a){a.$a="SOL";a.Aa="LUA";a.za="MERC\u00daRIO";a.hb="VENUS";a.ia="MARTE";a.ha="JUP\u00cdTER";a.Xa="SATURNO";a.fb="URANO";a.Ba="NETUNO";a.Ua="PLUT\u00c3O";a.o="QU\u00cdRON";a.Ta="FOLO";a.j="CERES";a.Ca="PALAS";a.ga="JUNO ";a.ib="VESTA";a.ya="NODO NORTE MED.";a.eb="NODO NORTE VERD.";a.ja="LUA NEGRA MED.";a.bb="LUA NEGRA VERD.";a.l="TERRA";a.ea="APOGEU INTERP.";a.fa="PERIGEU INTERP.";dc(a,b=>`CASA ${String(b).padStart(2,"0")}`)})(kc.g);var lc=kc.calc_info;lc.o="VELOC";lc.j="CASA";var mc=kc.h;
mc.u="PLANETAS";mc.j="ASTER\u00d3IDES";mc.B="PONTOS";mc.l="C\u00daSPIDE DAS CASAS";mc.o="EXTRA";async function nc(){return new Promise((a,b)=>{if("undefined"!==typeof JSZip)a();else{var c=document.createElement("script");c.src=fa()+"cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";c.onload=a;c.onerror=()=>b(Error("Falha ao carregar JSZip"));document.head.appendChild(c)}})}async function V(){await nc();const a=new JSZip;a.entries=()=>Object.entries(a.files).map(([b,c])=>{c.Va=async()=>await c.async("string");return{filename:b,data:c}});return a}
async function oc(a){a=atob(a);var b=a.length;const c=new Uint8Array(b);for(let d=0;d<b;d++)c[d]=a.charCodeAt(d);a=c.buffer;b=await V();await b.loadAsync(a);return b}async function pc(a){const b=await V();b.file("_",a);return await b.generateAsync({type:"uint8array"})}async function qc(a){let b=await V();await b.loadAsync(a);return await b.files._.async("string")};async function rc(a){return await (await fetch("https://script.google.com/macros/s/AKfycbz8kvZBqee545Q7d9yebhOuDfH7JYvLqaN_sZxSSK1Mi9Q23us-MvgSUsCkbNooyKy61A/exec",{method:"POST",headers:{"Content-Type":"text/plain"},body:a})).text()}
async function sc(a){const b=await V();b.file("q",JSON.stringify(a));a=await b.generateAsync({type:"base64"});const c=await rc(a);if(c.includes("<!DOCTYPE"))throw await xb({title:"ERROR",N:d=>Ia(d,c)}),Error(102);a=JSON.parse(c);isNaN(Number(a.error))?a.error&&console.log(a.error):console.log(Mb[parseInt(a.error,0)]);return a}async function tc(a){a=(await oc(a)).files.p;if(!a)throw Error();return await a.async("string")}
async function uc(a,b,c,d,e){a=await sc({user:a,password:b,request:1,data:{name:c,byteSize:d,ichunk:e}});if(a.rdata){a=atob(a.rdata);b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=a.charCodeAt(c);a=b}else a=null;return a}async function vc(a,b){a=await sc({user:a,password:b,request:0});b=a.error;b={error:!b||isNaN(parseInt(b,10))?void 0:parseInt(b,10)};if(!a.rdata)return b;b.Ia=await JSON.parse(await tc(a.rdata));return b}
async function wc(a,b,c,d){async function e(r){for(;6>=g;){let u=await uc(a,b,c,f,r);if(u){m[r]=u;console.log(r,"processado",u.length,"ativos",h.length);return}g++}p=!0}var f=void 0;let g=0,h=[],k=0;f||=1E6;let l=Math.ceil(d/f),m=Array(l),p=!1;await async function(){for(;k<l;){5<=h.length&&await Promise.race(h);let r=e(k).catch(u=>console.error(u)).finally(()=>{h=h.filter(u=>u!==r)});h.push(r);await Ka();k++}await Promise.all(h)}();if(p)return console.log("erro"),null;d=m.reduce((r,u)=>r+u.length,
0);d=new Uint8Array(d);let q=0;for(let r=0;r<m.length;r++)d.set(m[r],q),q+=m[r].length;return d}async function xc(a,b,c,d,e,f){const g=Array(f.length);for(let h=0;h<f.length;h++)g[h]=String.fromCharCode(f[h]);a=await sc({user:a,password:b,request:2,data:{name:c,mimetype:"application/zip",etype:e,update:d,t64array:btoa(g.join(""))}});return a.rdata?JSON.parse(a.rdata):null}async function yc(a,b,c){a=await sc({user:a,password:b,request:3,data:c});return a.rdata?JSON.parse(a.rdata):null};async function zc(a,b,c){const d=`${a.etype}.${a.name}`,e=v(d);if(a=await Ac(b,d,a.size))return await c.set(e,a),a;await Ib(c,e);console.error(Mb[102]);return null}async function Bc(a,b){a=v(`${a.etype}.${a.name}`);await Ib(b,a)}async function Cc(){const a=new Dc;a.h=[];a.i=new Kb("mandala._");await Gb(a.i);await Ec(a);return a}async function Ec(a){var b=await a.i.get("z");b?(b=await qc(b),a.h=JSON.parse(b)):a.h=[];2===a.g&&(a.g=1)}
async function Fc(a){let b=await pc(JSON.stringify(a.h));await a.i.set("z",b)}async function Gc(a){a.h=[];await Ib(a.i,"z");await Ib(a.i,"l");await Ib(a.i,"s")}async function Hc(a){var b=async d=>{d=await a.i.get(d);if(!d)return null;d=await qc(d);return JSON.parse(d)};const c=await b("l");if(c)return c;b=await b("s");b.itens=[];return b}
class Dc{async j(a,b){a=await pc(JSON.stringify(a));await this.i.set(b?"s":"l",a)}get username(){return String(this.h[0]??"")}set username(a){this.h[0]=a}get password(){return String(this.h[1]??"")}set password(a){this.h[1]=a}get g(){return parseFloat(this.h[2])}set g(a){this.h[2]=a}get l(){return[1,2,3].includes(this.g)}get u(){return[2,3].includes(this.g)}get o(){return 3===this.g}}var Ic=new WeakMap;
async function Jc(a){if(!a.i)return null;const b=v(a.username),c=new Kc;c.h=new Kb("mandala."+b);c.g=a;await Gb(c.h);return c}async function Lc(a){await Jb(a.h)}async function Mc(a,b){b=v(`${b.etype}.${b.name}`);return await a.h.get(b)}
async function Nc(a,b){var c=(await Oc(a.g))?.itens??[];let d=b.itens??[];d=Nb(d);let e=[],f=!1;var g=!1;let h=!1;for(var k of d){let l=Lb(c,`${k.etype}.${k.name}`);const m=await Mc(a,k);l&&m?l.update===k.update&&l.size===k.size&&l.deleted===k.deleted?e.push(l):new Date(l.update)>new Date(k.update)?(l.deleted?(g=await Pc(a.g,l.id))?e.push(g):h=!0:(g=await Qc(a.g,l.name,l.update,l.etype,m))?e.push(g):h=!0,g=!0):new Date(l.update)<new Date(k.update)?(k.deleted?(await Bc(k,a.h),e.push(k)):await zc(k,
a.g,a.h)?e.push(k):h=!0,f=!0):l.size!==k.size&&(await zc(k,a.g,a.h)?e.push(k):h=!0,f=!0):(await zc(k,a.g,a.h)?e.push(k):h=!0,f=!0)}for(let l of c)c=Lb(d,`${l.etype}.${l.name}`),k=await Mc(a,l),!c&&k&&((g=await Qc(a.g,l.name,l.update,l.etype,k))?e.push(g):h=!0,g=!0);f||g?console.log(`update com atualiza\u00e7\u00e3o ${f?"local":""} ${g?"no servdior":""} `):console.log("update sem atualiza\u00e7\u00e3o");h||(b.itens=e,(a=Ic.get(a.g))&&await a.j(b));return{Sc:g,Hc:f,error:h}}
async function Rc(a,b){if(!a.g.j)throw Error(Mb[101]);var c=await V();for(let [e,f]of Object.entries(b))c.file(e,f);b=await c.generateAsync({type:"uint8array"});c=v("1.menu_action");await a.h.set(c,b);c=await Oc(a.g);let d=Lb(c.itens,"1.menu_action");d?c.itens=c.itens.filter(e=>"1.menu_action"!==`${e.etype}.${e.name}`):d={name:"menu_action",etype:1,id:"",size:0,update:""};d.size=b.byteLength;d.update=(new Date).toISOString();c.itens.push(d);Ic.get(a.g)?.j(c)}
async function Sc(a){var b=v("1.menu_action");b=await a.h.get(b);if(!b)return null;a=await V();await a.loadAsync(b);b={};for(let c of a.entries())b[c.filename]=await c.data.Va();return b}class Kc{}async function Tc(){let a=new Uc;a.g=await Cc();a.h=await Jc(a);Ic.set(a,a.g);return a}async function Ac(a,b,c){if(!a.j)throw Error(101);return wc(a.username,a.g.password,b,c)}async function Oc(a){return a.i?Hc(a.g):null}
async function Pc(a,b){if(!a.j)throw Error(101);return yc(a.username,a.g.password,b)}async function Qc(a,b,c,d,e){if(!a.j)throw Error(101);return xc(a.username,a.g.password,b,c,d,e)}async function Vc(a){return(await Hc(a.g)).itens.filter(b=>0===b.etype)}async function Wc(a,b){if(!a.h)throw Error(101);return Mc(a.h,b)}async function Xc(a){await Gc(a.g);a.h&&await Lc(a.h);a.h=null}
async function Yc(a,b,c){let d={};await Ec(a.g);b&&b!==a.username?(a.username=b,a.password="",a.g.g=0,await Fc(a.g)):b||(b=a.username);c&&c!==a.g.password?(a.password="",a.g.g=0,await Fc(a.g)):c||(c=a.g.password);b&&c&&(d=await vc(b,c),6===d.error?await Xc(a):7===d.error&&await Xc(a));d.Ia&&!d.error&&(a.g.g=2,a.username=b,a.password=c,await a.g.j(d.Ia,!0),a.h=await Jc(a),await Fc(a.g),console.log("login verified"));return d.Ia&&!d.error?d.Ia:null}
async function Zc(a){if(!a.h)throw Error(101);return Sc(a.h)}async function $c(a,b){if(!a.h)throw Error(101);Rc(a.h,b)}async function ad(a,b){if(!a.h)throw Error(101);b=await Nc(a.h,b);a.g.g=3;return b}class Uc{get username(){return this.g.username}set username(a){this.g.username=a}get password(){throw Error(104);}set password(a){this.g.password=a}get i(){return this.g.l}get j(){return this.g.u}get o(){return this.g.o}};var bd=a=>a.layout_table?.itens[a.layout_table.sel]?.tab??[];const cd={yc:"PADR\u00c3O",xc:"TRADICIONAL",tb:"LISTAGEM"};async function dd(a){const b=new W;b.g=await Tc();b.status={};b.i=cd;b.h=a;return b}async function ed(a){return(a=(await Zc(a.g))?.["tables.json"])?JSON.parse(a):{layout_table:{itens:{},sel:""}}}async function fd(a,b){$c(a.g,{["tables.json"]:JSON.stringify(b)})}
async function gd(a){const b=[],c=(await Vc(a.g)).map(async d=>{const e=await Wc(a.g,d);if(e){var f=await V();await f.loadAsync(e);for(let g of f.entries()){const h={file:d.name,stream:g.filename,Ga:async function(){var k=await g.data.Va();k=JSON.parse(k);h.table=k;delete h.Ga;return k}};b.push(h)}}});await Promise.all(c);return b}class W{};async function hd(a,b){const c=new id;c.v=a;c.refresh=b;await jd(c);return c}
async function jd(a){await Gb(a.T);await Yb(a.u);a.o=(await ed(a.v)).layout_table;a.B=await gd(a.v);a.g=null;a.o&&a.o.sel&&(a.g=a.o.itens[a.o.sel],a.g.col=a.g.col.filter(e=>!1===e.on?!1:!0));a.i=[];a.l=[];if(a.g&&a.B)for(var b of a.g.tab){const e=a.g.tab.indexOf(b);for(var c of a.B)if(b===c.file){c.table||(c.table=await c.Ga());c.la||(c.la=c.table[0]);const f=c.la.indexOf("ENCODED");0<=f&&(c.Cc=1,a.l[e]=[],c.table.forEach(g=>{{const q=g[f].match(/^(\d+)(\w)(\d{2})(\d{2})(\d+)([-+]\d+(\.\d*)?)([-+]\d+(\.\d*)?)([-+]\d+(\.\d*)?)/);
if(q){g=parseInt(q[1],10);var h=parseInt(q[3],10),k=parseInt(q[4],10),l=parseInt(q[5].substring(0,2),10),m=parseInt(q[5].substring(2,4),10);6==q[5]&&(m+=parseInt(q[5].substring(4,6),10)/60);var p="CJBRcjbr".indexOf(q[2]);g={year:g,month:h,day:k,hour:l,minute:m,Hb:parseFloat(q[6]),Ab:parseFloat(q[8]),Bb:parseFloat(q[10]),Gc:p&1,vc:p>>1&1,Ic:p>>2&1}}else g=null}a.l[e].push(g)}));a.i.push(c)}}a.h=kd(a);a.C=new Map;b=a.g.col;for(c=0;c<b.length;c++){var d=b[c];if(d.extra){const e=new Map;a.C.set(c,e);
d=d.extra;for(let f=0;f<a.i.length;f++)e.set(f,a.i[f].la.indexOf(d))}}}function kd(a){const b=[];a.i.forEach((c,d)=>c.table.forEach((e,f)=>{0!==f&&b.push([d,f])}));return b}
function ld(a,b,c){const [d,e]=[b[0],b[1]];b=a.g.col[c];if(4===b.source)return(b=a.C.get(c)?.get(d))?a?.i[d]?.table[e][b]??"":null;c=a.l[d][e];if(!c)return null;if("number"===typeof b.point){const f=b.calc_info??-1;let g=b.ref;"number"!==typeof g&&(g=6===f?80:-1);a.u.g[4001]=a?.i[d]?.table[e][1];a.u.g[4002]=a?.i[d]?.table[e][21];return a.u.R(c.year,c.month,c.day,b.point,c.hour+c.minute/60+c.Hb,260,f,g,c.Ab,c.Bb)}return 1===b.point?6===b.calc_info:""}
function md(a,b){let c=[];const d=Array(a.g.col.length).fill(void 0);console.log("dr",a.h.length);console.log(a.h.slice(0,10).map(e=>e[1]));a.h.slice(0,b).forEach(e=>c.push(d.map((f,g)=>{var h=ld(a,e,g);"number"!==typeof h?f=h:(f=Math.floor(h),g=Math.floor(60*(h-f)),h=Math.round(60*(60*(h-f)-g)),60===h&&(g++,h=0),60===g&&(f++,g=0),(void 0)?.Rc?f=`${f}\u00ba${String(g).padStart(2,"0")}'${String(h).padStart(2,"0")}"`:(30<=h&&g++,60===g&&(f++,g=0),f=`${f}\u00ba${String(g).padStart(2,"0")}'`));return f})));
return c}function nd(a,b,c){a.h.sort((d,e)=>c(ld(a,d,b),ld(a,e,b)))}function od(a,b){if(!a.j[b]){let c=new Set;a.h.forEach(e=>c.add(String(ld(a,e,b))));let d=[];[...c].sort().forEach(e=>d.push({item:e,on:!0}));a.j[b]=d}}function pd(a){let b=kd(a);a.j.forEach((c,d)=>{b=b.filter(e=>{e=ld(a,e,d);let f=!0;for(let g of c)if(g.item===e){f=g.on;break}return f})});return b}
class id{constructor(){this.i=this.g=this.o=this.B=null;this.M=50;this.R=new jc;this.C=new Map;this.h=[];this.j=[];this.l=[];this.T=new Kb("mandala.calcs");this.u=new cc}get F(){return this.g?.col.map(a=>{if(a.name)return a.name;if(a.extra)return a.extra;if(void 0!==a.point)return this.R.g.g[a.point]??""})??[]}get U(){return md(this,this.M)}Ea(a){console.log(a);if(void 0===a.col||-1!==a.Eb||void 0===a.x||void 0===a.y)return null;class b{constructor(){a.I||(a.I=new Map);void 0===a.I.get("col")&&a.I.set("col",
a.col)}get col(){return a.I.get("col")}set col(f){a.I.set("col",f)}}const c=new b,d=f=>(g,h)=>{let k=parseFloat(g),l=parseFloat(h);isNaN(k)||isNaN(l)||(g=k,h=l);g=g===h?0:g<h?-1:1;return f?g:-g};let e=this.j?.[c.col]?.map(f=>[f.on??!0]);return{x:a.x,y:a.y,itens:[{select:{options:this.F,sel:this.F[c.col],$:f=>{a.I.set("col",f.yb);f.refresh()}}},{xa:{label:{text:"ORDENAR"},itens:[{text:"CRESCENTE",s:f=>{f.close=!1;nd(this,c.col,d(!0));this.refresh()}},{text:"DECRESCENTE",s:f=>{f.close=!1;nd(this,c.col,
d(!1));this.refresh()}}]}},{xa:{label:{text:"FILTRAR"},itens:[{text:"LISTAR",s:f=>{f.close=!1;od(this,c.col);f.refresh()}},{L:f=>{let g=0;this.j?.[c.col]?.forEach(k=>{k.on&&g++});let h=[];this.j?.[c.col]?.forEach((k,l)=>h.push({label:{text:k.item},input:{G:Q.La,value:e[l]},ta:()=>{e.forEach((m,p)=>{this.j[c.col][p].on=m[0]});console.log("a",this.h.length);this.h=pd(this);console.log("d",this.h.length);this.refresh()}}));f=D(f,"div");F(f,{class:"ms-3"});R(f,{item:h})},s:f=>{f.close=!1},default:!1}]}}]}}}
async function qd(){console.log("no test")};class rd extends M.g{constructor(a){super(a);this.u=Ta(this);this.B.va=["show","collapsed","collapsing"];this.g.Z&&(this.g.Z.refresh=async b=>{void 0!==b&&(this.g.show=b);await this.refresh()})}o(){const a="h"+this.id,b="c"+this.id,c=this.l?"#"+this.l:"";return L("div",{class:"accordion-item"},L("h2",{class:"accordion-header",id:a},L("button",{class:"accordion-button"+(this.g.show?"":" collapsed"),type:"button","data-bs-toggle":"collapse","data-bs-target":"#"+b,"aria-expanded":this.g.show??!1,"aria-controls":b},
this.g.jb)),L("div",{id:b,class:"accordion-collapse collapse"+(this.g.show?"show":""),"aria-labelledby":a,"data-bs-parent":c,ref:this.u},L("div",{class:"accordion-body"}," ",K(new $a({itens:this.children}))," ")))}}function sd(){return{ondisplay:()=>{},refresh:void 0}}
class td extends M.g{static get g(){return rd}constructor(){var a={id:"conf_acord",Fb:!1};super(a);this.id=a.id??ja();this.u=Ta(this);this.l=[];this.F=()=>{const b=this.u.g;b&&(!1!==this.g.Fb&&(b.id=this.id),aa(b,"shown.bs.collapse",async c=>{this.l.forEach(d=>{if(d.g.Z.ondisplay&&d.u.g===c.target)d.g.Z.ondisplay(!0)})}),aa(b,"hidden.bs.collapse",async c=>{this.l.forEach(d=>{if(d.g.Z.ondisplay&&d.u.g===c.target)d.g.Z.ondisplay(!1)})}))}}h(a){a=G(this,L("div",{className:"accordion",ref:this.u}),a);
this.l=[];const b=I(this.children);let c=b.length;for(let d=0;d<c;d++){const e=b[d];e instanceof rd?(this.l.push(e),e.id=`${this.id}.${d}`,e.l=this.id,G(this,b[d],a)):"string"===typeof e&&""===e.trim()||console.error(e,"no Accordion.Item")}return a}async i(a){a=G(this,L("div",{className:"accordion",ref:this.u}),a);this.l=[];const b=I(this.children);let c=b.length;for(let d=0;d<c;d++){const e=b[d];e instanceof rd?(this.l.push(e),e.id=`${this.id}.${d}`,e.l=this.id,await Ua(this,e,a)):"string"===typeof e&&
""===e.trim()||console.error(e,"no Accordion.Item")}return a}}class ud extends M.g{constructor(a){super(a)}}
class X extends M.g{static get g(){return ud}constructor(a){super(a)}h(a){if(!a)return null;a=new z(a);let b={...this.g,item:[]},c=I(this.children);c=Ma(c);c.forEach(e=>{if(e instanceof ud){let f={...e.g};e.children?.length&&(f.col=[],I(e.children).forEach(g=>{g instanceof ud&&f.col.push(g.g)}));b.item.push(f)}});const d=R(a,b);c.forEach((e,f)=>{if(!(e instanceof ud))if(e instanceof J)(e=e.h(d.t.D))&&Na(d.t.D,e,f);else if("string"===typeof e||"number"===typeof e)"number"===typeof e&&(e=String(e)),
e=document.createTextNode("number"===typeof e?String(e):e),-1===f?console.error("repositionChild inner form"):Na(d.t.D,e,f)});return d.t.D}async i(a){return this.h(a)}}class vd extends M.g{constructor(a){super(a)}h(a){var b;a?b=jb(new z(a),this.g).t.button:b=null;return b}async i(a){return this.h(a)}}class Y extends M.g{static get g(){return vd}constructor(a){super(a)}h(a){return a?ub(new z(a),this.g).t.button:null}async i(a){return this.h(a)}}
class wd extends M.g{constructor(a){super(a)}h(a){if(!a)return null;a=new z(a);console.log(this.g);return qb(a,this.g).t.table}async i(a){return this.h(a)}};async function xd(a,b){var c=await gd(a);if(!c)throw Error();a=[[]];for(var d of c)console.log(d.file,b),d.file===b&&(a=d.table??await d.Ga(),console.log(d));let e=a[0].map(g=>({text:g})),f=[];for(d=1;11>d;d++)c=a[d].map(g=>({text:`${g}`})),f.push({itens:c});xb({title:`TABELA ${b}`,N:g=>{F(D(g,"h1"),{_textContent:"EXIBINDO TABELA"});qb(g,{style:"white-space: nowrap;",head:{itens:e},rows:f})},class:"modal-xl modal-dialog-scrollable"})};async function yd(a,b){a=new zd(a,b);await Ad(a);return a}async function Ad(a){a.cache=await ed(a.v);a.o=await gd(a.v);a.u=a.o.map(b=>b.file);a.layout_table&&a.layout_table.sel&&!a.l.includes(a.layout_table.sel)&&(a.layout_table.sel="");await Bd(a)}async function Bd(a){console.log(a.cache);const b=bd(a.cache);a.j=[];for(let c of b)for(let d of a.o??[])d.file===c&&(d.table||(d.table=await d.Ga()),d.la||(d.la=d.table[0],a.B.push(...d.la.filter(e=>"ENCODED"!==e))));La(a.j)}
async function Cd(a){await Ad(a)}async function Dd(a,b){await Cd(a);if(!a.l.includes(b))throw Error(`${b} not in list`);a.layout_table.sel=b;b||(a.i=!1)}async function Ed(a){await Bd(a)}function Fd(a,b){a.g.includes(b)||a.g.push(b)}async function Gd(a,b){a.i=b;await a.h()}async function Hd(a,b){a=a.layout_table;b in a.itens&&delete a.itens[b]}async function Z(a){await fd(a.v,a.cache)}async function Id(a,b){let c=a.g;1>b||b>=c.length||([c[b-1],c[b]]=[c[b],c[b-1]],a.g=c,await a.h())}
async function Jd(a,b){let c=a.g;0>b||b-1>=c.length||([c[b],c[b+1]]=[c[b+1],c[b]],a.g=c,await a.h())}async function Kd(a,b){a.g.splice(b,1);await a.h()}function Ld(a){var b=void 0;void 0===b&&(b=a.layout_table.sel);if(!b)throw Error("nome n\u00e3o definido = prompt engine_config");return b}
async function Md(a){const b=Ld(a);!0===await yb(c=>({X:{text:"N\u00c3O",s:()=>c.resolve(!1)},title:"APAGAR",text:`Confirma apagar listagem "${b}" ?`,Y:{text:"SIM",color:P.ub,s:()=>c.resolve(!0)}}))&&(await Hd(a,b),a.layout_table.sel="",await Z(a),await a.h())}
async function Nd(a){const b=await yb(c=>{const d=[""];return{title:"INCLUS\u00c3O",N:e=>R(e,{item:[{label:{text:"NOVO NOME"},input:{G:Q.text,value:d}}]}),X:{text:"N\u00c3O",s:()=>c.resolve(!1)},Y:{text:"SIM",color:P.Sa,s:()=>c.resolve(d[0])}}});"string"===typeof b&&(a.layout_table.sel=b,a.layout_table.itens[b]={col:[],tab:[]},await Z(a),await a.h())}async function Od(a){Ld(a);await Z(a)}
async function Pd(a){const b=Ld(a),c=await yb(d=>{const e=[""];return{title:`SALVAR C\u00d3PIA'${b}'`,N:f=>R(f,{item:[{label:{text:"NOVO NOME"},input:{G:Q.text,value:e}}]}),Y:{text:"SIM",color:P.Sa,s:()=>d.resolve(e[0])},X:{text:"N\u00c3O",s:()=>d.resolve(void 0)}}});"string"===typeof c&&(a.layout_table.itens[c]=JSON.parse(JSON.stringify(a.layout_table.itens[b])),a.layout_table.sel=c,await Z(a),await a.h())}
async function Qd(a){const b=Ld(a),c=await yb(d=>{const e=[""];return{X:{text:"N\u00c3O",s:()=>d.resolve(!1)},title:"RENOMEAR",N:f=>R(f,{item:[{label:{text:"NOVO NOME"},input:{G:Q.text,value:e}}]}),Y:{text:"SIM",color:P.Sa,s:()=>d.resolve(e[0])}}});"string"===typeof c&&(a.layout_table.itens[c]=JSON.parse(JSON.stringify(a.layout_table.itens[b])),await Hd(a,b),a.layout_table.sel=c,await Z(a),await a.h())}
class zd{constructor(a,b){this.i=!1;this.u=[];this.v=a;this.h=b;this.j=this.o=null}get layout_table(){return this.cache.layout_table}get l(){return["",...Object.keys(this?.layout_table?.itens??{})]}get C(){return this.layout_table?.sel??""}get B(){return this.j??[]}get g(){return this.layout_table?.itens[this.layout_table.sel]?.col??[]}set g(a){this.layout_table.itens[this.layout_table.sel].col=a}};async function Rd(a,b){let c=[0],d=[""],e=[""],f=await yb(g=>{let h={Za:!1,title:"USER LOGIN",X:{text:"CANCEL",s:()=>g.kb.hide()},N:k=>{zb(k,{active:c,itens:[{text:"FAZER LOGIN",s:()=>{g.refresh()}},{text:"CRIAR CONTA",s:()=>{g.refresh()}}]});0===c[0]&&(R(k,{Ya:!0,item:[{label:{text:"USERNAME"},input:{G:Q.text,value:d,autocomplete:"current-user"}},{label:{text:"PASSWORD"},input:{G:Q.password,value:e,autocomplete:"current-password"}}]}),h.Y={text:"LOGIN",s:async()=>{let l=await Yc(a,d[0],e[0]);l?(g.kb.hide(),
b&&b(),await ad(a,l),b&&b(),g.resolve(d[0])):(e[0]="",g.refresh())}})}};return h});console.log("retorunou modal",f,a.i,a.j,a.o);return"string"===typeof f?{username:f}:void 0};function Sd(a){let b=a.W;!b&&a.id&&(b=document.getElementById(a.id));if(!b)throw Error("request_fullscreen with no el");b.requestFullscreen();const c=d=>{d=a.wb?a.wb(d):!1;document.fullscreenElement||d||(document.removeEventListener("fullscreenchange",c),a.gb&&a.gb())};document.addEventListener("fullscreenchange",c)};const Td=[0,1,2];
class Ud{constructor(a){this.g=a;this.h=kc;this.i=null}get name(){return this.g.name??""}set name(a){this.g.name=a.length?a:void 0}get placeholder(){if(void 0===this.g.point)return"";const a=this.h.g.g;return 0===this.g.source&&Pb.includes(this.g.point)||1===this.g.source&&Qb.includes(this.g.point)||3===this.g.source&&Sb.includes(this.g.point)||2===this.g.source&&Pb.includes(this.g.point)?a[this.g.point]:""}get source(){const a=this.h.h.i;return void 0!==this.g.source?a[this.g.source]??"":""}set source(a){const b=
this.h.h.C;this.name="";this.g.source=b[a]}get u(){const a=this.h.h.i;let b=[];Object.values(Ob).forEach(c=>{b.push({value:a[c],selected:c===this.g.source})});return b}get item(){if(this.g.extra)return this.g.extra;const a=this.h.g.g;return void 0!==this.g.point?a[this.g.point]??"":""}set item(a){this.name="";this.i&&this.i.includes(a)?(this.g.extra=a,this.g.point=void 0):(this.g.point=this.h.g.xb[a],this.g.extra=void 0)}get o(){const a=this.h.g.g;let b=[],c=[],d=[];0===this.g.source?c=Pb:1===this.g.source?
c=Qb:2===this.g.source?c=Rb:3===this.g.source?c=Sb:4===this.g.source&&(d=this.i??[]);c.forEach(e=>{b.push({value:a[e],selected:e===this.g.point})});d.forEach(e=>{b.push({value:e,selected:!1})});return b}get info(){const a=this.h.calc_info.i;return void 0!==this.g.calc_info?a[this.g.calc_info]??"":""}set info(a){this.g.calc_info=this.h.calc_info.M[a]}get j(){const a=this.h.calc_info.i;let b=[];if(Td.includes(this.g.source)){const c=Object.values(Vb),d=c.includes(this.g.calc_info)?this.g.calc_info:
0;c.forEach(e=>{b.push({value:a[e],selected:e===d})})}else 3===this.g.source&&b.push({value:a[0],selected:!0});return b}get ref(){if(3===this.g.source||6===this.g.calc_info){var a=this.h.i.i,b=this.g.ref;return void 0!==this.g.ref?a[b]??"":""}a=this.h.j.i;b=this.g.ref;return void 0!==this.g.ref?a[b]??"":""}set ref(a){this.g.ref=3===this.g.source||6===this.g.calc_info?this.h.i.Ca[a]:this.h.j.l[a]}get l(){let a=[];if(3===this.g.source||6===this.g.calc_info){const b=this.h.i.i;Object.values(Tb).forEach(c=>
a.push({value:b[c],selected:this.g.ref===c}))}else{const b=this.h.j.i;Object.values(Ub).forEach(c=>a.push({value:b[c],selected:this.g.ref===c}))}return a}get on(){return this.g.on??!0}set on(a){this.g.on=a}};async function Vd(a,b){const c=b.I.get("refresh"),d=b.I.get(zd);b=d.g;const e=b.length;b=[...b,{}];const f="VISIBLE NAME SOURCE ITEM INFO REF DEL".split(" ").map(l=>({text:l})),g=l=>{l=new Ud(d.g[l]??{});l.i=d.B;return l},h=[];for(let l=0;l<b.length;l++){var k=g(l);k={refresh:c,K:d,H:l,col:k,Da:e,cols:b,oa:g};h.push({itens:[{L:Wd(k)},{L:Xd(k)},{L:Yd(k)},{L:Zd(k)},{L:$d(k)},{L:ae(k)},{L:be(k)}]})}Ab(a,{class:"table-hover",head:{itens:f},rows:h})}
function Wd(a){return async b=>{b=D(b,"div",c=>F(c,{class:"row"}));D(b,"div",c=>{F(c,{class:"col-4",lid:a.H});if(a.H<a.Da){const d=[a.col.on];wb(c,{input:{G:Q.La,value:d},ta:async()=>{a.oa(a.H).on=d[0];await a.refresh()}})}});ub(b,{color:P.Oa,class:"btn-sm p-0",grid:"col-4",N:c=>E(c,"svg",d=>{0<a.H&&a.H<a.Da||F(c,{class:"d-none"});F(d,{width:24,height:24,fill:"currentColor"});E(d,"use",e=>F(e,{href:"#aup"}))}),s:async()=>{Id(a.K,a.H)},lid:"up"});ub(b,{color:P.Oa,class:"btn-sm p-0",grid:"col-4",N:c=>
E(c,"svg",d=>{a.H<a.Da-1||F(c,{class:"d-none"});F(d,{width:24,height:24,fill:"currentColor"});E(d,"use",e=>F(e,{href:"#adwn"}))}),s:async()=>Jd(a.K,a.H),lid:"down"})}}function Xd(a){return async b=>{const c=[a.col.name];wb(b,{input:{G:Q.text,value:c,placeholder:a.col.placeholder,P:!1},ta:async()=>{a.oa(a.H).name=c[0];await a.refresh()},lid:"name"})}}
function Yd(a){return async b=>{vb(b,{options:["",...a.col.u.map(c=>c.value)],sel:a.col.source,P:!1,$:async c=>{let d=a.oa(a.H);d.source=c.qa;Fd(a.K,d.g);await a.refresh()},lid:"source"})}}function Zd(a){return async b=>{void 0!==a.col.source&&vb(b,{options:["",...a.col.o.map(c=>c.value)],sel:a.col.item,P:!1,$:async c=>{let d=a.oa(a.H);d.item=c.qa;Fd(a.K,d.g);await a.refresh()},lid:"item"})}}
function $d(a){return async b=>{const c=a.col.j;c.length&&vb(b,{options:["",...c.map(d=>d.value)],sel:a.col.info,P:!1,$:async d=>{let e=a.oa(a.H);e.info=d.qa;Fd(a.K,e.g);await a.refresh()},lid:"info"})}}function ae(a){return async b=>{const c=a.col.l;c.length&&vb(b,{options:["",...c.map(d=>d.value)],sel:a.col.ref,P:!1,$:async d=>{let e=a.oa(a.H);e.ref=d.qa;Fd(a.K,e.g);await a.refresh()},lid:"ref"})}}
function be(a){return async b=>{ub(b,{color:P.Oa,class:"btn-sm p-0",N:c=>E(c,"svg",d=>{a.H<a.Da||F(c,{class:"d-none"});F(d,{width:24,height:24,fill:"red"});E(d,"use",e=>F(e,{href:"#del"}))}),s:async()=>await Kd(a.K,a.H),lid:"down"})}};Ea.Pa=!0;async function ce(a){a.v||(a.v=await dd({Pc:a.refresh.bind(a),mb:async()=>"",lb:async()=>"",Qa:async()=>"",nb:async()=>{a.l.g&&(a.l.g.style.overflowY=a.v.status.ka?"auto":"",a.refresh())},Db:()=>{if(!a.l.g)throw Error();return a.l.g}}),a.pmr={I:new Map([[W,a.v]])},a.v.g.j||Yc(a.v.g).then(async b=>{b&&(await ad(a.v.g,b),a.refresh())}),a.B.va=["show","collapsed"],a.B.ma={class:"dropdown-menu show",keys:["style"]})}
class de extends M.g{constructor(){super();this.l=Ta(this)}async o(){await ce(this);qd();let a={backgroundColor:"white"};this.v.status.ka&&(a.overflowY="auto");return L("div",{style:a,ref:this.l,className:"container",id:"dmain"},K(new ab({scn:tb.vb,pmr:this.pmr})),L("br",null),L("div",{style:{backgroundColor:"white"}},K(new ee({v:this.v})),K(new fe({v:this.v})),K(new ge({v:this.v}))))}}
class ee extends M.g{constructor(a){super(a);this.pmr={I:new Map,va:["show"],ma:{class:"dropdown-menu show",keys:["style"]}};this.pmr.I.set(W,a.v);a.v.h.lb=async()=>{await this.refresh()}}async o(){const a=this.g.v;return K(new Y.g({color:"secondary",class:"ms-4",style:"position: sticky; left: 20px;z-index: 1050;",cb:"ESCOLHA A\u00c7\u00c3O",Fa:[{text:"CONFIG"+(a.status.Ja?" \u2714":""),s:()=>{a.status.Ja=!a.status.Ja;a.h.mb()}},{text:"TABLE"+(a.status.Ka?" \u2714":""),s:()=>{a.status.Ka=!a.status.Ka;
a.h.Qa()}},{Na:!0},{text:"FULLSCREEN"+(a.status.ka?" \u2714":""),s:async()=>{a.status.ka=!a.status.ka;a.status.ka?Sd({W:a.h.Db(),gb:async()=>{a.status.ka=!1;await a.h.nb()}}):document.exitFullscreen();await a.h.nb()}}]}))}}
class fe extends M.g{constructor(a){super(a);a.v.h.mb=async()=>{await this.g.v.h.lb();await this.refresh()};this.l=sd();this.l.ondisplay=async b=>{const c=this.g.v;b?c.g.i?this.l.refresh():await Rd(c.g,()=>{this.l.refresh();this.u.refresh();console.log("refresh cb0 cb1")}):this.l.refresh()};this.u=sd()}async o(){const a=this.g.v;if(!a.status.Ja)return L("div",null);const b=[a.g.username],c=[1,2];return L("div",null,L("div",{className:"container"},L("br",null," "),K(new td,()=>["  ",K(new td.g({jb:"COLUNAS VIS\u00cdVIES",
Z:this.l}),()=>[K(new he({v:a}))]),K(new td.g({jb:"BANCO DE DADOS",Z:this.u}),()=>[b[0]=a.g.username,K(new X({class:"row"}),()=>[K(new X.g({label:{text:"USERNAME"},grid:"col-md-4 ml-auto",input:{G:"text",value:b}})),L("div",{className:"col-md-2 d-flex align-items-end"},K(new Y({color:"primary",text:a.g.i?"DESCONECTAR":"CONECTAR",s:async()=>{a.g.i?await Xc(a.g):await Rd(a.g,()=>{this.u.refresh();this.l.refresh()});this.u.refresh();this.l.refresh()}})))]),L("button",{onClick:()=>{c[1]++;this.u.refresh();
console.log(c[1])}}," SOMAR ",c[1].toString())])])),L("br",null),L("br",null),L("br",null))}}
function ie(a,b,c){return K(new M.h,()=>[K(new X({class:"row mb-4"}),()=>[K(new X.g({label:{text:b.i.tb},class:"col-md-6",input:{select:{options:a.l,$:async d=>{await Dd(a,d.qa);d.qa&&await Z(a);c()},sel:a.C}}})),L("div",{class:"col-md-6 mt-3 d-flex align-items-end col-auto"},a.i?K(new M.h,()=>[K(new Y.g({text:"EDITAR",color:"primary",class:"me-3",ra:[{text:"SALVAR",s:async()=>{await Od(a);b.h.Qa()}}],Fa:[{text:"SALVAR COMO",s:async()=>await Pd(a)},{text:"RENOMEAR",s:async()=>await Qd(a)},{Na:!0},
{text:"FECHAR",s:async()=>{Cd(a);Gd(a,!1)}}]})),K(new Y({text:"NOVO",color:"secondary",class:"me-1",s:()=>{Nd(a)}})),K(new Y({text:"APAGAR",color:"danger",s:()=>{Md(a)}}))]):K(new Y({text:"EDITAR",color:"success",s:()=>{Gd(a,!0)},lid:"tg"})))]),a.i?L("div",{class:"mb-3"},a.u.map(d=>{const e=bd(a.cache),f=[e.includes(d)];return K(new X({class:"row ms-2"}),()=>[K(new X.g({grid:"col-md-1",lid:d,input:{G:Q.La,value:f},label:{text:d},ta:async()=>{La(e);{const g=e.indexOf(d);-1===g?e.splice(e.length,0,
d):e.splice(g,1)}await Ed(a);c()}})),L("div",{class:"col-md-1"},K(new Y({text:"VIEW",s:()=>(console.log(1),xd(b,d))})))])})):null])}async function je(a){const b=a.g.v;b.g.i?!a.K&&b.g.o&&(a.K=await yd(b,()=>a.refresh()),a.pmr={I:new Map([[W,a.g.v],[zd,a.K],["refresh",()=>a.refresh()]])}):delete a.K}
class he extends M.g{constructor(a){super(a);this.n=[1,2];this.pmr={I:new Map([[W,a.v]])}}async o(){await je(this);const a=this.g.v;return a.g.i?a.g.o?L("div",null,ie(this.K,this.g.v,()=>this.refresh()),this.K.i?K(new M.h,()=>[L("svg",{style:{display:"none"}},L("symbol",{viewBox:"0 0 16 16",id:"aup"},L("path",{d:"M8 12a.5.5 0 0 1-.5-.5V4.707l-3.146 3.147a.5.5 0 1 1-.708-.708l4-4a.5.5 0 0 1 .708 0l4 4a.5.5 0 1 1-.708.708L8.5 4.707V11.5a.5.5 0 0 1-.5.5z"})),L("symbol",{viewBox:"0 0 16 16",id:"adwn"},
L("path",{d:"M8 4a.5.5 0 0 1 .5.5v6.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 11.293V4.5A.5.5 0 0 1 8 4z"})),L("symbol",{viewBox:"0 0 16 16",id:"del"},L("path",{d:"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"}))),K(new bb({acn:Vd,pmr:this.pmr}))]):null,L("button",{onClick:()=>{this.n[0]++;this.refresh()}},
" SOMAR ",this.n[0])):L("h3",null,"AGUARDANDO CARREGAR"):L("h3",null,"DESCONECTADO")}}async function ke(a){a.view=await hd(a.g.v,()=>a.refresh());a.view.M=200}
class ge extends M.g{constructor(a){super(a);this.pmr={I:new Map([[W,a.v]])};a.v.h.Qa=async()=>{await ke(this);await this.refresh()}}async o(){if(!this.g.v.status.Ka)return L("div",null);this.view||await ke(this);const a=this.view.U,b=[],c=[];this.view.F.forEach(d=>b.push({text:d}));b[0].width=220;b[0].pb=!0;b[1].width=150;for(let d of a){const e={itens:[]};d.forEach(f=>e.itens.push({text:f}));c.push(e)}return L("div",null,K(new Y({text:"REFRESH",s:()=>this.refresh()})),K(new wd({class:"table-striped  mt-5",
style:"text-align: center; vertical-align: middle;",Ea:d=>this.view.Ea(d),Ma:"ts1",head:{itens:b,class:"bg-light sticky-top"},rows:c})))}};document.addEventListener("DOMContentLoaded",async function(){try{Ea.Pa=!0;const a=new de,b=document.getElementById("dmain");await cb(a,b)}catch(a){console.log(a)}});}).call(this);
