(function(){class p{constructor(a){this.g=a}get D(){return this.g}get h(){return this.g}get input(){return this.g}get select(){return this.g}get button(){return this.g}get style(){return this.g}get fa(){return this.g}get table(){return this.g}get pb(){return this.g}get a(){return this.g}get label(){return this.g}get i(){return this.g}};function aa(a,b,c,d,e){let f=a.h.get(b);f||(f=[],a.h.set(b,f));if(e){if(!ba.has(d)){a=d.toString();b=0;for(e=0;e<a.length;e++)b=(b<<5)-b+a.charCodeAt(e),b|=0;ba.set(d,b)}a=ba.get(d)}else a=void 0;f.push({event:c,A:d,hash:a})}
class ca{constructor(){this.h=new WeakMap;this.o=(a,b,c)=>{aa(this,a,b,c,!0)};this.g=null;this.l=[document.body];this.j=[]}get i(){return!!this.g}set i(a){a!==!!this.g&&(a?(this.g=new MutationObserver(b=>{b.forEach(c=>{this.j.forEach(d=>d(c))})}),this.l.forEach(b=>this.g.observe(b,{childList:!0,subtree:!0}))):(this.g.disconnect(),this.g=null))}}var ba=new WeakMap,t=new ca;const da={[6]:1,[5]:1,[7]:1,[1]:10,[4]:1,[3]:1,[2]:10,[8]:1,[9]:1,[10]:-100.11,[11]:-100.33,[12]:0,[13]:2,[14]:8,[15]:0};function ea(){const a=new Uint8Array([...atob("aHR0cHM6Ly8=")].map(b=>b.charCodeAt(0)));return(new TextDecoder("utf-8")).decode(a)}function u(a){a=(new TextEncoder("utf-8")).encode(a);return btoa(String.fromCharCode(...a))}let fa=0,ha=0;function ia(){var a=Date.now();a===ha?fa++:(fa=0,ha=a);a=1E3*a+fa;let b="";do b="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"[a%62]+b,a=Math.floor(a/62);while(0<a);return b};function ja(a,b){a=document.createElement(a);if(b.V)for(let [c,d]of Object.entries(b.V))c.startsWith("_")||a.setAttribute(c.replace("_","-"),d);b.parent&&b.parent.appendChild(a);b.A&&b.A(a);return a};function ka(a){function b(f){if(d.currentNode.childNodes.length!==f.h.length)return d.firstChild(),new la(d.currentNode,f);if(d.nextSibling())return new la(d.currentNode,f.parent);d.parentNode();if(d.currentNode&&f.parent)return f.parent}function c(f){f.h=f.h.filter(g=>{let h=g.node instanceof Text?0<g.node.textContent.trim().length:!0;h||f.node.removeChild(g.node);return h});f.h.forEach(g=>c(g))}let d=document.createTreeWalker(a,NodeFilter.SHOW_ALL),e=a=new la(a);for(;e=b(e),void 0!==e;);c(a);return a}
function ma(a){let b=[];var c=[];if(a.node instanceof HTMLElement||a.node instanceof SVGElement){a=a.node.attributes;for(c=0;c<a.length;c++)b.push(a[c]);c=b.reduce((d,e)=>{d.push({key:e.localName,value:e.value});return d},[])}return c}function na(a,b){for(let c=0;c<a.V.length;c++)if(b===a.V[c].key)return a.V[c].value}function oa(a,b){return b?a.V.reduce((c,d)=>c||d.key===b,!1):a.node instanceof HTMLElement?!0:!1}
class la{constructor(a,b){b&&(this.parent=b);this.node=a;this.h=[];b&&b.h.push(this);this.o=null;this.V=ma(this);this.j=[];a instanceof HTMLElement||a instanceof SVGElement?(this.g=a,this.i=this.g.localName,a instanceof HTMLInputElement?(this.j.push({key:"value",value:a.value}),this.j.push({key:"checked",value:a.checked})):a instanceof HTMLSelectElement&&this.j.push({key:"value",value:a.value})):a instanceof Text?(this.i="-Text",this.o=a.textContent):a instanceof ShadowRoot?this.i="div":a instanceof
Comment?this.i="!--":(this.i=a.constructor.name,console.log("TYPE",a,this.i))}get id(){return na(this,"id")??""}get lid(){return na(this,"lid")??""}toString(a=0){const b="    ".repeat(a);let c=`${b}<${this.i}>\n`;this.h.forEach(d=>{c+=`${d.toString(a+1)}`});return c+=`${b}</${this.i}>\n`}};const pa=new WeakMap;function qa(a,b,c){b=b.trim().split(/\s+/);const d=e=>!c.includes(e);a=a.trim().split(/\s+/).filter(d);b=b.filter(d);a=new Set(a);b=new Set(b);if(a.size!==b.size)return!1;for(const e of a)if(!b.has(e))return!1;return!0}
var ra=(a,b,c,d)=>{let e=[];const f=[];c.V.forEach(l=>{oa(b,l.key)||e.push(l.key)});let g=!1,h=[];if(d.ca){const l=(na(c,"class")??"").trim().split(/\s+/);d.ca.class.trim().split(/\s+/).every(k=>l.includes(k))&&(g=!0,h=d.ca.keys)}g&&(e=e.filter(l=>!h.includes(l)));b.V.forEach(l=>{const k=na(c,l.key);g&&h.includes(l.key)||("class"===l.key?qa(l.value,k??"",d.ya??[])||f.push(l):k!==l.value&&f.push(l))});e.length&&a.g.push({step:6,N:e.length,A:()=>e.forEach(l=>c.g.removeAttribute(l))});f.length&&a.g.push({step:5,
N:f.length,A:()=>f.forEach(l=>c.g.setAttribute(l.key,l.value))})};
function sa(a,b,c,d){b.i!==c.i&&(a.status=1);if(1!==a.status){ra(a,b,c,d);var e=b.j.reduce((k,m)=>{var n;a:{for(n=0;n<c.j.length;n++)if(m.key===c.j[n].key){n=c.j[n].value;break a}n=void 0}n!==m.value&&k.push(m);return k},[]);e.length&&a.g.push({step:7,N:e.length,A:()=>e.forEach(k=>{c.node instanceof HTMLInputElement&&("value"===k.key&&(c.node.value=k.value),"checked"===k.key&&(c.node.checked=k.value));c.node instanceof HTMLSelectElement&&"value"===k.key&&(c.node.value=k.value)})});b.o!==c.o&&a.g.push({step:4,
N:1,A:()=>{c.node.textContent=b.o}});var f=t.h.get(b.node)??[],g=t.h.get(c.node)??[],h=[],l=[];g.forEach((k,m)=>{let n=!0;f.forEach(q=>{k.event===q.event&&(void 0!==k.hash||void 0!==q.hash?k.hash===q.hash&&(n=!1):k.A===q.A&&(n=!1))});n&&h.push(m)});f.forEach((k,m)=>{let n=!0;g.forEach(q=>{q.event===k.event&&(void 0!==q.hash||void 0!==k.hash?q.hash===k.hash&&(n=!1):q.A===k.A&&(n=!1))});n&&l.push(m)});h.length&&a.g.push({step:9,N:h.length,A:()=>{h.forEach(k=>c.node.removeEventListener(g[k].event,g[k].A));
h.sort((k,m)=>k<m?1:m<k?-1:0).forEach(k=>g.splice(k,1));t.h.set(c.node,g)}});l.length&&a.g.push({step:8,N:l.length,A:()=>{l.forEach(k=>{c.node.addEventListener(f[k].event,f[k].A);g.push({event:f[k].event,A:f[k].A,hash:f[k].hash});t.h.set(c.node,g)})}})}}function ta(a,b,c,d){let e=ua.get(b.g);if(e){var f=ua.get(c.g);f?a.g.push({step:13,N:1,A:()=>{v(e,f,d)}}):a.g.push({step:14,N:1,A:()=>{f=c.g.attachShadow({mode:e.mode});ua.set(c.g,f);v(e,f,d)}})}}
function va(a,b,c,d){let e=b.h.map(()=>!1),f=c.h.map(()=>!1),g=[],h=[];b.h.forEach((m,n)=>{c.h.forEach((q,r)=>{e[n]||f[r]||(q=new wa(m,q,d),1!==q.status&&(4===q.status||0===q.h?(e[n]=!0,f[r]=!0,g.push({R:n,za:r,da:r}),4===q.status?a.o++:a.j++,a.i.push(q)):h.push({Na:n,Ea:r,fa:q,dc:q.h,selected:!1})))})});0<h.length&&(h=h.sort((m,n)=>m.fa.h<n.fa.h?-1:m.fa.h===n.fa.h?0:1),h.forEach(m=>{e[m.Na]||f[m.Ea]||(e[m.Na]=!0,f[m.Ea]=!0,m.selected=!0,g.push({R:m.Na,za:m.Ea,da:m.Ea}),a.i.push(m.fa))}));let l=f.reduce((m,
n,q)=>n?m:[...m,q],[]);l.length&&(a.g.push({step:2,N:l.length,A:()=>l.forEach(m=>{c.node.removeChild(c.h[m].node)})}),l.forEach(m=>{g=g.map(n=>m>n.za?n:{R:n.R,za:n.za,da:n.da-1})}));let k=e.reduce((m,n,q)=>n?m:[...m,q],[]);k.length&&(a.g.push({step:1,N:k.length,A:()=>k.forEach(m=>{m=b.h[m].node;c.node.appendChild(m);t.i||xa(m)})}),k.forEach(m=>g.push({R:m,za:Number.NaN,da:g.length})));if(g.reduce((m,n)=>m||n.da!==n.R,!1)){let m=g.sort((n,q)=>n.R<q.R?-1:n.R===q.R?0:1).map(n=>n.da);a.g.push({step:3,
N:1,A:()=>{for(let n=0;n<m.length;n++)if(n!=m[n]){let q=m[n];if(c.node instanceof HTMLElement||c.node instanceof SVGElement){let r=c.node.childNodes[n],w=c.node.childNodes[q];m.splice(n,1,n);m=m.map(B=>B+(B>=n&&B<q?1:0));c.node.insertBefore(w,r)}}}})}}function ya(a){if(1===a.status)return 0;let b=0;a.g.forEach(c=>b+=da[c.step]*c.N);b+=da[10]*a.j;b+=da[11]*a.o;a.i.forEach(c=>b+=c.h);return b}
class wa{constructor(a,b,c){this.g=[];this.status=2;this.i=[];this.h=Number.NaN;this.o=this.j=0;this.g.push({step:15,A:()=>{const d=a.g,e=b.g;d&&e&&pa.set(d,e)},N:1});if(!0!==c.va){if(a.id)if(a.id===b.id){if(this.status=4,pa.set(a.g,b.g),(c.fc??[]).includes(a.id))return}else{this.status=1;return}else if(a.lid)if(a.lid===b.lid)this.status=4,pa.set(a.g,b.g);else{this.status=1;return}else if(b.id||b.lid){this.status=1;return}sa(this,a,b,c);if(1===this.status)return}ta(this,a,b,{...c,va:!0});1!==this.status&&
(va(this,a,b,{...c,va:!1}),this.h=ya(this))}update(){this.i.forEach(a=>{a.update()});this.g.forEach(a=>{try{a.A()}catch(b){console.error(a.step,b)}})}}function xa(a){let b=za.get(a);b&&(b(a),za.delete(a));a.childNodes.forEach(xa)}function v(a,b,c){let d="string"!==typeof a?a:ja("div",{A:f=>f.innerHTML=a});b instanceof ShadowRoot&&d instanceof HTMLElement&&d.attributes.length&&(d=ja("div",{A:f=>f.appendChild(d)}));let e=ka(d);b=ka(b);(new wa(e,b,c)).update()};async function Aa(a,b){a=new y(document.createElement(a));b&&await b(a);return a}function z(a,b,c){a=document.createElement(a);c&&c.appendChild(a);c=new y(a);b&&b(c);return c}async function Ba(a,b){let c=await Aa(b&&"tagName"in b?b.tagName.toLocaleLowerCase():"div");c.e.innerHTML=a;b.appendChild(c.root);return c}async function Ca(a,b,c){Aa("div",async d=>{await b(d,c);v(d.root,a,c??{})})}const Da={set La(a){t.i=a;t.j=[b=>{b.addedNodes&&b.addedNodes.forEach(c=>xa(c))}]},get lc(){return t.i}};
function C(a,b,c){let d=[];c(e=>d.push(e));a.data.push({ob:b,rules:d.join("")})}function Ea(a,b){ja("style",{A:c=>{b.e.appendChild(c);c.innerText=a.data.map(d=>`${d.ob} { ${d.rules} }`).join(" ")}})}class Fa{constructor(){this.data=[]}add(a,b){this.data.push({ob:a,rules:b})}}
function Ga(a){return new Proxy(a,{get:(b,c)=>"addEventListener"===c?(d,e,f)=>{t.o(b,d,e);return b.addEventListener(d,e,f)}:"function"===typeof b[c]?b[c].bind(b):b[c],set:(b,c,d)=>{"string"===typeof c&&c.toLowerCase().startsWith("on")?(c=c.substring(2),t.o(b,c,d),b.addEventListener(c,d)):b[c]=d;return!0}})}function D(a,b,c){return z(b,c,a.g)}function E(a,b,c){a=a.g;b=document.createElementNS("http://www.w3.org/2000/svg",b);a&&a.appendChild(b);b=new y(b);c&&c(b);return b}
function F(a,b){const c=a.g;for(let [d,e]of Object.entries(b))d.startsWith("_")?("_textContent"===d&&(c.textContent=e),"_innerHTML"===d&&(c.innerHTML=e)):c.setAttribute(d.replaceAll("_","-"),e);return a}async function Ha(a,b){return Ba(b,a.g)}function Ia(a,b){let c=new Fa;b(c);Ea(c,a)}class y{constructor(a){this.g=a;this.h=null}get e(){this.i||(this.i=Ga(this.g));return this.i}get t(){this.h||(this.h=new p(this.g));return this.h}get root(){return this.g}M(a){za.set(this.g,a);return this}}
var ua=new WeakMap,za=new WeakMap;const Ja={Pb:0,Ib:1,POINTS:2,Lb:3,Jb:4};var Ka=[0,1,2,3,4,5,6,7,8,9],La=[15,16,17,18,19,20],Ma=[10,11,12,13,21,22],Na=[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012];const Oa={Ob:0,EQUAL:1,Tb:2,Sb:3,Qb:4},Pa={Nb:0,Mb:1,Rb:2,Ub:3,Vb:4,Wb:5,Kb:6};function Qa(a,b){for(let c of a)if(b===`${c.etype}.${c.name}`)return c;return null}
const Ra={[1]:"Nome de usu\u00e1rio n\u00e3o pode conter espa\u00e7os",[2]:"Email inv\u00e1lido",[3]:"Usu\u00e1rio j\u00e1 existe",[4]:"C\u00f3digo de valida\u00e7\u00e3o inv\u00e1lido ou expirado",[5]:"N\u00famero m\u00e1ximo de tentativas de senha excedido. Tente novamente mais tarde",[6]:"Senha incorreta",[7]:"Usu\u00e1rio n\u00e3o encontrado",[8]:"Formato do request",[9]:"Item n\u00e3o encontrado",[10]:"Par\u00e2metro inv\u00e1lido",[11]:"Id repetido em UserData",[12]:"Id n\u00e3o achado UserData",
[13]:"Erro nos arquivos do usu\u00e1rio",[101]:"Usu\u00e1rio n\u00e3o autenticado",[102]:"Download incompleto",[103]:"erro na requsi\u00e7\u00e3o / servidor"};function Sa(a){const b=new Map;a.forEach(c=>{const d=`${c.name}-${c.etype}`,e=b.get(d);(!e||new Date(c.update)>new Date(e.update))&&b.set(d,c)});return Array.from(b.values())};class Ta{async U(){}get I(){}get ia(){}async ja(){}get l(){}get pa(){}async qa(){}get h(){}set h(a){}B(){}async sa(){}async ta(){}async ra(){}async S(){}async T(){}async j(){}async ka(){}async la(){}async na(){}async oa(){}async ma(){}};class G{async i(){}async j(){}};async function Ua(){return new Promise(a=>setTimeout(a,400))}function Va(a){for(let b=0;b<a.length;b++)for(let c=b+1;c<a.length;c++)a[b]===a[c]&&(a.splice(c,1),c--)}function Wa(a){if(!Array.isArray(a))return a;const b=[];a.forEach(c=>{Array.isArray(c)?b.push(...Wa(c)):b.push(c)});return b}function Xa(a,b,c){const d=a.children;c>=d.length?a.appendChild(b):a.insertBefore(b,d[c])};const Ya=new WeakMap,Za=new WeakMap;function $a(a){if(!a)return null;if(document.body.contains(a))return a;for(;a;){let b=pa.get(a);if(b&&document.body.contains(b))return b;if(b===a)break;a=b}return null}class ab{get h(){const a=this.g;return a?!(Za.get(a)??!1):!1}get g(){return $a(this.i)}}async function bb(a){a=a.j;let b=a.length;for(let c=0;c<b;c++){const d=a[c].I;d&&(await d(),a[c].C.forEach(e=>{(e=e.g)&&Za.set(e,!0)}))}a.length=0}function cb(a){let b=new ab;a.C.push(b);return b}
function H(a,b,c){if(!b)return null;if("string"===typeof b||"number"===typeof b)return c&&c.appendChild(document.createTextNode(String(b))),null;a.j?.push(b);b.j=a.j;a=b.h(c);Ya.set(b,{parent:c??null,W:a});return a}async function db(a,b,c){if(!b)return null;if("string"===typeof b||"number"===typeof b)return c&&c.appendChild(document.createTextNode(String(b))),null;a.j.push(b);b.j=a.j;a=await b.i(c);Ya.set(b,{parent:c??null,W:a});return a}
function eb(a,b){for(let [d,e]of Object.entries(a.g??{}))if(d=String(d).toLowerCase(),"classname"===d&&(d="class"),"style"===d){a=[];var c=e;for(let [f,g]of Object.entries(c))a.push(`${fb(f)}:${g}`);b.setAttribute(d,a.join(";"))}else d.startsWith("on")?(a=d.substring(2),c=e,b.addEventListener(a,c),aa(t,b,a,c,!1)):"ref"===d?e.i=b:b.setAttribute(String(d),String(e))}function gb(a,b){const c=I(a.children);let d=c.length;for(let e=0;e<d;e++)H(a,c[e],b)}
async function hb(a,b){const c=I(a.children);let d=c.length;for(let e=0;e<d;e++)await db(a,c[e],b)}
class J{constructor(a){this.g=a??{};this.children=[];this.B={};this.C=[]}async refresh(){const a=Ya.get(this);a&&(a.W=$a(a.W),a.parent=$a(a.parent));if(!a||!a.W)throw Error("no root to update");var b=a.parent?a.parent.cloneNode(!1):null;this.j=[];(b=await this.i(b??void 0))&&v(b,a.W,{va:!1,...this.B});await bb(this)}o(){return null}h(a){const b=this.o();if(b instanceof Promise)throw Error("async on render sync");return b?H(this,b,a):null}async i(a){const b=await this.o();return b?db(this,b,a):null}}
class ib extends J{h(a){if(!this.l)return null;const b=document.createElement(this.l);eb(this,b);a&&a.appendChild(b);gb(this,b);return b}async i(a){if(!this.l)return null;const b=document.createElement(this.l);eb(this,b);a&&a.appendChild(b);await hb(this,b);return b}}class jb extends J{h(a){a&&gb(this,a);return null}async i(a){a&&await hb(this,a);return null}}class kb extends jb{constructor(a){super(a);this.children=a.itens}}
class lb extends J{h(a){if(!a)throw Error("chain without parent");this.g.scn(new y(a),this.g.pmr);return null}async i(a){return this.h(a)}}class mb extends J{h(){throw Error("ChainAsync requires Async");}async i(a){if(!a)throw Error("chain without parent");await this.g.acn(new y(a),this.g.pmr);return null}}function fb(a){return a.replace(/[A-Z]/g,b=>`-${b.toLowerCase()}`)}function K(a,...b){a.children?b.length&&a.children.push(...b):a.children=b;return a}
function L(a,b,...c){b=new ib(b);b.l=a;c&&(b.children=Wa(c));return b}class M{static get g(){return J}static get h(){return jb}}function I(a){const b=a?.[0];return 1===(a?.length??0)&&"function"===typeof b?b():a??[]};async function nb(a,b){const c=b.cloneNode(!1);a.j=[];const d=await a.i(c);Ya.set(a,{parent:c,W:d});v(c,b,{va:!1});await bb(a)};function ob(a){const b=[];for(a=a.parentElement;a&&a!==document.documentElement;)a.classList&&a.classList.contains("dropdown-menu")&&b.unshift(a),a=a.parentElement;return b}var pb=a=>{const b=d=>d.classList.remove("show");let c=ob(a);c.length||(c=[a]);c.forEach(d=>d.classList.remove("show"));c.length&&c[0].querySelectorAll(".show").forEach(b)};
function qb(a,b,c){const d=(new p(b.target)).h,e=(new p(b.target.closest(".dropdown-menu"))).D;if(e){var f=Array.from(e.children??[]),g=f.indexOf(d.closest("li")),h=d.closest(".dropdown-submenu");f=f.indexOf(h);b.stopPropagation();0<=g?(a=a[g],a?.select&&(c.close=!1),a?.s&&a.s(c),c.close&&pb(e)):0<=f&&(c.close=!1,a[f]?.s&&a[f].s(c),h.classList.toggle("show"),c.close&&pb(d));c.close=!0}}
function N(a){if(Array.isArray(a)&&0!==a.length)return a=a.filter(b=>void 0!==b).map(b=>b.trim()).filter(b=>0<b.length),a=[...(new Set(a.join(" ").split(/\s+/).filter(b=>0<b.length)))],0<a.length?{class:a.join(" ")}:void 0};var O=(a,b,c)=>{let d=["btn"],e=null;b.grid&&(e=a=D(a,"div",f=>F(f,{class:b.grid})));b.color&&d.push(`btn-${b.color}`);b.class&&d.push(b.class.trim());a=D(a,"button");F(a,{type:"button",class:d.join(" ")});b.lid&&F(a,{lid:b.lid});b.text?F(a,{_textContent:b.text}):b.xa?F(a,{_innerHTML:b.xa}):b.L&&b.L(a);c||a.M(f=>{f.addEventListener("click",()=>{b.s&&b.s()})});return e?e:a},rb=(a,b)=>{a=O(a,b);F(a,{data_bs_toggle:"dropdown",data_bs_reference:"parent",data_bs_auto_close:b.Va});a.e.classList.add("dropdown-toggle");
return a},tb=(a,b)=>sb(a,()=>b),sb=(a,b)=>{const c={close:!1,refresh:async()=>{}},d=[],e=g=>{d[0]=b();let h=d[0];F(g,{class:`btn-group ${h.class??""}`,role:"group"});h.lid&&F(g,{lid:h.lid});h.style&&F(g,{style:h.style});h.ua?.forEach(l=>O(g,{color:h.color,...l},!0));if(h.Ca||h.eb){const l=rb(g,{color:h.color,text:h.eb,Va:h.Va});h.ua&&l.e.classList.add("px-1");D(g,"ul",k=>{F(k,{class:"dropdown-menu"});h.Ca?.forEach(m=>{ub(k,m,c)})})}},f=D(a,"div");f.M(()=>{c.refresh=async()=>{await Ca(f.root,async g=>
{e(g)},{ya:["show"],ca:{class:"dropdown-menu show",keys:["style"]}})};f.root.addEventListener("click",async g=>{var h=(new p(g.target)).h;h=Array.from(f.t.D.children).indexOf(h);const l=d[0];0<=h&&h<l?.ua?.length&&l.ua[h].s&&l?.ua[h].s();qb(l?.Ca??[],g,c)});f.root.addEventListener("show.bs.dropdown",async()=>{pb(f.t.D)})});e(f);return f},ub=(a,b,c)=>{b||={Ia:!0};let d=[];b.class&&d.push(b.class);a=D(a,"li");if(b.Ia)d.push("dropdown-divider");else if(b.K)b.K(a,{}),(b.default??!0)&&d.push("dropdown-item");
else if(b.xa)a.e.innerHTML=b.xa,(b.default??!0)&&d.push("dropdown-item");else if(b.text)F(a,{_textContent:b.text}),(b.default??!0)&&d.push("dropdown-item");else if(b.select)b.select.refresh=c.refresh,vb(a,b.select);else if(b.Aa){d.push("dropdown-submenu");ub(a,b.Aa.label,c);let e=D(a,"ul");F(e,{class:"dropdown-menu"});b.Aa.itens.forEach(f=>ub(e,f,c));e.M(()=>{e.root.addEventListener("click",async f=>qb(b.Aa.itens??[],f,c))})}F(a,{class:d.join(" ")});b.lid&&F(a,{lid:b.lid});return a},vb=(a,b)=>{const c=
["form-select",b.class];"boolean"===typeof b.P&&c.push(b.P?"form-select-lg":"form-select-sm");const d=D(a,"select");F(d,{...N(c)});b.lid&&F(d,{lid:b.lid});b.options?.forEach(e=>{D(d,"option").e.innerHTML=e});b.ix?d.t.select.selectedIndex=b.ix:b.sel&&(a=b.options.indexOf(b.sel),0<=a&&(d.t.select.selectedIndex=a));b.$&&d.M(e=>{e.addEventListener("change",()=>{b.$({ga:d.t.select.value,yb:d.t.select.selectedIndex,refresh:b.refresh})})});return d},wb=(a,b,c)=>{const d=[b.class,b.grid],e="checkbox"===b?.input?.G;
e&&c?d.push("form-check-inline"):c&&!b.grid&&d.push("col-auto");const f=D(a,"div");b.lid&&F(f,{lid:b.lid});if(b.label&&!e){const g=[b.label.grid?"col-form-label":"form-label"];"boolean"===typeof b.label.P&&g.push(b.input.P?"form-control-lg":"form-control-sm");D(f,"label",h=>{F(h,{_textContent:b.label.text,...N([b.label.class,b.label.grid,...g])});b.label.Hb&&console.log(b.label.Hb)})}if(b.input){const g=[b.input.class];"boolean"===typeof b.input.P&&g.push(b.input.P?"form-control-lg":"form-control-sm");
const h=[];let l=(()=>{const k=b.input.grid?D(f,"div",m=>{b.input.grid&&F(m,{class:b.input.grid})}):f;if("textarea"===b.input.G)return g.push("form-control"),b.input.value&&h.push(m=>F(m,{_textContent:b.input.value[0]})),D(k,"textarea",m=>{b.input.Fb&&F(m,{rows:b.input.Fb})});if(b.input.G)return e?(g.push("form-check-input"),d.includes("form-check")||d.push("form-check")):g.push("form-control"),b.input.value&&(e&&b.input.value[0]?h.push(m=>F(m,{checked:void 0})):h.push(m=>F(m,{value:b.input.value[0]}))),
D(k,"input",m=>F(m,{type:b.input.G}));if(b.input.select)return vb(k,b.input.select);throw Error("type form-item ??");})();b.input.mc&&g.push("form-control-plaintext");b.input.autocomplete&&F(l,{autocomplete:b.input.autocomplete});F(l,{...N(g)});h.forEach(k=>k(l));b.input.placeholder&&F(l,{placeholder:b.input.placeholder});b.input.readonly&&F(l,{readonly:void 0});b.input.value&&l.M(k=>{k.addEventListener("change",()=>{e?b.input.value[0]=l.t.input.checked:"textarea"===b.input.G?b.input.value[0]=l.t.pb.value:
b.input.G&&(b.input.value[0]=l.t.input.value)})})}if(b.label&&e){const g=b.label.grid?"col-form-check-label":"form-check-label";if(b.label.grid)throw Error("Existe ??");D(f,"label",h=>{F(h,{_textContent:b.label.text,...N([g,b.label.class,b.label.grid])})})}b.col&&(F(f,{...N(["row",...d])}),b.col.forEach(g=>wb(f,g,!0)));b.D&&f.t.D.appendChild(b.D);b.rb&&b.rb(f,{});b.text&&F(D(f,"div"),{_textContent:b.text,class:"form-text"});b.small&&F(D(f,"small"),{_textContent:b.small});b.wa&&f.M(()=>{f.t.D.addEventListener("change",
()=>b.wa())});F(f,{...N(d)});return f},xb=(a,b)=>{const c=z("div");F(c,{class:"modal fade",tabindex:-1,role:"dialog"});D(c,"div",d=>{F(d,{...N(["modal-dialog",a.class])});D(d,"div",e=>{F(e,{class:"modal-content"});D(e,"div",f=>{F(f,{class:a.title?"modal-header":"col-auto d-flex justify-content-end"});a.title&&D(f,"h5",g=>g.e.textContent=a.title);D(f,"button",g=>{F(g,{class:"btn-close",data_bs_dismiss:"modal"});b?.resolve&&g.M(()=>{g.e.addEventListener("click",()=>b.resolve(void 0))})})});D(e,"div",
f=>{F(f,{class:"modal-body"});a.xa?f.e.innerHTML=a.xa:a.text?f.e.innerHTML=a.text:a.L&&a.L(f)});(a.Y||a.X)&&D(e,"div",f=>{F(f,{class:"modal-footer"});if(a.Y){let g=O(f,{color:"primary",...a.Y});(a.Za??!0)&&F(g,{data_bs_dismiss:"modal"})}a.X&&(f=O(f,{color:"secondary",...a.X}),(a.Za??!0)&&F(f,{data_bs_dismiss:"modal"}))})})});return c.t.D},yb=(a,b)=>{let c;document.fullscreenElement&&(document.fullscreenElement.append(a),c=z("div").t.D,c.className="modal-backdrop fade show",document.fullscreenElement.append(c));
let d=bootstrap.Modal.getOrCreateInstance(a,{});a.addEventListener("hidden.bs.modal",()=>{c&&c.remove();a.remove();b&&b()});return d};
function zb(a,b){const c=D(a,"ul",d=>F(d,{class:"pagination"}));b.itens.forEach((d,e)=>D(c,"li",f=>{const g=["page-item"];(d.active||(b.active??[]).includes(e))&&g.push("active");F(f,{...N(g)});F(D(f,"a"),{class:"page-link",href:"#",_textContent:d.text??""})}));c.M(()=>{c.root.addEventListener("click",d=>{d=(new p(d.target.closest("li"))).h;d=Array.from(c.t.i.children).indexOf(d);b.active&&(b.active.length=0,b.active.push(d));b.itens.at(d)?.s&&b.itens.at(d).s()})})}function Ab(a,b){Bb(a,()=>b)}
function Bb(a,b){const c=[];var d=async()=>{};const e=f=>{const g=b();c[0]=g;const h=[],l=[],k=[];let m=0;g.head.itens.forEach((n,q)=>{n.Eb&&l.push(q);n.width&&(h[q]=n.width)});(l||h)&&Ia(f,n=>{let q="table";g.bb&&(q=("#"===g.bb[0]?"":"#")+g.bb+" "+q);g.ab&&(q+="."+g.ab);l.forEach((r,w)=>{let B=h[r]??150;const x=k.length+1;C(n,`${q} th:nth-child(${x}), ${q} td:nth-child(${x})`,A=>{A("position: sticky;");A(`left: ${m}px;`);A("z-index: 1010;");A(`width: ${B}px;\n`)});w===l.length-1&&C(n,`${q} th:nth-child(${x})::after, ${q} td:nth-child(${x})::after`,
A=>{A("content: '';");A("position: absolute;");A("top: 0; right: 0px; height: 100%; width: 2px;");A("background-color: #dee2e6;")});m+=B;k.push(r)});C(n,`${q} thead th`,r=>{r("background-color: inherit;");r("user-select: none;")});g.head.itens.forEach((r,w)=>{if(!l.includes(w)){let B=h[w]??150;r=k.length+1;C(n,`${q} th:nth-child(${r}), ${q} td:nth-child(${r})`,x=>{x(`width: ${B}px;`)});k.push(w)}});C(n,q,r=>{r("table-layout: fixed;")})});f=D(f,"table");F(f,{...N(["table",g.class,g.ab])});g.style&&
F(f,{style:g.style});D(f,"thead",n=>{g.head?.class&&F(n,{class:g.head.class});g.head?.style&&F(n,{style:g.head?.style});let q=g.head?.itens??[];k.length&&(q=k.map(r=>q[r]));q.forEach(r=>{D(n,"th",w=>{F(w,{scope:"col"});r.style&&F(w,{style:r.style});r.text&&F(w,{_textContent:r.text});r.K&&r.K(w,g.zb??{})})})});D(f,"tbody",n=>{g.rows?.forEach((q,r)=>{D(n,"tr",w=>{F(w,{lid:r});q.class&&F(w,{class:q.class});let B=q?.itens??[];k.length&&(B=k.map(x=>B[x]));B.forEach(x=>{let A=D(w,"td");if(x.Eb||x.width)throw Error("width / tick definir no head");
x.text&&F(A,{_textContent:x.text});x.K&&x.K(A,g.zb??{});x.style&&F(A,{style:x.style})})})})})};e(a);d=async()=>Ca(a.root,async f=>e(f),{});a.M(()=>{function f(h,l,k){var m=h.closest("td,th");const n=h.closest("tr,thead");h=Array.from(n.closest("tbody")?.children??[]).indexOf(n);m=Array.from(n.children).indexOf(m);const q=c[0];if(q.Ha){const r={refresh:d,x:l,y:k,Cb:h,col:m};Cb(()=>q.Ha(r))}}const g=a.t.D.querySelector("table");g&&(g.oncontextmenu=h=>{h.preventDefault();h.stopPropagation();return f((new p(h.target)).h,
h.pageX,h.pageY)},g.ontouchstart=h=>{const l=h.touches[0],k=l.clientX+window.scrollX,m=l.clientY+window.scrollY,n=setTimeout(()=>{f((new p(h.target)).h,k,m)},500);g.ontouchend=()=>clearTimeout(n);g.ontouchmove=()=>clearTimeout(n)})})};var Db={ub:a=>{Ia(a,b=>{C(b,".dropdown-menu .dropdown-submenu",c=>{c("position: relative;")});C(b,".dropdown-menu .dropdown-submenu > .dropdown-menu",c=>{c("display: none;");c("position: absolute;");c("left: 100%;");c("top: 0;");c("margin-top: -1px;")});C(b,".dropdown-menu .dropdown-submenu:hover > .dropdown-menu,.dropdown-menu .dropdown-submenu.show > .dropdown-menu",c=>{c("display: block;")})})},ec:(a,b)=>{Ia(a,c=>{C(c,`.${b.name} .dropdown-item:hover,`+`.${b.name} .dropdown-item:focus`,d=>{b.qb&&
d(`background-color: ${b.qb};`);b.color&&d(`color: ${b.color};`)})})}},P={nc:"primary",rc:"secondary",Oa:"success",tb:"danger",tc:"warning",info:"info",Ka:"light",ac:"dark",link:"link"},Q={button:"button",Ga:"checkbox",color:"color",bc:"date",cc:"datetime-local",email:"email",file:"file",hidden:"hidden",image:"image",month:"month",kc:"number",password:"password",oc:"radio",pc:"range",reset:"reset",search:"search",submit:"submit",sc:"tel",text:"text",time:"time",url:"url",uc:"week",pb:"textarea"};
function Eb(a,b){return O(a,b)}function Fb(a,b){vb(a,b)}function Gb(a,b){wb(a,b,!1)}
function Cb(a){function b(h){if(!g.contains(h.target)||"mousedown"===h.type&&0!=h.button)g.remove(),document.removeEventListener("mousedown",b)}const c=z("div"),d={close:!0,refresh:async()=>{}},e=[],f=h=>{F(h,{class:"dropdown-menu show"});e[0]=a();const l=e[0];if(l){l.itens.forEach(m=>{ub(h,m,d)});var k=h.t.D;k.style.left=`${l.x}px`;k.style.top=`${l.y}px`;k.style.zIndex=1020}};d.refresh=async()=>Ca(c.root,async h=>f(h),{});f(c);if(e[0]){var g=c.t.D;g.addEventListener("click",async h=>{const l=e[0];
l&&qb(l.itens,h,d)});document.fullscreenElement?document.fullscreenElement.appendChild(g):document.body.appendChild(g);e[0]&&!e[0].Yb&&document.addEventListener("mousedown",b)}}function R(a,b){let c;if(b.Ya)c=D(a,"form");else if(!b.Ya||b.class)c=D(a,"div");b.class&&F(c,{class:b.class});const d=(b.class??"").split(" ").includes("row");b.item.forEach(e=>wb(c,e,d));return c}async function Hb(a){Da.La=!0;const b=xb(a);return new Promise(c=>{yb(b,()=>c(a.resolve?a.resolve():void 0)).show()})}
async function S(a){const b=z("div");F(b,{class:"modal fade",tabindex:-1,role:"dialog"});D(b,"div",d=>{F(d,{class:"modal-dialog"});D(d,"div",e=>{F(e,{class:"modal-content"})})});let c=[void 0];return new Promise((d,e)=>{const f=yb(b.t.D,()=>d(c[0]?c[0]():void 0)),g={lb:f,resolve:d,reject:e,root:b.t.D,refresh:()=>{var h=a(g);c[0]=h.resolve;h=xb(h,g);v(h,b.t.D,{va:!1,ya:["show"],ca:{class:"modal",keys:["style"]}})}};g.refresh();f.show()})}function Ib(a,b){zb(a,b)}function Jb(a,b){Ab(a,b)};function Kb(a,b){a.B=b(1);a.u=b(2);a.C=b(3);a.I=b(4);a.O=b(5);a.S=b(6);a.T=b(7);a.U=b(8);a.ha=b(9);a.ia=b(10);a.ja=b(11);a.ka=b(12)}
class Lb{constructor(){this.$a="SUN";this.ta="MOON";this.sa="MERCURY";this.ib="VENUS";this.pa="MARS";this.oa="JUPITER";this.Xa="SATURN";this.gb="URANUS";this.Ra="NEPTUNE";this.Ta="PLUTO";this.o="CHIRON";this.Qa="PHOLUS";this.j="CERES";this.Sa="PALLAS";this.na="JUNO ";this.jb="VESTA";this.ra="MEAN_NODE";this.fb="TRUE_NODE";this.qa="MEAN DARK MOON";this.cb="TRUE DARK MOON";this.l="EARTH";this.la="INTP_APOG";this.ma="INTP_PERG";this.ka=this.ja=this.ia=this.ha=this.U=this.T=this.S=this.O=this.I=this.C=
this.u=this.B="";Kb(this,a=>`H${String(a).padStart(2,"0")}`);this.h=this.i=null}get g(){if(!this.i){const a=this.i={};a[0]=this.$a;a[1]=this.ta;a[2]=this.sa;a[3]=this.ib;a[4]=this.pa;a[5]=this.oa;a[6]=this.Xa;a[7]=this.gb;a[8]=this.Ra;a[9]=this.Ta;a[10]=this.ra;a[11]=this.fb;a[12]=this.qa;a[13]=this.cb;a[14]=this.l;a[21]=this.la;a[22]=this.ma;a[15]=this.o;a[16]=this.Qa;a[17]=this.j;a[18]=this.Sa;a[19]=this.na;a[20]=this.jb;a[1001]=this.B;a[1002]=this.u;a[1003]=this.C;a[1004]=this.I;a[1005]=this.O;
a[1006]=this.S;a[1007]=this.T;a[1008]=this.U;a[1009]=this.ha;a[1010]=this.ia;a[1011]=this.ja;a[1012]=this.ka}return this.i}get xb(){this.h||(this.h={},Object.entries(this.g).forEach(([a,b])=>{this.h[b]=Number(a)}));return this.h}}
class Mb{constructor(){this.o="PLACIDUS";this.j="EQUAL";this.u="WHOLE_SIGN";this.B="TROPICAL";this.l="SIDERAL";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[0]=this.o;a[1]=this.j;a[2]=this.u;a[3]=this.B;a[4]=this.l}return this.h}get C(){this.g||(this.g={},Object.entries(this.i).forEach(([a,b])=>{this.g[b]=Number(a)}));return this.g}}
class Nb{constructor(){this.B="LONG";this.l="LAT";this.o="SPEED";this.u="X";this.C="Y";this.I="Z";this.j="HOUSE";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[0]=this.B;a[1]=this.l;a[2]=this.o;a[3]=this.u;a[4]=this.C;a[5]=this.I;a[6]=this.j}return this.h}get O(){this.g||(this.g={},Object.entries(this.i).forEach(([a,b])=>{this.g[b]=Number(a)}));return this.g}}
class Ob{constructor(){this.B="PLANETS";this.j="ASTEROIDS";this.u="POINTS";this.l="HOUSE CUSPS";this.o="EXTRA";this.g=this.h=null}get i(){if(!this.h){const a=this.h={};a[0]=this.B;a[1]=this.j;a[2]=this.u;a[3]=this.l;a[4]=this.o}return this.h}get C(){this.g||(this.g={},Object.entries(this.i).forEach(([a,b])=>{this.g[b]=Number(a)}));return this.g}}class Pb{constructor(){this.g=new Lb;this.calc_info=new Nb;this.h=new Ob;this.i=new Mb}}const Qb=new Pb;
(function(a){a.$a="SOL";a.ta="LUA";a.sa="MERC\u00daRIO";a.ib="VENUS";a.pa="MARTE";a.oa="JUP\u00cdTER";a.Xa="SATURNO";a.gb="URANO";a.Ra="NETUNO";a.Ta="PLUT\u00c3O";a.o="QU\u00cdRON";a.Qa="FOLO";a.j="CERES";a.Sa="PALAS";a.na="JUNO ";a.jb="VESTA";a.ra="NODO NORTE MED.";a.fb="NODO NORTE VERD.";a.qa="LUA NEGRA MED.";a.cb="LUA NEGRA VERD.";a.l="TERRA";a.la="APOGEU INTERP.";a.ma="PERIGEU INTERP.";Kb(a,b=>`CASA ${String(b).padStart(2,"0")}`)})(Qb.g);var Rb=Qb.calc_info;Rb.o="VELOC";Rb.j="CASA";var T=Qb.h;
T.B="PLANETAS";T.j="ASTER\u00d3IDES";T.u="PONTOS";T.l="C\u00daSPIDE DAS CASAS";T.o="EXTRA";async function Sb(a){return await a.g.g?.h.j()??[]}async function Tb(a,b){await a.g.j(b)}async function Ub(a){return await a.g.i()}class Vb{constructor(a){this.g=a}}class Wb extends Vb{};const U=new Map,Xb=U.delete.bind(U),Yb=new BroadcastChannel("ib");Yb.onmessage=a=>{a=a.data;1===a.m&&(U.get(a.n)?.close(),Xb(a.n))};U.delete=a=>{Yb.postMessage({m:1,n:a});return Xb(a)};
async function Zb(a,b){var c=U.get(a);if(c&&!b)return c;let d;b&&(c=await Zb(a),d=c.version+1,c.close());return new Promise((e,f)=>{let g=!1,h=!1;setTimeout(()=>{g||f(Error(`indexedDB timeout: bloqueado: ${h?"essa aba":"outra"} (${a})`))},100);const l=indexedDB.open(a,d);l.onsuccess=k=>{g=!0;k=k.target.result;U.set(a,k);e(k)};l.onerror=k=>{g=!0;f(k.target.error)};l.onupgradeneeded=k=>{g=!0;k=k.target.result;b&&b(k)};l.onblocked=()=>{h=!0}})}
async function $b(a,b){let c=await Zb(a);c.objectStoreNames.contains(b)||(c.close(),c=await Zb(a,d=>{d.createObjectStore(b)}));return c}async function ac(a){return await $b(a.g,a.h)}async function bc(a,b,c,...d){const e=a.i.transaction([a.h],b).objectStore(a.h)[c](...d);return new Promise((f,g)=>{e.onsuccess=h=>{f(h.target.result)};e.onerror=h=>{g(h.target.error)}})}async function cc(a,b){await bc(a,"readwrite","delete",b)}
async function dc(a){a.i.close();U.delete(a.g);return new Promise((b,c)=>{const d=indexedDB.deleteDatabase(a.g);d.onsuccess=()=>{b()};d.onerror=e=>{c(e.target.error)}})}class ec{constructor(a){const [b,c]=a.split(".");this.g=b;this.h=c}get i(){return U.get(this.g)}async get(a){return await bc(this,"readonly","get",a)}async set(a,b){await bc(this,"readwrite","put",b,a)}};async function fc(a,b={}){a=new Response(new Blob([a],{type:"application/wasm"}));return await WebAssembly.instantiateStreaming(a,b)}async function gc(a,b){a.g=await fc(b,{wasi_snapshot_preview1:a.h,js:a.h,env:a.h});a.M.forEach(c=>c())}async function hc(a){var b=await fetch("teste.wasm");b.ok&&(b=await b.arrayBuffer(),console.log(b.byteLength),console.log(b),await gc(a,b))}
class ic{constructor(){const a=this;this.M=[()=>a.i=a.g.instance.exports.memory,()=>a.o=a.g.instance.exports.malloc,()=>a.l=a.g.instance.exports.free];this.h={emscripten_resize_heap:b=>a.i.grow((b-a.i.buffer.byteLength+65535)/65536|0),fd_write:()=>{console.log("fd_write")},__syscall_fcntl64:()=>{console.log("__syscall_fcntl64")},__syscall_ioctl:()=>{console.log("__syscall_ioctl")},__syscall_openat:()=>{console.log("__syscall_openat")},_emscripten_memcpy_js:()=>{console.log("_emscripten_memcpy_js")},
environ_get:()=>{console.log("environ_get")},environ_sizes_get:()=>{console.log("environ_sizes_get")},fd_close:()=>{console.log("fd_close")},fd_read:()=>{console.log("fd_read")},fd_seek:()=>{console.log("fd_seek")}}}};class jc extends ic{};class kc extends jc{constructor(){super();const a=this;this.M.push(()=>a.g.instance.exports.somar,()=>a.g.instance.exports.jday,()=>this.j=a.g.instance.exports.planeta)}};function lc(a){new Lb;return a.map(b=>{const c={};c.name=b;"ENCODED"===b?c.chart_info=1:(c.extra=b,4===c.source);return c})};class mc{get C(){}Ha(){}}
async function nc(a){await ac(a.T);console.log(11);await hc(a.O);console.log(12);a.B=await Sb(a.I);a.o=await Ub(a.I);a.g=null;a.o&&a.o.sel&&(a.g=a.o.itens[a.o.sel],a.g.col=a.g.col.filter(b=>!1===b.on?!1:!0));a.j=[];a.l=[];if(a.g&&a.B)for(let b of a.g.tab){const c=a.g.tab.indexOf(b);for(let d of a.B)if(b===d.file){d.table||(d.table=await d.Ja());d.ba||(d.ba=lc(d.table[0]));const e=d.ba.map(f=>f.chart_info).indexOf(1);0<=e&&(d.vb=1,a.l[c]=[],d.table.forEach(f=>{{const n=f[e].match(/^(\d+)(\w)(\d{2})(\d{2})(\d+)([-+]\d+(\.\d*)?)([-+]\d+(\.\d*)?)([-+]\d+(\.\d*)?)/);if(n){f=
parseInt(n[1],10);var g=parseInt(n[3],10),h=parseInt(n[4],10),l=parseInt(n[5].substring(0,2),10),k=parseInt(n[5].substring(2,4),10);6==n[5]&&(k+=parseInt(n[5].substring(4,6),10)/60);var m="CJBRcjbr".indexOf(n[2]);f={year:f,month:g,day:h,hour:l,minute:k,Gb:parseFloat(n[6]),ic:parseFloat(n[8]),jc:parseFloat(n[10]),hc:m&1,Xb:m>>1&1,Ab:m>>2&1}}else f=null}a.l[c].push(f)}));a.j.push(d)}}a.j.forEach((b,c)=>b.table.forEach((d,e)=>{1===b.vb&&0===e||a.i.push([c,e])}));a.u=new Map;a.g.col.forEach((b,c)=>{if(b.extra){const d=
new Map;a.u.set(c,d);b=b.extra;for(c=0;c<a.j.length;c++){let e=a.j[c].ba.map(f=>f.name??"").indexOf(b);d.set(c,e)}}})}function oc(a,b,c){const [d,e]=[b[0],b[1]];b=a.u.get(c)?.get(d);if(void 0!==b)return a?.j[d]?.table[e][b];b=a.l[d][e];if(!b)return null;let f=a.g.col[c].point;var g;"number"===typeof f?g=a.O.j(b.year,b.month,b.day,f,b.hour+b.minute/60+b.Gb,0):g=`point:${a.g.col[c].point} ${b.Ab}`;return g}function pc(a,b,c){a.i.sort((d,e)=>c(oc(a,d,b),oc(a,e,b)))}
function qc(a,b){console.log("set field",b);console.log(a.h[b]);if(!a.h[b]){let c=new Set;a.i.forEach(e=>c.add(String(oc(a,e,b))));let d=[];[...c].sort().forEach(e=>d.push({item:e,on:!0}));console.log(b,d);a.h[b]=d}}function rc(a){a.i=[];a.j.forEach((b,c)=>b.table.forEach((d,e)=>{0<e&&a.i.push([c,e])}));a.h.forEach((b,c)=>{a.i=a.i.filter(d=>{d=oc(a,d,c);let e=!0;for(let f of b)if(f.item===d){e=f.on;break}return e})})}
class sc{constructor(a){this.I=a;this.j=this.g=this.o=this.B=null;this.U=50;this.S=new Pb;this.u=new Map;this.i=[];this.h=[];this.l=[];this.T=new ec("mandala.calcs");this.O=new kc}get C(){return this.g?.col.map(a=>{if(a.name)return a.name;if(a.extra)return a.extra;if(void 0!==a.point)return this.S.g.g[a.point]??""})??[]}Ha(a){if(void 0===a.col||-1!==a.Cb||void 0===a.x||void 0===a.y)return null;class b{constructor(){a.F||(a.F=new Map);void 0===a.F.get("col")&&a.F.set("col",a.col)}get col(){return a.F.get("col")}set col(f){a.F.set("col",
f)}}const c=new b,d=f=>(g,h)=>{let l=parseFloat(g),k=parseFloat(h);isNaN(l)||isNaN(k)||(g=l,h=k);g=g===h?0:g<h?-1:1;return f?g:-g};let e=this.h?.[c.col]?.map(f=>[f.on??!0]);return{x:a.x,y:a.y,itens:[{select:{options:this.C,sel:this.C[c.col],$:f=>{a.F.set("col",f.yb);f.refresh()}}},{Aa:{label:{text:"ORDENAR"},itens:[{text:"CRESCENTE",s:f=>{f.close=!1;pc(this,c.col,d(!0));a.refresh()}},{text:"DECRESCENTE",s:f=>{f.close=!1;pc(this,c.col,d(!1));a.refresh()}}]}},{Aa:{label:{text:"FILTRAR"},itens:[{text:"LISTAR",
s:f=>{f.close=!1;qc(this,c.col);f.refresh()}},{K:f=>{let g=0;this.h?.[c.col]?.forEach(l=>{l.on&&g++});let h=[];this.h?.[c.col]?.forEach((l,k)=>h.push({label:{text:l.item},input:{G:Q.Ga,value:e[k]},wa:()=>{e.forEach((m,n)=>{this.h[c.col][n].on=m[0]});rc(this);a.refresh()}}));f=D(f,"div");F(f,{class:"ms-3"});R(f,{item:h})},s:f=>{f.close=!1},default:!1}]}}]}}}async function tc(a){a=new sc(a);await nc(a);return a};async function uc(a,b){var c=b.F.get(G);c.g.h?(b.F.get(mc)||(c=await tc(new Wb(c)),c.U=500,b.F.set(mc,c)),b.F.get(mc),D(a,"div")):console.log("sem dados usu\u00e1rio")};async function vc(){return new Promise((a,b)=>{if("undefined"!==typeof JSZip)a();else{var c=document.createElement("script");c.src=ea()+"cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";c.onload=a;c.onerror=()=>b(Error("Falha ao carregar JSZip"));document.head.appendChild(c)}})}async function V(){await vc();const a=new JSZip;a.entries=()=>Object.entries(a.files).map(([b,c])=>{c.Ua=async()=>await c.async("string");return{filename:b,data:c}});return a}
async function wc(a){a=atob(a);var b=a.length;const c=new Uint8Array(b);for(let d=0;d<b;d++)c[d]=a.charCodeAt(d);a=c.buffer;b=await V();await b.loadAsync(a);return b}async function xc(a){const b=await V();b.file("_",a);return await b.generateAsync({type:"uint8array"})}async function yc(a){let b=await V();await b.loadAsync(a);return await b.files._.async("string")};class zc extends M.g{constructor(a){super(a);this.u=cb(this);this.B.ya=["show","collapsed","collapsing"];this.g.Z&&(this.g.Z.refresh=async b=>{void 0!==b&&(this.g.show=b);await this.refresh()})}o(){const a="h"+this.id,b="c"+this.id,c=this.l?"#"+this.l:"";return L("div",{class:"accordion-item"},L("h2",{class:"accordion-header",id:a},L("button",{class:"accordion-button"+(this.g.show?"":" collapsed"),type:"button","data-bs-toggle":"collapse","data-bs-target":"#"+b,"aria-expanded":this.g.show??!1,"aria-controls":b},
this.g.kb)),L("div",{id:b,class:"accordion-collapse collapse"+(this.g.show?"show":""),"aria-labelledby":a,"data-bs-parent":c,ref:this.u},L("div",{class:"accordion-body"}," ",K(new kb({itens:this.children}))," ")))}}function Ac(){return{ondisplay:()=>{},refresh:void 0}}
class Bc extends M.g{static get g(){return zc}constructor(){var a={id:"conf_acord",Db:!1};super(a);this.id=a.id??ia();this.u=cb(this);this.l=[];this.I=()=>{const b=this.u.g;b&&(!1!==this.g.Db&&(b.id=this.id),this.u.h&&(b.addEventListener("shown.bs.collapse",async c=>{this.l.forEach(d=>{if(d.g.Z.ondisplay&&d.u.g===c.target)d.g.Z.ondisplay(!0)})}),b.addEventListener("hidden.bs.collapse",async c=>{this.l.forEach(d=>{if(d.g.Z.ondisplay&&d.u.g===c.target)d.g.Z.ondisplay(!1)})})))}}h(a){a=H(this,L("div",
{className:"accordion",ref:this.u}),a);this.l=[];const b=I(this.children);let c=b.length;for(let d=0;d<c;d++){const e=b[d];e instanceof zc?(this.l.push(e),e.id=`${this.id}.${d}`,e.l=this.id,H(this,b[d],a)):"string"===typeof e&&""===e.trim()||console.error(e,"no Accordion.Item")}return a}async i(a){a=H(this,L("div",{className:"accordion",ref:this.u}),a);this.l=[];const b=I(this.children);let c=b.length;for(let d=0;d<c;d++){const e=b[d];e instanceof zc?(this.l.push(e),e.id=`${this.id}.${d}`,e.l=this.id,
await db(this,b[d],a)):"string"===typeof e&&""===e.trim()||console.error(e,"no Accordion.Item")}return a}}class Cc extends M.g{constructor(a){super(a)}}
class W extends M.g{static get g(){return Cc}constructor(a){super(a)}h(a){if(!a)return null;a=new y(a);let b={...this.g,item:[]},c=I(this.children);c=Wa(c);c.forEach(e=>{if(e instanceof Cc){let f={...e.g};e.children?.length&&(f.col=[],I(e.children).forEach(g=>{g instanceof Cc&&f.col.push(g.g)}));b.item.push(f)}});const d=R(a,b);c.forEach((e,f)=>{if(!(e instanceof Cc))if(e instanceof J)(e=e.h(d.t.D))&&Xa(d.t.D,e,f);else if("string"===typeof e||"number"===typeof e)"number"===typeof e&&(e=String(e)),
e=document.createTextNode("number"===typeof e?String(e):e),-1===f?console.error("repositionChild inner form"):Xa(d.t.D,e,f)});return d.t.D}async i(a){return this.h(a)}}class Dc extends M.g{constructor(a){super(a)}h(a){var b;a?b=tb(new y(a),this.g).t.button:b=null;return b}async i(a){return this.h(a)}}class X extends M.g{static get g(){return Dc}constructor(a){super(a)}h(a){return a?Eb(new y(a),this.g).t.button:null}async i(a){return this.h(a)}};const Ec=[0,1,2];
class Fc{constructor(a){this.g=a;this.h=Qb;this.i=null}get name(){return this.g.name??""}set name(a){this.g.name=a.length?a:void 0}get placeholder(){if(void 0===this.g.point)return"";const a=this.h.g.g;return 0===this.g.source&&Ka.includes(this.g.point)||1===this.g.source&&La.includes(this.g.point)||3===this.g.source&&Na.includes(this.g.point)||2===this.g.source&&Ka.includes(this.g.point)?a[this.g.point]:""}get source(){const a=this.h.h.i;return void 0!==this.g.source?a[this.g.source]??"":""}set source(a){const b=
this.h.h.C;this.name="";this.g.source=b[a]}get B(){const a=this.h.h.i;let b=[];Object.values(Ja).forEach(c=>{b.push({value:a[c],selected:c===this.g.source})});return b}get item(){if(this.g.extra)return this.g.extra;const a=this.h.g.g;return void 0!==this.g.point?a[this.g.point]??"":""}set item(a){this.name="";this.i&&this.i.includes(a)?(this.g.extra=a,this.g.point=void 0):(this.g.point=this.h.g.xb[a],this.g.extra=void 0)}get o(){const a=this.h.g.g;let b=[],c=[],d=[];0===this.g.source?c=Ka:1===this.g.source?
c=La:2===this.g.source?c=Ma:3===this.g.source?c=Na:4===this.g.source&&(d=this.i??[]);c.forEach(e=>{b.push({value:a[e],selected:e===this.g.point})});d.forEach(e=>{b.push({value:e,selected:!1})});return b}get info(){const a=this.h.calc_info.i;return void 0!==this.g.calc_info?a[this.g.calc_info]??"":""}set info(a){this.g.calc_info=this.h.calc_info.O[a]}get j(){const a=this.h.calc_info.i;let b=[];if(Ec.includes(this.g.source)){const c=Object.values(Pa),d=c.includes(this.g.calc_info)?this.g.calc_info:
0;c.forEach(e=>{b.push({value:a[e],selected:e===d})})}else 3===this.g.source&&b.push({value:a[0],selected:!0});return b}get ref(){const a=this.h.i.i;return void 0!==this.g.ref?a[this.g.ref]??"":""}set ref(a){this.g.ref=this.h.i.C[a]}get l(){const a=this.h.i.i;let b=[],c=[3,4],d=[],e=this.g.ref;3===this.g.source||6===this.g.calc_info?(Object.values(Oa).forEach(f=>{c.includes(f)||d.push(f)}),this.g.ref&&d.includes(this.g.ref)||(e=0)):Ec.includes(this.g.source)&&(c.forEach(f=>d.push(f)),this.g.ref&&
d.includes(this.g.ref)||(e=3));d.forEach(f=>{b.push({value:a[f],selected:f===e})});return b}get on(){return this.g.on??!0}set on(a){this.g.on=a}};async function Gc(a,b){const c=b.F.get("refresh"),d=b.F.get(Ta);b=d.h;const e=b.length;b=[...b,{}];const f="VISIBLE NAME SOURCE ITEM INFO REF DEL".split(" ").map(k=>({text:k})),g=k=>{k=new Fc(d.h[k]??{});k.i=d.pa;return k},h=[];for(let k=0;k<b.length;k++){var l=g(k);l={refresh:c,J:d,H:k,col:l,Ba:e,cols:b,ea:g};h.push({itens:[{K:Hc(l)},{K:Ic(l)},{K:Jc(l)},{K:Kc(l)},{K:Lc(l)},{K:Mc(l)},{K:Nc(l)}]})}Jb(a,{class:"table-hover",head:{itens:f},rows:h})}
function Hc(a){return async b=>{b=D(b,"div",c=>F(c,{class:"row"}));D(b,"div",c=>{F(c,{class:"col-4",lid:a.H});if(a.H<a.Ba){const d=[a.col.on];Gb(c,{input:{G:Q.Ga,value:d},wa:async()=>{a.ea(a.H).on=d[0];await a.refresh()}})}});Eb(b,{color:P.Ka,class:"btn-sm p-0",grid:"col-4",L:c=>E(c,"svg",d=>{0<a.H&&a.H<a.Ba||F(c,{class:"d-none"});F(d,{width:24,height:24,fill:"currentColor"});E(d,"use",e=>F(e,{href:"#aup"}))}),s:async()=>{a.J.sa(a.H)},lid:"up"});Eb(b,{color:P.Ka,class:"btn-sm p-0",grid:"col-4",L:c=>
E(c,"svg",d=>{a.H<a.Ba-1||F(c,{class:"d-none"});F(d,{width:24,height:24,fill:"currentColor"});E(d,"use",e=>F(e,{href:"#adwn"}))}),s:async()=>a.J.ta(a.H),lid:"down"})}}function Ic(a){return async b=>{const c=[a.col.name];Gb(b,{input:{G:Q.text,value:c,placeholder:a.col.placeholder,P:!1},wa:async()=>{a.ea(a.H).name=c[0];await a.refresh()},lid:"name"})}}
function Jc(a){return async b=>{Fb(b,{options:["",...a.col.B.map(c=>c.value)],sel:a.col.source,P:!1,$:async c=>{let d=a.ea(a.H);d.source=c.ga;a.J.B(d.g);await a.refresh()},lid:"source"})}}function Kc(a){return async b=>{void 0!==a.col.source&&Fb(b,{options:["",...a.col.o.map(c=>c.value)],sel:a.col.item,P:!1,$:async c=>{let d=a.ea(a.H);d.item=c.ga;a.J.B(d.g);await a.refresh()},lid:"item"})}}
function Lc(a){return async b=>{const c=a.col.j;c.length&&Fb(b,{options:["",...c.map(d=>d.value)],sel:a.col.info,P:!1,$:async d=>{let e=a.ea(a.H);e.info=d.ga;a.J.B(e.g);await a.refresh()},lid:"info"})}}function Mc(a){return async b=>{const c=a.col.l;c.length&&Fb(b,{options:["",...c.map(d=>d.value)],sel:a.col.ref,P:!1,$:async d=>{let e=a.ea(a.H);e.ref=d.ga;a.J.B(e.g);await a.refresh()},lid:"ref"})}}
function Nc(a){return async b=>{Eb(b,{color:P.Ka,class:"btn-sm p-0",L:c=>E(c,"svg",d=>{a.H<a.Ba||F(c,{class:"d-none"});F(d,{width:24,height:24,fill:"red"});E(d,"use",e=>F(e,{href:"#del"}))}),s:async()=>await a.J.ra(a.H),lid:"down"})}};async function Oc(a,b){var c=await a.g.h?.j();if(!c)throw Error();a=[[]];for(var d of c)console.log(d.file,b),d.file===b&&(a=d.table??await d.Ja(),console.log(d));let e=a[0].map(g=>({text:g})),f=[];for(d=1;11>d;d++)c=a[d].map(g=>({text:`${g}`})),f.push({itens:c});Hb({title:`TABELA ${b}`,L:g=>{F(D(g,"h1"),{_textContent:"EXIBINDO TABELA"});Ab(g,{style:"white-space: nowrap;",head:{itens:e},rows:f})},class:"modal-xl modal-dialog-scrollable"})}
async function Pc(a){a=E(a,"svg");a.e.style.display="none";E(a,"symbol",b=>{F(b,{viewBox:"0 0 16 16",id:"aup"});E(b,"path",c=>F(c,{d:"M8 12a.5.5 0 0 1-.5-.5V4.707l-3.146 3.147a.5.5 0 1 1-.708-.708l4-4a.5.5 0 0 1 .708 0l4 4a.5.5 0 1 1-.708.708L8.5 4.707V11.5a.5.5 0 0 1-.5.5z"}))});E(a,"symbol",b=>{F(b,{viewBox:"0 0 16 16",id:"adwn"});E(b,"path",c=>F(c,{d:"M8 4a.5.5 0 0 1 .5.5v6.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 11.293V4.5A.5.5 0 0 1 8 4z"}))});
E(a,"symbol",b=>{F(b,{viewBox:"0 0 16 16",id:"del"});E(b,"path",c=>F(c,{d:"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"}))})};async function Qc(a){a.u=[];for(let b of a.l)for(let c of a.C??[])c.file===b&&(c.table||(c.table=await c.Ja()),c.ba||(c.ba=lc(c.table[0])),c.ba.forEach(d=>{d.extra&&a.u.push(d.extra)}));Va(a.u)}async function Rc(a){console.log("iniciando data layout table");a.g=await Ub(a.O);a.C||(a.C=await Sb(a.O),a.ha=a.C.map(b=>b.file));a.g&&a.g.sel&&!a.I.includes(a.g.sel)&&(a.g.sel="");await Qc(a)}
function Sc(a){var b=void 0;void 0===b&&(b=a.g.sel);if(!b)throw Error("nome n\u00e3o definido = prompt engine_config");return b}
class Tc{constructor(a,b){this.o=!1;this.ha=[];this.O=a;this.i=b;this.u=this.C=null}async U(){await Rc(this)}get I(){return["",...Object.keys(this?.g?.itens??{})]}get ia(){return this.g?.sel??""}async ja(a){await this.U();if(!this.I.includes(a))throw Error(`${a} not in list`);this.g.sel=a;a||(this.o=!1)}get l(){return this.g?.itens[this.g.sel]?.tab??[]}get pa(){return this.u??[]}async qa(){console.log("update sel table",void 0);await Qc(this)}get h(){return this.g?.itens[this.g.sel]?.col??[]}set h(a){this.g.itens[this.g.sel].col=
a}B(a){this.h.includes(a)||this.h.push(a)}async S(){this.o=!this.o;await this.i()}async T(a){const b=this.g;a in b.itens&&delete b.itens[a]}async j(){await Tb(this.O,this.g)}async sa(a){let b=this.h;1>a||a>=b.length||([b[a-1],b[a]]=[b[a],b[a-1]],this.h=b,await this.i())}async ta(a){let b=this.h;0>a||a-1>=b.length||([b[a],b[a+1]]=[b[a+1],b[a]],this.h=b,await this.i())}async ra(a){this.h.splice(a,1);await this.i()}async ka(){const a=Sc(this);!0===await S(b=>({X:{text:"N\u00c3O",s:()=>b.resolve(!1)},
title:"APAGAR",text:`Confirma apagar listagem "${a}" ?`,Y:{text:"SIM",color:P.tb,s:()=>b.resolve(!0)}}))&&(await this.T(a),this.g.sel="",await this.j(),await this.i())}async la(){const a=await S(b=>{const c=[""];return{title:"INCLUS\u00c3O",L:d=>R(d,{item:[{label:{text:"NOVO NOME"},input:{G:Q.text,value:c}}]}),X:{text:"N\u00c3O",s:()=>b.resolve(!1)},Y:{text:"SIM",color:P.Oa,s:()=>b.resolve(c[0])}}});"string"===typeof a&&(this.g.sel=a,this.g.itens[a]={col:[],tab:[]},await this.j(),await this.i())}async na(){Sc(this);
await this.j()}async oa(){const a=Sc(this),b=await S(c=>{const d=[""];return{title:`SALVAR C\u00d3PIA'${a}'`,L:e=>R(e,{item:[{label:{text:"NOVO NOME"},input:{G:Q.text,value:d}}]}),Y:{text:"SIM",color:P.Oa,s:()=>c.resolve(d[0])},X:{text:"N\u00c3O",s:()=>c.resolve(void 0)}}});"string"===typeof b&&(this.g.itens[b]=JSON.parse(JSON.stringify(this.g.itens[a])),this.g.sel=b,await this.j(),await this.i())}async ma(){console.log(10);const a=Sc(this),b=await S(c=>{const d=[""];return{X:{text:"N\u00c3O",s:()=>
c.resolve(!1)},title:"RENOMEAR",L:e=>R(e,{item:[{label:{text:"NOVO NOME"},input:{G:Q.text,value:d}}]}),Y:{text:"SIM",color:P.Oa,s:()=>c.resolve(d[0])}}});console.log(12);"string"===typeof b&&(this.g.itens[b]=JSON.parse(JSON.stringify(this.g.itens[a])),await this.T(a),this.g.sel=b,await this.j(),await this.i())}}async function Uc(a,b){a=new Tc(a,b);await Rc(a);return a};async function Vc(a,b){let c=[0],d=[""],e=[""],f=await S(g=>{let h={Za:!1,title:"USER LOGIN",X:{text:"CANCEL",s:()=>g.lb.hide()},L:l=>{Ib(l,{active:c,itens:[{text:"FAZER LOGIN",s:()=>{g.refresh()}},{text:"CRIAR CONTA",s:()=>{g.refresh()}}]});0===c[0]&&(R(l,{Ya:!0,item:[{label:{text:"USERNAME"},input:{G:Q.text,value:d,autocomplete:"current-user"}},{label:{text:"PASSWORD"},input:{G:Q.password,value:e,autocomplete:"current-password"}}]}),h.Y={text:"LOGIN",s:async()=>{let k=await Wc(a,d[0],e[0],b);k?
(g.lb.hide(),g.resolve(k)):(e[0]="",g.refresh())}})}};return h});return"string"===typeof f?{username:f}:void 0};async function Xc(a){return await (await fetch("https://script.google.com/macros/s/AKfycbz8kvZBqee545Q7d9yebhOuDfH7JYvLqaN_sZxSSK1Mi9Q23us-MvgSUsCkbNooyKy61A/exec",{method:"POST",headers:{"Content-Type":"text/plain"},body:a})).text()}
async function Yc(a){const b=await V();b.file("q",JSON.stringify(a));a=await b.generateAsync({type:"base64"});const c=await Xc(a);if(c.includes("<!DOCTYPE"))throw await Hb({title:"ERROR",L:d=>Ha(d,c)}),Error(102);a=JSON.parse(c);isNaN(Number(a.error))?a.error&&console.log(a.error):console.log(Ra[parseInt(a.error,0)]);return a}async function Zc(a){a=(await wc(a)).files.p;if(!a)throw Error();return await a.async("string")}
async function $c(a,b,c,d,e){a=await Yc({user:a,password:b,request:1,data:{name:c,byteSize:d,ichunk:e}});if(a.rdata){a=atob(a.rdata);b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=a.charCodeAt(c);a=b}else a=null;return a}async function ad(a,b){a=await Yc({user:a,password:b,request:0});b=a.error;b={error:!b||isNaN(parseInt(b,10))?void 0:parseInt(b,10)};if(!a.rdata)return b;b.Pa=await JSON.parse(await Zc(a.rdata));return b}
async function bd(a,b,c,d){async function e(r){for(;6>=g;){let w=await $c(a,b,c,f,r);if(w){m[r]=w;console.log(r,"processado",w.length,"ativos",h.length);return}g++}n=!0}var f=void 0;let g=0,h=[],l=0;f||=1E6;let k=Math.ceil(d/f),m=Array(k),n=!1;await async function(){for(;l<k;){5<=h.length&&await Promise.race(h);let r=e(l).catch(w=>console.error(w)).finally(()=>{h=h.filter(w=>w!==r)});h.push(r);await Ua();l++}await Promise.all(h)}();if(n)return console.log("erro"),null;d=m.reduce((r,w)=>r+w.length,
0);d=new Uint8Array(d);let q=0;for(let r=0;r<m.length;r++)d.set(m[r],q),q+=m[r].length;return d}async function cd(a,b,c,d,e,f){const g=Array(f.length);for(let h=0;h<f.length;h++)g[h]=String.fromCharCode(f[h]);a=await Yc({user:a,password:b,request:2,data:{name:c,mimetype:"application/zip",etype:e,update:d,t64array:btoa(g.join(""))}});return a.rdata?JSON.parse(a.rdata):null}async function dd(a,b,c){a=await Yc({user:a,password:b,request:3,data:c});return a.rdata?JSON.parse(a.rdata):null};async function Y(a){await ac(a.j);a=await a.j.get("z");if(!a)return[];a=await yc(a);return JSON.parse(a)}async function ed(a){a.g=await Y(a);"4"===a.g[2]&&(a.g[2]="1")}function fd(a){if(!a.i)throw Error(101);a.g[2]="5"}async function Z(a){let b=await xc(JSON.stringify(a.g));await a.j.set("z",b)}
async function gd(a,b,c){let d={};a.g=await Y(a);b&&b!==a.g[0]?(a.g[0]=b,a.g[1]="",a.g[2]="",await Z(a)):b||=a.g[0];c&&c!==a.g[1]?(a.g[1]="",a.g[2]="",await Z(a)):c||=a.g[1];b&&c&&(d=await ad(b,c),6===d.error?(a.g[2]="3",a.g[1]="",await Z(a)):7===d.error&&(a.g[2]="",a.g[0]="",a.g[1]="",await Z(a)));d.Pa&&!d.error&&(a.g[2]="4",console.log("login verified"),b!==a.g[0]||c!==a.g[1])&&(a.g[0]=b,a.g[1]=c,await Z(a));a.g[1]="";return d.Pa&&!d.error?d.Pa:null}
async function hd(a,b,c,d,e){if(!a.i)throw Error(101);a=await Y(a);return cd(a[0],a[1],b,c,d,e)}async function id(a,b){if(!a.i)throw Error(101);a=await Y(a);return dd(a[0],a[1],b)}async function jd(a,b,c){if(!a.i)throw Error(101);a=await Y(a);return bd(a[0],a[1],b,c)}async function kd(a){a.g=[];await dc(a.j)}
class ld{constructor(){this.g=[];this.j=new ec("mandala._")}get h(){return["1","4","5"].includes(this.g[2])}get i(){return["4","5"].includes(this.g[2])}get o(){return"5"===this.g[2]}get username(){return this.g[0]??""}};async function md(a,b,c){const d=`${a.etype}.${a.name}`,e=u(d);if(a=await jd(b,d,a.size))return await c.set(e,a),a;await cc(c,e);console.error(Ra[102]);return null}async function nd(a,b){a=u(`${a.etype}.${a.name}`);await cc(b,a)}async function od(a){await ac(a.g)}async function pd(a,b){b=await xc(JSON.stringify(b));await a.g.set("l",b)}async function qd(a){a=await a.g.get("l");if(!a)return null;a=await yc(a);return JSON.parse(a)}
async function rd(a,b){var c=(await qd(a))?.itens??[];let d=b.itens??[];d=Sa(d);let e=[],f=!1;var g=!1;let h=!1;for(let k of d){var l=`${k.etype}.${k.name}`;let m=Qa(c,l);l=u(l);l=await a.g.get(l);m&&l?m.update===k.update&&m.size===k.size&&m.deleted===k.deleted?e.push(m):new Date(m.update)>new Date(k.update)?(m.deleted?(g=await id(a.h,m.id))?e.push(g):h=!0:(g=await hd(a.h,m.name,m.update,m.etype,l))?e.push(g):h=!0,g=!0):new Date(m.update)<new Date(k.update)?(k.deleted?(await nd(k,a.g),e.push(k)):
await md(k,a.h,a.g)?e.push(k):h=!0,f=!0):m.size!==k.size&&(await md(k,a.h,a.g)?e.push(k):h=!0,f=!0):(await md(k,a.h,a.g)?e.push(k):h=!0,f=!0)}for(let k of c)c=`${k.etype}.${k.name}`,Qa(d,c)||(c=u(c),c=await a.g.get(c),(c=await hd(a.h,k.name,k.update,k.etype,c))?e.push(c):h=!0,g=!0);a.i?f||g?console.log(`update com atualiza\u00e7\u00e3o ${f?"local":""} ${g?"no servdior":""} `):console.log("update sem atualiza\u00e7\u00e3o"):console.log("sem fun\u00e7\u00e3o atualiza\u00e7\u00e3o");f&&a.i&&await a.i();
h?console.log("algo errado"):(b.itens=e,await pd(a,b))}
async function sd(a,b){if(!a.h.i)throw Error(Ra[101]);var c=await V();for(let [e,f]of Object.entries(b))c.file(e,f);b=await c.generateAsync({type:"uint8array"});c=u("1.menu_action");await a.g.set(c,b);c=await qd(a);let d=Qa(c.itens,"1.menu_action");d?c.itens=c.itens.filter(e=>"1.menu_action"!==`${e.etype}.${e.name}`):d={name:"menu_action",etype:1,id:"",size:0,update:""};d.size=b.byteLength;d.update=(new Date).toISOString();c.itens.push(d);pd(a,c)}
async function td(a){var b=u("1.menu_action");b=await a.g.get(b);if(!b)return null;a=await V();await a.loadAsync(b);b={};for(let c of a.entries())b[c.filename]=await c.data.Ua();return b}
class ud{constructor(a,b){if(!a.h)throw Error(Ra[101]);this.h=a;this.o=u(a.username);this.g=new ec("mandala."+this.o);this.i=b}async j(){const a=[];var b=await qd(this);if(!b)return a;const c=this;b=b.itens.map(async d=>{if(0===d.etype&&!d.deleted){var e=u(`${d.etype}.${d.name}`);if(e=await c.g.get(e)){var f=await V();await f.loadAsync(e);for(let g of f.entries())a.push({file:d.name,stream:g.filename,Ja:async function(){var h=await g.data.Ua();h=JSON.parse(h);return g.filename=h}})}}});await Promise.all(b);
return a}};async function Wc(a,b,c,d){const e=await gd(a.g,b,c);if(!a.g.h)return a.h=null,!1;a.h=new ud(a.g,a.j);await od(a.h);e?(async()=>{e&&await rd(a.h,e);await a.i(e);fd(a.g);d&&d()})():(a.h=null,await a.i(null));d&&d();return!!e}async function vd(a,b){await ed(a.g);a.g.h?(a.h=new ud(a.g,a.j),await od(a.h),await a.i(null),gd(a.g).then(async c=>{c?await rd(a.h,c):a.h=null;await a.i(c);c&&fd(a.g);b&&b()})):a.h=null}async function wd(a){await kd(a.g);a.h=null}
class xd{constructor(a,b){this.g=new ld;this.h=null;this.i=a;this.j=b}};const yd={$b:"PADR\u00c3O",Zb:"TRADICIONAL",sb:"LISTAGEM"};async function zd(a,b){a.g.h&&(b?await Ad(a):a.g.g.h&&await Ad(a))}async function Ad(a){const b=(await td(a.g.h))?.["tables.json"];a.cache=b?JSON.parse(b):{layout_table:{itens:{},sel:""}}}function Bd(a){if(!a.cache)throw Error(101);}async function Cd(a){Bd(a);const b={["tables.json"]:JSON.stringify(a.cache)};sd(a.g.h,b)}
class Dd{constructor(){this.g=new xd(async a=>await zd(this,a),async()=>{console.log("atualizado")});this.status={};this.cache=null;this.o=yd;this.h={}}async i(){Bd(this);return JSON.parse(JSON.stringify(this.cache.layout_table))}async j(a){Bd(this);this.cache.layout_table=a;await Cd(this)}};function Ed(a){let b=a.W;!b&&a.id&&(b=document.getElementById(a.id));if(!b)throw Error("request_fullscreen with no el");b.requestFullscreen();const c=d=>{d=a.wb?a.wb(d):!1;document.fullscreenElement||d||(document.removeEventListener("fullscreenchange",c),a.hb&&a.hb())};document.addEventListener("fullscreenchange",c)};Da.La=!0;
class Fd extends M.g{constructor(){super();this.u=!1;this.v=new Dd;this.pmr={F:new Map([[G,this.v]])};this.l=cb(this);const a=this.v.h;this.B.ya=["show","collapsed"];this.B.ca={class:"dropdown-menu show",keys:["style"]};a.qc=this.refresh.bind(this);a.mb=this.refresh.bind(this);a.Bb=()=>{if(!this.l.g)throw Error();return this.l.g};this.v.h.nb=async()=>{this.l.g&&(this.l.g.style.overflowY=this.v.status.aa?"auto":"",this.v.h.Da())}}async o(){this.u||(this.u=!0,await vd(this.v.g,()=>this.refresh()));let a=
{backgroundColor:"white"};this.v.status.aa&&(a.overflowY="auto");return L("div",{style:a,ref:this.l,className:"container",id:"dmain"},K(new lb({scn:Db.ub,pmr:this.pmr})),L("br",null),L("div",{style:{backgroundColor:"white"}},K(new Gd({v:this.v})),K(new Hd({v:this.v})),K(new Id({v:this.v}))))}}
class Gd extends M.g{constructor(a){super(a);this.pmr={F:new Map,ya:["show"],ca:{class:"dropdown-menu show",keys:["style"]}};this.pmr.F.set(G,a.v);a.v.h.Da=async()=>{await this.refresh()}}async o(){const a=this.g.v;return K(new X.g({color:"secondary",class:"ms-4",style:"position: sticky; left: 20px;z-index: 1050;",eb:"ESCOLHA A\u00c7\u00c3O",Ca:[{text:"TABLE"+(a.status.Wa?" \u2714":""),s:()=>{a.status.Wa=!a.status.Wa;a.h.Ma()}},{text:"CONFIG"+(a.status.Fa?" \u2714":""),s:()=>{a.status.Fa=!a.status.Fa;
a.h.mb()}},{Ia:!0},{text:"FULLSCREEN"+(a.status.aa?" \u2714":""),s:async()=>{a.status.aa=!a.status.aa;a.status.aa?Ed({W:a.h.Bb(),hb:async()=>{a.status.aa=!1;await a.h.nb()}}):document.exitFullscreen();await a.h.nb()}}]}))}}
class Hd extends M.g{constructor(a){super(a);a.v.h.mb=async()=>{await this.g.v.h.Da();await this.refresh()};this.l=Ac();this.l.ondisplay=async b=>{const c=this.g.v;b?c.g.g.h?this.l.refresh():await Vc(c.g,()=>{this.l.refresh();this.u.refresh()}):this.l.refresh()};this.u=Ac()}async o(){const a=this.g.v;if(!a.status.Fa)return L("div",null);const b=[a.g.g.username],c=[1,2];return L("div",null,L("div",{className:"container"},L("br",null," "),K(new Bc,()=>["  ",K(new Bc.g({kb:"COLUNAS VIS\u00cdVIES",Z:this.l}),
()=>[K(new Jd({v:a}))]),K(new Bc.g({kb:"BANCO DE DADOS",Z:this.u}),()=>[b[0]=a.g.g.username,K(new W({class:"row"}),()=>[K(new W.g({label:{text:"USERNAME"},grid:"col-md-4 ml-auto",input:{G:"text",value:b}})),L("div",{className:"col-md-2 d-flex align-items-end"},K(new X({color:"primary",text:a.g.g.h?"DESCONECTAR":"CONECTAR",s:async()=>{a.g.g.h?(b[0]="",await wd(a.g)):await Vc(a.g);console.log("db click",a.g.g.h);this.u.refresh();this.l.refresh()}})))]),L("button",{onClick:()=>{c[1]++;this.u.refresh();
console.log(c[1])}}," SOMAR ",c[1].toString())])])),L("br",null),L("br",null),L("br",null))}}
function Kd(a,b,c){return K(new M.h,()=>[K(new W({class:"row mb-4"}),()=>[K(new W.g({label:{text:b.o.sb},class:"col-md-6",input:{select:{options:a.I,$:async d=>{await a.ja(d.ga);d.ga&&await a.j();c()},sel:a.ia}}})),L("div",{class:"col-md-6 mt-3 d-flex align-items-end col-auto"},a.o?K(new M.h,()=>[K(new X.g({text:"EDITAR",color:"primary",class:"me-3",ua:[{text:"SALVAR",s:async()=>{await a.na();b.h.Ma()}}],Ca:[{text:"SALVAR COMO",s:async()=>await a.oa()},{text:"RENOMEAR",s:async()=>await a.ma()},{Ia:!0},
{text:"FECHAR",s:async()=>{a.U();a.S()}}]})),K(new X({text:"NOVO",color:"secondary",class:"me-1",s:()=>{a.la()}})),K(new X({text:"APAGAR",color:"danger",s:()=>{a.ka()}}))]):K(new X({text:"EDITAR",color:"success",s:()=>{a.S();console.log("ect")},lid:"tg"})))]),a.o?L("div",{class:"mb-3"},a.ha.map(d=>{const e=[a.l.includes(d)];return K(new W({class:"row ms-2"}),()=>[K(new W.g({grid:"col-md-1",lid:d,input:{G:Q.Ga,value:e},label:{text:d},wa:async()=>{Va(a.l);{var f=a.l;const g=f.indexOf(d);-1===g?f.splice(f.length,
0,d):f.splice(g,1)}await a.qa();c()}})),L("div",{class:"col-md-1"},K(new X({text:"VIEW",s:()=>(console.log(1),Oc(b,d))})))])})):null])}async function Ld(a){const b=a.g.v;b.g.g.h?a.J||(a.J=await Uc(new Vb(b),()=>a.refresh()),a.pmr={F:new Map([[G,a.g.v],[Ta,a.J],["refresh",()=>a.refresh()]])}):delete a.J}
class Jd extends M.g{constructor(a){super(a);this.n=[1,2];this.pmr={F:new Map([[G,a.v]])};a.v.h.Ma=async()=>{await this.g.v.h.Da();await this.refresh()}}async o(){await Ld(this);const a=this.g.v;return a.g.g.h?a.g.g.o?L("div",null,Kd(this.J,this.g.v,()=>this.refresh()),this.J.o?K(new M.h,()=>[K(new mb({acn:Pc,pmr:this.pmr})),K(new mb({acn:Gc,pmr:this.pmr}))]):null,L("button",{onClick:()=>{this.n[0]++;this.refresh()}}," SOMAR ",this.n[0])):L("h3",null,"AGUARDANDO CARREGAR"):L("h3",null,"DESCONECTADO")}}
class Id extends M.g{constructor(a){super(a);this.pmr={F:new Map([[G,a.v]])};a.v.h.Ma=async()=>{await this.g.v.h.Da();await this.refresh()}}async o(){return L("div",null,K(new mb({acn:uc,pmr:this.pmr})))}};document.addEventListener("DOMContentLoaded",async function(){try{Da.La=!0;const a=new Fd,b=document.getElementById("dmain");await nb(a,b)}catch(a){console.log(a)}});}).call(this);
