(function(){const h=new Map,m=h.delete.bind(h),p=new BroadcastChannel("ib");p.onmessage=a=>{a=a.data;1===a.m&&(h.get(a.n)?.close(),m(a.n))};h.delete=a=>{p.postMessage({m:1,n:a});return m(a)};
async function q(a,b){var c=h.get(a);if(c&&!b)return c;let d;b&&(c=await q(a),d=c.version+1,c.close());return new Promise((e,f)=>{let g=!1,l=!1;setTimeout(()=>{g||f(Error(`indexedDB timeout: bloqueado: ${l?"essa aba":"outra"} (${a})`))},100);const k=indexedDB.open(a,d);k.onsuccess=n=>{g=!0;n=n.target.result;h.set(a,n);e(n)};k.onerror=n=>{g=!0;f(n.target.error)};k.onupgradeneeded=n=>{g=!0;n=n.target.result;b&&b(n)};k.onblocked=()=>{l=!0}})}
async function aa(a,b){let c=await q(a);c.objectStoreNames.contains(b)||(c.close(),c=await q(a,d=>{d.createObjectStore(b)}));return c}async function ba(a,b){let c=await q(a);c.objectStoreNames.contains(b)&&(c.close(),c=await q(a,d=>{d.deleteObjectStore(b);console.log("apagado")}));return c}async function t(a,b,c,...d){const e=a.i.transaction([a.h],b).objectStore(a.h)[c](...d);return new Promise((f,g)=>{e.onsuccess=l=>{f(l.target.result)};e.onerror=l=>{g(l.target.error)}})}
class v{constructor(a){const [b,c]=a.split(".");this.g=b;this.h=c}get i(){return h.get(this.g)}async j(){return await aa(this.g,this.h)}async get(a){return await t(this,"readonly","get",a)}async set(a,b){await t(this,"readwrite","put",b,a)}async s(a){await t(this,"readwrite","delete",a)}async l(){await t(this,"readwrite","clear")}async o(){return await t(this,"readwrite","getAllKeys")}async v(){await ba(this.g,this.h)}async u(){this.i.close();h.delete(this.g);return new Promise((a,b)=>{const c=indexedDB.deleteDatabase(this.g);
c.onsuccess=()=>{a()};c.onerror=d=>{b(d.target.error)}})}}function ca(a){a=new v(a);const b=[];b[0]=a.j.bind(a);b[1]=a.get.bind(a);b[2]=a.set.bind(a);b[3]=a.s.bind(a);b[4]=a.l.bind(a);b[5]=a.o.bind(a);b[6]=a.v.bind(a);b[7]=a.u.bind(a);return b};const y="clock_time_get fd_advise fd_allocate fd_datasync fd_fdstat_set_flags fd_fdstat_set_rights fd_filestat_get fd_filestat_set_size fd_filestat_set_times fd_pread fd_pwrite fd_read fd_readdir fd_renumber fd_sync fd_tell path_create_directory path_filestat_get path_filestat_set_times path_link path_open path_readlink path_remove_directory path_rename path_symlink path_unlink_file poll_oneoff sched_yield random_get sock_accept sock_recv sock_send sock_shutdown __wasm_longjmp __wasm_setjmp_test args_get args_sizes_get clock_res_get fd_close fd_fdstat_get fd_prestat_get fd_prestat_dir_name fd_seek fd_write proc_exit".split(" ");
async function da(a,b={}){a=new Response(new Blob([a],{type:"application/wasm"}));return await WebAssembly.instantiateStreaming(a,b)}console.log("DEV MODE",!0);function z(a,b){window.exp=a.F.instance.exports;return a.F.instance.exports[b]}
async function ea(a,b){let c=0;const d=async()=>{var e={wasi_snapshot_preview1:a.u,env:a.u};try{a.F=await da(b,e)}catch(f){return(e=String(f).match(/"(.*?)"\s*"(.*?)"/))?e[2]:null}return null};for(;100>c;){let e=await d();if(e)y.push(e),c++;else break}0<c&&(console.log("new imports demmand",c),console.log(y));a.J.forEach(e=>e());a.M()}async function fa(a){if(!a.F){var b=await fetch(`${"teste.wasm"}?v=${Date.now()}`);b.ok&&(b=await b.arrayBuffer(),await ea(a,b))}}
class ha{constructor(){this.J=[()=>{this.l=z(this,"memory");this.h=this.l.buffer;this.v=new Uint8Array(this.h);this.s=new DataView(this.h)},()=>this.G=z(this,"c01"),()=>z(this,"c02"),()=>this.M=z(this,"_start")]}get j(){this.l.buffer!==this.h&&(this.h=this.l.buffer,this.v=new Uint8Array(this.h),this.s=new DataView(this.h));return this.v}get view(){this.l.buffer!==this.h&&(this.h=this.l.buffer,this.v=new Uint8Array(this.h),this.s=new DataView(this.h));return this.s}G(){throw Error("Not initialized");
}M(){throw Error("Not initialized");}get u(){return this.N}get N(){const a={environ_get:(b,c)=>{console.log("environ_get",b,c);return 0},environ_sizes_get:(b,c)=>{this.view.setUint32(b,0,!0);this.view.setUint32(c,0,!0);return 0}};y.forEach(b=>{a[b]=(c,d,e,f)=>{console.log(b,c,d,e,f)}});return a}}
function A(a,b,c,d,e){if(33==b)return{D:a.g,key:c};if(34===b)return{D:a.g[c],key:e};if(35===b){let f=a.g[c];a=a.o.decode(a.j.subarray(d,d+e)).split(".");b=a.pop();a.forEach(g=>f=f[g]);return{D:f,key:b}}return null}
function B(a,b,c,d,e){if(2===b)return c;if(3===b)return e;if(4===b)return a.o.decode(a.j.subarray(d,d+c));if(33==b)return a.g[c];if(34===b)return a.g[c][e];if(35===b){let f=a.g[c];a.o.decode(a.j.subarray(d,d+e)).split(".").forEach(g=>f=f[g]);return f}if(1025==b)return a=ca(a.o.decode(a.j.subarray(d,d+c))),window.sa=a}
class ia extends ha{constructor(){super();this.J.push(()=>this.O=z(this,"c03"),()=>z(this,"c04"),()=>z(this,"c05"),()=>this.K=z(this,"c06"));this.g=[];this.o=new TextDecoder;this.T=new TextEncoder;this.g[0]=window}get u(){return{...this.N,...this.U}}get U(){return{j01:this.V.bind(this),j02:this.Y.bind(this),j03:this.W.bind(this),j04:this.ba.bind(this),j05:this.aa.bind(this),j06:this.$.bind(this),j07:this.write.bind(this),j08:this.Z.bind(this),j09:this.ca.bind(this),j10:this.S.bind(this),j11:this.X.bind(this)}}O(){throw Error("Not initialized");
}K(){throw Error("Not initialized");}V(a,b,c,d){(a=A(this,a,b,c,d))&&delete a.D[a.key]}Y(a,b,c,d){(a=A(this,a,b,c,d))&&(a.D[a.key]={})}W(a,b,c,d){(a=A(this,a,b,c,d))&&(a.D[a.key]=[])}ba(a,b,c,d){return B(this,a,b,c,d)}aa(a,b,c,d){return B(this,a,b,c,d)}$(a,b,c,d,e,f){a=B(this,a,b,c,d);a=this.T.encode(a);b=0;a.length>=f&&(b=e=this.G(a.length+1));this.j.set(a,e);this.j[e+a.length]=0;return b}Z(a,b,c,d,e){a=B(this,a,b,c,d);e&&this.view.setInt32(e,a?.byteLength??0,!0);if(!a)return 0;e=this.G(a.byteLength);
this.j.set(new Uint8Array(a),e);return e}write(a,b,c,d,e,f,g,l){(a=A(this,a,b,c,d))&&(a.D[a.key]=B(this,e,f,g,l))}ca(a,b,c,d,e,f,g,l,k,n,r,w,x){a=B(this,a,b,c,d);0==e?x=a():(e=B(this,e,f,g,l),x=x&&Array.isArray(e)?a(...e):a(e));(k=A(this,k,n,r,w))&&(k.D[k.key]=x)}S(a,b,c,d,e,f,g,l,k,n,r,w,x,la,ma,na,S,I,oa){const T=E=>{const u=A(this,x,la,ma,na);u&&(u.D[u.key]=E);this.K(S,0)};(async()=>{try{let u=!1,U=0;I&&(U=setTimeout(()=>{u=!0;T("timeout")},I));const J=B(this,a,b,c,d);let K;if(0==e)K=await J();
else{const L=B(this,e,f,g,l);K=oa&&Array.isArray(L)?await J(...L):await J(L)}if(!u){I&&clearTimeout(U);var E=A(this,k,n,r,w);E&&(E.D[E.key]=K);this.K(S,1)}}catch(u){T(u.name+": "+u.message)}})()}X(a,b,c,d,e,f){a=new (B(this,a,b,c,d))(...(e?this.g[e]:[]));f&&(this.g[f]=a)}};class ja extends ia{};class ka extends ja{constructor(){super();this.J.push(()=>this.i=z(this,"c07"),()=>z(this,"c08"),()=>z(this,"c10"),()=>z(this,"c11"))}i(){throw Error("Not initialized");}};function C(a,b,c){return d=>{const e=a[d??""];void 0===e&&"string"===typeof d&&console.error(`${c} ${d}`);return e??b}}function D(a){const b=Object.fromEntries(Object.entries(a).map(([c,d])=>[d,c]));return c=>b[c]}
var pa=D({arc:1,arcTo:2,bezierCurveTo:3,closePath:4,ellipse:5,lineTo:6,moveTo:7,quadraticCurveTo:8,rect:9,roundRect:10,addPath:11,clearRect:12,fillRect:13,strokeRect:14,getTransform:15,resetTransform:16,rotate:17,scale:18,setTransform:19,transform:20,translate:21,beginPath:22,clip:23,fill:24,isPointInPath:25,isPointInStroke:26,stroke:27,lineCap:28,lineDashOffset:29,lineJoin:30,lineWidth:31,miterLimit:32,getLineDash:33,setLineDash:34,drawImage:35,createImageData:36,getImageData:37,putImageData:38,
isContextLost:39,reset:40,restore:41,save:42,fillStyle:43,strokeStyle:44,P:45,createLinearGradient:46,createPattern:47,createRadialGradient:48,filter:49,globalAlpha:50,globalCompositeOperation:51,imageSmoothingEnabled:52,imageSmoothingQuality:53,getContextAttributes:54,shadowBlur:55,shadowColor:56,shadowOffsetX:57,shadowOffsetY:58,fillText:59,measureText:60,strokeText:61,direction:62,font:63,fontKerning:64,fontStretch:65,fontVariantCaps:66,letterSpacing:67,textAlign:68,textBaseline:69,textRendering:70,
wordSpacing:71,drawFocusIfNeeded:72,fa:100,ia:101,da:102,ea:103,ha:104,ga:105});const F={"source-over":0,"source-in":1,"source-out":2,"source-atop":3,"destination-over":4,"destination-in":5,"destination-out":6,"destination-atop":7,lighter:8,copy:9,xor:10,multiply:11,screen:12,overlay:13,darken:14,lighten:15,"color-dodge":16,"color-burn":17,"hard-light":18,"soft-light":19,difference:20,exclusion:21,hue:22,saturation:23,color:24,luminosity:25};var qa=C(F,F["source-over"],"eglobalCompositeOperation");
D(F);const G={ka:0,round:1,oa:2};var ra=C(G,0,"eLineCap");D(G);const H={ma:0,ja:1,round:2};var sa=C(H,0,"eLineJoin");D(H);D({repeat:0,"repeat-x":1,"repeat-y":2,"no-repeat":3});const M={na:0,la:1};var N=C(M,0,"eFillRule");D(M);
const ta={[1]:{m:3,A:1,C:2},[2]:{m:5},[3]:{m:6},[4]:{},[5]:{m:4,A:1,C:3},[6]:{m:2},[7]:{m:2},[8]:{m:4},[9]:{m:4},[10]:{m:4,I:3},[11]:{B:1,I:3},[12]:{m:4},[13]:{m:4},[14]:{m:4},[16]:{},[17]:{C:1},[18]:{C:2},[19]:{m:6},[20]:{m:6},[21]:{m:2},[22]:{},[23]:{A:1,B:1},[24]:{A:1,B:1},[27]:{B:1},[28]:{A:2},[29]:{L:1},[30]:{A:2},[31]:{C:1},[32]:{C:1},[34]:{H:7,B:1},[38]:{m:2,I:3,R:1},[41]:{},[42]:{},[43]:{H:4,B:1},[44]:{H:4,B:1},[50]:{L:1},[55]:{C:1},[56]:{L:7},[57]:{C:1},[58]:{C:1},[59]:{},[61]:{},[62]:{},
[63]:{},[64]:{},[65]:{},[66]:{},[67]:{},[68]:{},[69]:{},[70]:{},[71]:{},[100]:{size:1},[101]:{R:1,size:1},[102]:{},[103]:{},[104]:{A:1,size:1}};function O(a){if(a instanceof OffscreenCanvas||a instanceof HTMLCanvasElement)return a=a.getContext("2d").getImageData(0,0,a.width,a.height),{width:a.width,height:a.height,data:a.data};if(a instanceof ImageBitmap){var b=new OffscreenCanvas(a.width,a.height);b.getContext("2d").drawImage(a,0,0);return O(b)}let c;a instanceof HTMLImageElement?(b=a.naturalWidth,c=a.naturalHeight):a instanceof HTMLVideoElement?(b=a.videoWidth,c=a.videoHeight):(b=a.width,c=a.height);b=new OffscreenCanvas(b,c);b.getContext("2d").drawImage(a,
0,0);return O(b)}function ua(a){a=[...a.trim().replace(/^#/,"")].map(b=>parseInt(b,16));return[16*a[0]+a[1],16*a[2]+a[3],16*a[4]+a[5]]}function P(a){if(-1<a.indexOf("#"))a=ua(a);else{const b=a.match(/[\d.]+/g)?.map(Number)??[];4===b.length&&/%/.test(a)&&(b[3]/=100);a=b}return a};class va extends DataView{constructor(a){super(a,void 0,void 0);this.j=new Uint8Array(this.buffer)}i(a,b,c){var d=this.j,e=c??!1;c=10;let f,g=16-c-1;const l=(1<<g)-1,k=l>>1,n=23===c?Math.pow(2,-24)-Math.pow(2,-77):0;let r=e?0:1;const w=e?1:-1,x=0>b||0===b&&0>1/b?1:0;b=Math.abs(b);isNaN(b)||Infinity===b?(b=isNaN(b)?1:0,e=l):(e=Math.floor(Math.log(b)/Math.LN2),1>b*(f=Math.pow(2,-e))&&(e--,f*=2),b=1<=e+k?b+n/f:b+n*Math.pow(2,1-k),2<=b*f&&(e++,f/=2),e+k>=l?(b=0,e=l):1<=e+k?(b=(b*f-1)*Math.pow(2,c),e+=
k):(b=b*Math.pow(2,k-1)*Math.pow(2,c),e=0));for(;8<=c;)d[a+r]=b&255,r+=w,b/=256,c-=8;e=e<<c|b;for(g+=c;0<g;)d[a+r]=e&255,r+=w,e/=256,g-=8;d[a+r-w]|=128*x}}function Q(a,b,c){b+=c;b>=a.g.byteLength&&(c=new Uint8Array(a.g.buffer),a.h=new ArrayBuffer(Math.max(a.g.byteLength+500,b)),a.g=new va(a.h),(new Uint8Array(a.h)).set(c))}
class wa{constructor(){this.h=new ArrayBuffer(500);this.g=new va(this.h)}get buffer(){return this.g.buffer}get byteLength(){return this.g.byteLength}get byteOffset(){return this.g.byteOffset}i(a,b,c){this.g.i(a,b,c)}getFloat32(a,b){return this.g.getFloat32(a,b)}setFloat32(a,b,c){Q(this,a,4);this.g.setFloat32(a,b,c)}getFloat64(a,b){return this.g.getFloat64(a,b)}setFloat64(a,b,c){Q(this,a,8);this.g.setFloat64(a,b,c)}getUint8(a){return this.g.getUint8(a)}setUint8(a,b){Q(this,a,1);this.g.setUint8(a,b)}getUint16(a,
b){return this.g.getUint16(a,b)}setUint16(a,b,c){Q(this,a,2);this.g.setUint16(a,b,c)}getUint32(a,b){return this.g.getUint32(a,b)}setUint32(a,b,c){Q(this,a,4);this.g.setUint32(a,b,c)}getInt8(a){return this.g.getInt8(a)}setInt8(a,b){Q(this,a,1);this.g.setInt8(a,b)}getInt16(a,b){return this.g.getInt16(a,b)}setInt16(a,b,c){Q(this,a,2);this.g.setInt16(a,b,c)}getInt32(a,b){return this.g.getInt32(a,b)}setInt32(a,b,c){Q(this,a,4);this.g.setInt32(a,b,c)}getBigInt64(a,b){return this.g.getBigInt64(a,b)}setBigInt64(a,
b,c){Q(this,a,8);this.g.setBigInt64(a,b,c)}getBigUint64(a,b){return this.g.getBigUint64(a,b)}setBigUint64(a,b,c){Q(this,a,8);this.g.setBigUint64(a,b,c)}};function R(a,b,c){b=(1<<b)-1;if((a|b)!==b)throw Error(`${a} > ${b}`);return(b&a)<<c}
function V(a){a.F++;let b=a.size;a.h.setUint8(b,a.e);b++;const c=b,d=ta[a.e];d||console.log(a.e);const e=Math.ceil(((d.A??0)+(d.H??0)+(d.B??0)+(d.I??0)+2*(d.m??0))/8);b+=e;[...a.g,...a.u,...a.s,...a.i,...a.j,...a.v,...a.l];for(var f=0;f<(d.C??0);f++)a.h.i(b,a.i[f]??0,!0),b+=2;a.i.length=0;for(f=0;f<(d.L??0);f++)a.h.setUint8(b,a.u[f]??0),b+=1;a.u.length=0;for(f=0;f<(d.R??0);f++)a.h.setUint16(b,a.v[f]??0,!0),b+=2;let g=f=a.v.length=0;d.A&&(f|=R(a.o,d.A,g),g+=d.A,a.o=0);d.H&&(f|=R(a.s.length,d.H,g),
g+=d.H,a.s.forEach(k=>{a.h.setUint8(b,k);b+=1}),a.s.length=0);d.B&&(f|=R(a.l.length,d.B,g),g+=d.B,a.l.forEach(k=>{a.h.setUint16(b,k,!0);b+=2}),a.v.length=0);d.I&&(f|=R(a.j.length,d.I,g),g+=d.I,a.j.forEach(k=>{a.h.setFloat32(b,k,!0);b+=4}),a.j.length=0);for(let k=0;k<(d.m??0);k++){var l=a.g[k]??0;if(Number.isInteger(l))if(256>Math.abs(l)){0<l?(a.h.setUint8(b,l),l=R(0,2,g),g+=2,f|=l):(a.h.setUint8(b,l),l=R(1,2,g),g+=2,f|=l);b+=1;continue}else if(32768>Math.abs(l)){a.h.setInt16(b,l,!0);l=R(2,2,g);g+=
2;f|=l;b+=2;continue}a.h.setFloat32(b,l,!0);l=R(3,2,g);g+=2;f|=l;b+=4}a.g.length=0;if(0!=e)if(1==e)a.h.setUint8(c,f);else if(2==e)a.h.setUint16(c,f,!0);else if(4>=e)a.h.setUint32(c,f,!0);else throw Error();a.size=b}class xa{constructor(){this.h=new wa;this.h.setUint8(0,100);this.size=5;this.g=[];this.u=[];this.v=[];this.s=[];this.l=[];this.j=[];this.i=[];this.F=0}get size(){return this.h.getUint32(1,!0)}set size(a){this.h.setUint32(1,a,!0)}get G(){return this.h.buffer.slice(0,this.size)}};function W(a){if(a instanceof Path2D)throw Error("not a Path2DArray");return-1}class ya{}function X(a){44!==a&&43!==a&&63!==a&&60!==a&&console.log(pa(a))}
class za{constructor(){this.h=new xa;this.i=new ya;this.i.g=this.h;this.canvas=new OffscreenCanvas(200,200);this.g=this.canvas.getContext("2d")}arc(a,b,c,d,e,f){const g=this.h;g.e=1;g.g[0]=a;g.g[1]=b;g.g[2]=c;g.i[0]=d;g.i[1]=e;g.o=f?1:0;V(g);this.g.arc(a,b,c,d,e,f)}arcTo(a,b,c,d,e){const f=this.h;f.e=2;f.g[0]=a;f.g[1]=b;f.g[2]=c;f.g[3]=d;f.g[4]=e;V(f);this.g.arcTo(a,b,c,d,e)}bezierCurveTo(a,b,c,d,e,f){const g=this.h;g.e=3;g.g[0]=a;g.g[1]=b;g.g[2]=c;g.g[3]=d;g.g[4]=e;g.g[5]=f;V(g);this.g.bezierCurveTo(a,
b,c,d,e,f)}closePath(){const a=this.h;a.e=4;V(a);this.g.closePath()}ellipse(a,b,c,d,e,f,g,l){const k=this.h;k.e=5;k.g[0]=a;k.g[1]=b;k.g[2]=c;k.g[3]=d;k.i[0]=e;k.i[1]=f;k.i[2]=g;k.o=l?1:0;V(k);this.g.ellipse(a,b,c,d,e,f,g,l)}lineTo(a,b){const c=this.h;c.e=6;c.g[0]=a;c.g[1]=b;V(c);this.g.lineTo(a,b)}moveTo(a,b){const c=this.h;c.e=7;c.g[0]=a;c.g[1]=b;V(c);this.g.moveTo(a,b)}quadraticCurveTo(a,b,c,d){const e=this.h;e.e=8;e.g[0]=a;e.g[1]=b;e.g[2]=c;e.g[3]=d;V(e);this.g.quadraticCurveTo(a,b,c,d)}rect(a,
b,c,d){const e=this.h;e.e=9;e.g[0]=a;e.g[1]=b;e.g[2]=c;e.g[3]=d;V(e);this.g.rect(a,b,c,d)}roundRect(a,b,c,d,e){const f=this.h;f.e=10;f.g[0]=a;f.g[1]=b;f.g[2]=c;f.g[3]=d;const g=[],l=k=>{"number"===typeof k.x&&g.push(k.x);"number"===typeof k.y&&g.push(k.y)};"number"===typeof e?g.push(e):Array.isArray(e)?e.forEach(k=>{"number"===typeof k?g.push(k):l(k)}):e&&l(e);g.forEach((k,n)=>f.j[n]=k);V(f);this.g.roundRect(a,b,c,d,e)}addPath(a,b){const c=this.h;c.e=11;a=W(a);-1<a&&(c.l[0]=a,b&&(c.j[0]=b.a,c.j[1]=
b.b,c.j[2]=b.c,c.j[3]=b.d,c.j[4]=b.e,c.j[5]=b.f));V(c)}clearRect(a,b,c,d){const e=this.h;e.e=12;e.g[0]=a;e.g[1]=b;e.g[2]=c;e.g[3]=d;V(e);this.g.clearRect(a,b,c,d)}fillRect(a,b,c,d){const e=this.h;e.e=13;e.g[0]=a;e.g[1]=b;e.g[2]=c;e.g[3]=d;V(e);this.g.fillRect(a,b,c,d)}strokeRect(a,b,c,d){const e=this.h;e.e=14;e.g[0]=a;e.g[1]=b;e.g[2]=c;e.g[3]=d;V(e);this.g.strokeRect(a,b,c,d)}getTransform(){X(15);return this.g.getTransform()}resetTransform(){const a=this.h;a.e=16;V(a);this.g.resetTransform()}rotate(a){const b=
this.h;b.e=17;b.i[0]=a;V(b);this.g.rotate(a)}scale(a,b){const c=this.h;c.e=18;c.i[0]=a;c.i[1]=b;V(c);this.g.scale(a,b)}setTransform(a,b,c,d,e,f){const g=this.h;g.e=19;"number"!==typeof a&&(b=a.b,c=a.c,d=a.d,e=a.e,f=a.f,a=a.a);g.g[0]=a??0;g.g[1]=b??0;g.g[2]=c??0;g.g[3]=d??0;g.g[4]=e??0;g.g[5]=f??0;V(g);this.g.setTransform(a,b,c,d,e,f)}transform(a,b,c,d,e,f){const g=this.h;g.e=20;g.g[0]=a;g.g[1]=b;g.g[2]=c;g.g[3]=d;g.g[4]=e;g.g[5]=f;V(g);this.g.transform(a,b,c,d,e,f)}translate(a,b){const c=this.h;c.e=
21;c.g[0]=a;c.g[1]=b;V(c);this.g.translate(a,b)}beginPath(){const a=this.h;a.e=22;V(a);this.g.beginPath()}clip(a,b){const c=this.h;c.e=23;let d=W(a);-1<d?c.l[0]=d:"string"===typeof a&&(b=a,a=void 0);c.o=N(b);V(c);a&&b?this.g.clip(a,b):a?this.g.clip(a):b?this.g.clip(b):this.g.clip()}fill(a,b){const c=this.h;c.e=24;let d=W(a);-1<d?c.l[0]=d:"string"===typeof a&&(b=a,a=void 0);c.o=N(b);V(c);a&&b?this.g.fill(a,b):a?this.g.fill(a):b?this.g.fill(b):this.g.fill()}isPointInPath(a,b,c,d){X(25);return a instanceof
Path2D?this.g.isPointInPath(a,b,c,d):this.g.isPointInPath(a,b,c)}isPointInStroke(a,b,c){X(26);return a instanceof Path2D?this.g.isPointInStroke(a,b,c):this.g.isPointInStroke(a,b)}stroke(a){const b=this.h;b.e=27;let c=W(a);-1<c&&(b.l[0]=c);V(b);a?this.g.stroke(a):this.g.stroke()}get lineCap(){X(28);return this.g.lineCap}set lineCap(a){const b=this.h;b.e=28;b.o=ra(a);V(b);this.g.lineCap=a}get lineDashOffset(){X(29);return this.g.lineDashOffset}set lineDashOffset(a){const b=this.h;b.e=29;b.g[0]=a;V(b);
this.g.lineDashOffset=a}get lineJoin(){X(30);return this.g.lineJoin}set lineJoin(a){const b=this.h;b.e=30;b.o=sa(a);V(b);this.g.lineJoin=a}get lineWidth(){X(31);return this.g.lineWidth}set lineWidth(a){const b=this.h;b.e=31;b.i[0]=a;V(b);this.g.lineWidth=a}get miterLimit(){X(32);return this.g.miterLimit}set miterLimit(a){const b=this.h;b.e=32;b.g[0]=a;V(b);this.g.miterLimit=a}getLineDash(){X(33);return this.g.getLineDash()}setLineDash(a){const b=this.h;b.e=34;this.g.setLineDash(a);if(a&&a.length){const c=
Math.max(...a);if(128>a.length&&256>c)a.forEach((d,e)=>b.u[e]=Math.trunc(d));else throw b.o=128,Error();}V(b);this.g.setLineDash(a)}drawImage(a,b,c,d,e,f,g,l,k){const n=this.h;n.e=35;V(n);"number"===typeof f?this.g.drawImage(a,b,c,d,e,f,g,l,k):"number"===typeof d?this.g.drawImage(a,b,c,d,e):this.g.drawImage(a,b,c)}createImageData(a,b){X(36);return this.g.createImageData(a,b)}getImageData(a,b,c,d){X(37);return this.g.getImageData(a,b,c,d)}putImageData(a,b,c,d,e,f,g){a=this.h;a.e=38;a.g[0]=b;a.g[1]=
c;b=[d,e,f,g];for(c=0;c<b.length;c++){d=b[c];if(void 0===d)break;a.j[c]=d}throw Error();}isContextLost(){X(39);return this.g.isContextLost()}reset(){const a=this.h;a.e=40;V(a);this.g.reset()}restore(){const a=this.h;a.e=41;V(a);this.g.restore()}save(){const a=this.h;a.e=42;V(a);this.g.save()}get fillStyle(){X(43);return this.g.fillStyle}set fillStyle(a){const b=this.h;b.e=43;if("string"===typeof a)this.g.fillStyle=a,b.s=P(this.g.fillStyle);else{let c=W(a);-1<c&&(b.l[0]=c);if(a instanceof Y||a instanceof
Z)this.g.fillStyle=a.g;else throw Error();}V(b)}get strokeStyle(){X(44);return this.g.strokeStyle}set strokeStyle(a){const b=this.h;b.e=44;if("string"===typeof a)this.g.strokeStyle=a,b.s=P(this.g.strokeStyle);else{let c=W(a);0<=c&&(b.l[0]=c);if(a instanceof Y||a instanceof Z)this.g.fillStyle=a.g;else throw Error();}V(b)}P(a,b,c){X(45);var d=this.g.P(a,b,c);d=new Y(d);d.F=b;d.G=c;d.v=a;return d}createLinearGradient(a,b,c,d){X(46);var e=this.g.createLinearGradient(a,b,c,d);e=new Y(e);e.i=a;e.j=c;e.l=
b;e.o=d;return e}createPattern(a,b){X(47);var c=this.g.createPattern(a,b??"");c=new Z(c);if(a){a instanceof VideoFrame&&console.error("async toImageBuffer VideoFrame");a=O(a);c.data=a.data;c.height=a.height;c.width=a.width;if(b)throw Error();c.i=0}return c}createRadialGradient(a,b,c,d,e,f){X(48);var g=this.g.createRadialGradient(a,b,c,d,e,f);g=new Y(g);g.i=a;g.j=d;g.l=b;g.o=e;g.s=c;g.u=f;return g}get filter(){X(49);return this.g.filter}set filter(a){const b=this.h;b.e=49;V(b);this.g.filter=a}get globalAlpha(){X(50);
return this.g.globalAlpha}set globalAlpha(a){const b=this.h;b.e=50;b.u[0]=255*a;V(b);this.g.globalAlpha=a}get globalCompositeOperation(){X(51);return this.g.globalCompositeOperation}set globalCompositeOperation(a){const b=this.h;b.e=51;b.o=qa(a);V(b);this.g.globalCompositeOperation=a}get shadowBlur(){X(55);return this.g.shadowBlur}set shadowBlur(a){const b=this.h;b.e=55;b.g[0]=a;V(b);this.g.shadowBlur=a}get shadowColor(){X(56);return this.g.shadowColor}set shadowColor(a){const b=this.h;b.e=57;this.g.shadowColor=
a;V(b);this.g.shadowColor=a}get shadowOffsetX(){X(57);return this.g.shadowOffsetX}set shadowOffsetX(a){const b=this.h;b.e=57;b.g[0]=a;V(b);this.g.shadowOffsetX=a}get shadowOffsetY(){X(58);return this.g.shadowOffsetY}set shadowOffsetY(a){const b=this.h;b.e=58;b.g[0]=a;V(b);this.g.shadowOffsetY=a}fillText(a,b,c,d){const e=this.h;e.e=59;V(e);this.g.fillText(a,b,c,d)}strokeText(a,b,c,d){const e=this.h;e.e=61;V(e);this.g.strokeText(a,b,c,d)}measureText(a){X(60);return this.g.measureText(a)}get direction(){X(62);
return this.g.direction}set direction(a){const b=this.h;b.e=62;V(b);this.g.direction=a}get font(){X(63);return this.g.font}set font(a){const b=this.h;b.e=63;V(b);this.g.font=a}get fontKerning(){X(64);return this.g.fontKerning}set fontKerning(a){const b=this.h;b.e=64;V(b);this.g.fontKerning=a}get fontStretch(){X(65);return this.g.fontStretch}set fontStretch(a){const b=this.h;b.e=65;V(b);this.g.fontStretch=a}get fontVariantCaps(){X(66);return this.g.fontVariantCaps}set fontVariantCaps(a){const b=this.h;
b.e=66;V(b);this.g.fontVariantCaps=a}get letterSpacing(){X(67);return this.g.letterSpacing}set letterSpacing(a){const b=this.h;b.e=67;V(b);this.g.letterSpacing=a}get textAlign(){X(68);return this.g.textAlign}set textAlign(a){const b=this.h;b.e=68;V(b);this.g.textAlign=a}get textBaseline(){X(69);return this.g.textBaseline}set textBaseline(a){const b=this.h;b.e=69;V(b);this.g.textBaseline=a}get textRendering(){X(70);return this.g.textRendering}set textRendering(a){const b=this.h;b.e=70;V(b);this.g.textRendering=
a}get wordSpacing(){X(71);return this.g.wordSpacing}set wordSpacing(a){const b=this.h;b.e=71;V(b);this.g.wordSpacing=a}}class Y{constructor(a){this.g=a;this.h=[]}addColorStop(a,b){this.h.push({offset:a,color:b});this.g.addColorStop(a,b)}}class Z{constructor(a){this.g=a;this.data=null;this.h=[]}setTransform(a){this.g.setTransform(a);a&&this.h.push(a)}};function Aa(a,b){b=new Uint8ClampedArray(a.g.j.subarray(b,b+a.size));b=new ImageData(b,a.width,a.height);a.l.putImageData(b,0,0)}
class Ba{constructor(a,b){this.g=a;this.h=b;this.l=b.getContext("2d");this.size=0;this.width=b.offsetWidth;this.height=b.offsetHeight;this.s=[()=>window.requestAnimationFrame(this.i.bind(this))];this.o=this.g.O();this.g.g[this.o]=this.s;window.requestAnimationFrame(this.i.bind(this));window.addEventListener("resize",this.j.bind(this));this.j();Ca(this)}j(){this.width=this.h.width=this.h.offsetWidth;this.height=this.h.height=this.h.offsetHeight;this.size=this.g.i(6,1,this.width,this.height,0,0);const a=
this.g.i(7,1,0,0,0,0);a&&Aa(this,a)}i(a){(a=this.g.i(7,1,0,0,0,a))&&Aa(this,a);window.requestAnimationFrame(this.i.bind(this))}}
var Ca=a=>{function b(c){return c.buttons??(void 0!==c.button?1<<c.button:0)}a.h.addEventListener("mousedown",c=>{a.g.i(0,1,c.offsetX,c.offsetY,b(c),0)});a.h.addEventListener("mouseup",c=>{a.g.i(1,1,c.offsetX,c.offsetY,b(c),0)});a.h.addEventListener("mousemove",c=>{a.g.i(2,1,c.offsetX,c.offsetY,b(c),0)});a.h.addEventListener("wheel",c=>{a.g.i(3,1,c.offsetX,c.offsetY,b(c),c.deltaY)},{passive:!0});a.h.addEventListener("mouseenter",c=>{a.g.i(4,1,c.offsetX,c.offsetY,b(c),0)});a.h.addEventListener("mouseleave",
c=>{a.g.i(5,1,c.offsetX,c.offsetY,b(c),0)})};async function Da(a,b,c){console.log(1);let d=new Ba(a,b);console.log(2);window.ctx=d.l;window.canvas=d.h;window.mem=a.g;a=new v("stg.mandala");await a.j();c.width=b.width;c.height=b.height;b=new za;c.getContext("2d");b.strokeStyle="brown";b.lineWidth=15;b.strokeRect(400,500,200,100);b.fillStyle="pink";b.fillRect(200,200,200,100);c=Math.PI;b.fillStyle="yellow";b.arc(600,300,150,0,3*c/2);b.closePath();b.stroke();b.fill();await a.set("bvg3",b.h.G)};document.addEventListener("DOMContentLoaded",async function(){let a=new ka;await fa(a);var b=()=>{const d=document.createElement("canvas");d.style.position="fixed";d.style.top="0";d.style.left="0";d.style.height="100vh";d.style.width="100vw";document.getElementById("dmain")?.appendChild(d);return d};const c=b("1");b=b("2");b.style.pointerEvents="none";Da(a,c,b)});}).call(this);
