(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=this||self;async function ba(a){console.log("sleep",a);return new Promise(b=>setTimeout(b,a))};const l=new Map,ca=l.delete.bind(l),da=new BroadcastChannel("ib");da.onmessage=a=>{a=a.data;1===a.m&&(l.get(a.n)?.close(),ca(a.n))};l.delete=a=>{da.postMessage({m:1,n:a});return ca(a)};
async function u(a,b){var d=l.get(a);if(d&&!b)return d;let f;b&&(d=await u(a),f=d.version+1,d.close());return new Promise((c,e)=>{let g=!1,h=!1;setTimeout(()=>{g||e(Error(`indexedDB timeout: bloqueado: ${h?"essa aba":"outra"} (${a})`))},100);const k=indexedDB.open(a,f);k.onsuccess=p=>{g=!0;p=p.target.result;l.set(a,p);c(p)};k.onerror=p=>{g=!0;e(p.target.error)};k.onupgradeneeded=p=>{g=!0;p=p.target.result;b&&b(p)};k.onblocked=()=>{h=!0}})}
async function ea(a,b){let d=await u(a);d.objectStoreNames.contains(b)||(d.close(),d=await u(a,f=>{f.createObjectStore(b)}));return d}async function fa(a,b){let d=await u(a);d.objectStoreNames.contains(b)&&(d.close(),d=await u(a,f=>{f.deleteObjectStore(b);console.log("apagado")}));return d}async function v(a,b,d,...f){const c=a.j.transaction([a.h],b).objectStore(a.h)[d](...f);return new Promise((e,g)=>{c.onsuccess=h=>{e(h.target.result)};c.onerror=h=>{g(h.target.error)}})}
class w{constructor(a){const [b,d]=a.split(".");this.g=b;this.h=d}get j(){return l.get(this.g)}async i(){return await ea(this.g,this.h)}async get(a){return await v(this,"readonly","get",a)}async set(a,b){await v(this,"readwrite","put",b,a)}async l(a){await v(this,"readwrite","delete",a)}async o(){await v(this,"readwrite","clear")}async s(){return await v(this,"readwrite","getAllKeys")}async A(){await fa(this.g,this.h)}async u(){this.j.close();l.delete(this.g);return new Promise((a,b)=>{const d=indexedDB.deleteDatabase(this.g);
d.onsuccess=()=>{a()};d.onerror=f=>{b(f.target.error)}})}}function ha(a){a=new w(a);const b=[];b[0]=a.i.bind(a);b[1]=a.get.bind(a);b[2]=a.set.bind(a);b[3]=a.l.bind(a);b[4]=a.o.bind(a);b[5]=a.s.bind(a);b[6]=a.A.bind(a);b[7]=a.u.bind(a);return b};async function ia(a=null){let b={};if(null!==a){let d="desktop documents downloads music pictures videos".split(" ");"FileSystemDirectoryHandle"===(a?.constructor.name??"")||d.includes(a)?b.startIn=a:"string"===typeof a&&(b.id=a)}try{return await window.showDirectoryPicker(b)}catch(d){return null}}async function ma(a){try{return"granted"===await a.queryPermission()||"granted"===await a.requestPermission()}catch(b){return!1}};async function na(a,b){a=new oa(a,b);await pa(a);return a}async function pa(a){if("file"===a.handle.kind){a.g=await a.handle.getFile();a.size=a.g.size;a.mimeType=a.g.type;var b=new Date(a.g.lastModified);a.modifiedTime=`${(b.getMonth()+1).toString().padStart(2,"0")}-${b.getDate().toString().padStart(2,"0")}-${b.getFullYear()} ${b.getHours().toString().padStart(2,"0")}:${b.getMinutes().toString().padStart(2,"0")}:${b.getSeconds().toString().padStart(2,"0")}`}}
class oa{constructor(a,b){this.folder=a;this.name=b.name;this.handle=b;"file"===b.kind?this.isfile=!0:"directory"===b.kind&&(this.isfile=!1)}}async function qa(a,b=!0,d=""){let f=[];if(!a)return f;for await(const e of a.values()){var c=e;a=await na(d,c);if("file"===c.kind)a.isfile=!0,f.push(a);else if("directory"===c.kind){a.isfile=!1;c=await qa(c,b,d?`${d}/${c.name}`:c.name);if(b)for(let g of c)f.push(g);else a.h=c;f.push(a)}}return f}
async function ra(a,b,d=!1){if(!a||!b)return a;b=b.split("/").filter(Boolean);try{for(const f of b)a=await a.getDirectoryHandle(f,{create:d});return a}catch(f){if("NotFoundError"===f.name)return null;throw f;}};async function sa(a){let b;if(a.ja)b=a.ja;else if(a.W)b=new w(a.W),await b.i();else{if(a.throw)throw Error("no storage passed");return{persisted:!1,handle:null}}a.reload&&await b.l(a.key);var d=await b.get(a.key);let f=await ma(d);if((d=f?d:await ia(d))&&await ma(d))await b.set(a.key,d);else{if(a.throw)throw Error("dir handle not  aquired");return{persisted:!1,handle:null}}return{persisted:f,handle:d}}
async function ta(a,b,d){if(a.h&&(d=await ra(a.h,d),d=await qa(d,!0),d.length)){var f=q=>6>q?!0:10===q||16===q,c=q=>f(q)?a.g.view.getInt32(b+4*q,!0):a.g.view.getFloat64(b+4*q,!0),e=(q,r)=>{f(q)?a.g.view.setInt32(b+4*q,r,!0):a.g.view.setFloat64(b+4*q,r,!0)},g=c(0),h=c(2),k=c(3),p=c(4),m=c(10),n=c(16),t=async(q,r)=>{1===q?(q=await r.g.text(),q=a.g.M.encode(q),r=c(12),q.length+1>r&&(m&&a.g.N(m),r=q.length+1,m=a.g.s(r),e(10,m),e(12,r)),e(14,q.length),a.g.h.set(q,m),a.g.view.setUint8(m+q.length,0)):2===
q?r.handle instanceof FileSystemFileHandle&&(q=await r.handle.createWritable(),r=(r=c(14))?a.g.j(n,n+r):"",await q.write(r),await q.close()):3==q?(q=await r.g.arrayBuffer(),r=c(18),q.byteLength>r&&(n&&a.g.N(n),r=q.byteLength,n=a.g.s(r),e(16,n),e(18,r)),e(20,q.byteLength),a.g.h.set(new Uint8Array(q),n)):4===q&&r.handle instanceof FileSystemFileHandle&&(q=await r.handle.createWritable(),r=c(20),await q.write(a.g.h.subarray(n,n+r)),await q.close())};for(let q=0;q<d.length;q++){const r=d[q];a.g.K(r.name,
h);a.g.K(r.folder,k);a.g.K(r.mimeType,p);r.isfile?(e(6,r.size),e(8,r.g.lastModified)):(e(6,0),e(8,0));e(1,0);a.g.u(g,2);const L=c(1);L&&(await t(L,r),a.g.u(g,2))}}}async function ua(a,b,d,f){if(a=await (await ra(a.h,b,!0))?.getFileHandle(d,{create:!0}))a=await a.createWritable(),await a.write(f),await a.close()}function va(){console.log("m3")}class wa{}
var xa=async(a,b,d,f)=>{const c=new wa;b=await sa({W:b,key:d,reload:f,throw:!0});b.handle&&(c.h=b.handle);c.g=a;return(e,...g)=>{switch(e){case 1:return ta(c,...g);case 2:return ua(c,...g);case 3:return va(...g)}}};const x="fd_advise fd_allocate fd_datasync fd_fdstat_set_flags fd_fdstat_set_rights fd_filestat_get fd_filestat_set_size fd_filestat_set_times fd_pread fd_pwrite fd_read fd_readdir fd_renumber fd_sync fd_tell path_create_directory path_filestat_get path_filestat_set_times path_link path_open path_readlink path_remove_directory path_rename path_symlink path_unlink_file poll_oneoff sched_yield sock_accept sock_recv sock_send sock_shutdown __wasm_longjmp __wasm_setjmp_test args_get args_sizes_get clock_res_get fd_close fd_prestat_get fd_prestat_dir_name fd_seek proc_exit".split(" ");
async function ya(a,b={}){a=new Response(new Blob([a],{type:"application/wasm"}));return await WebAssembly.instantiateStreaming(a,b)}console.log("DEV MODE",!0);function z(a,b){window.exp=a.O.instance.exports;return a.O.instance.exports[b]}
async function za(a,b){let d=0;const f=async()=>{var c={wasi_snapshot_preview1:a.J,env:a.J};try{a.O=await ya(b,c)}catch(e){return(c=String(e).match(/"(.*?)"\s*"(.*?)"/))?c[2]:null}return null};for(;100>d;){let c=await f();if(c)x.push(c),d++;else break}0<d&&(console.log("new imports demmand",d),console.log(x));a.P.forEach(c=>c());a.S()}async function Aa(a){if(!a.O){var b=await fetch(`${"teste.wasm"}?v=${Date.now()}`);b.ok&&(b=await b.arrayBuffer(),await za(a,b))}}
class Ba{constructor(){this.P=[()=>{this.o=z(this,"memory");this.i=this.o.buffer;this.F=new Uint8Array(this.i);this.I=new DataView(this.i)},()=>this.s=z(this,"c01"),()=>this.N=z(this,"c02"),()=>this.S=z(this,"_start")]}get Y(){return this.o.buffer}get h(){this.o.buffer!==this.i&&(this.i=this.o.buffer,this.F=new Uint8Array(this.i),this.I=new DataView(this.i));return this.F}get view(){this.o.buffer!==this.i&&(this.i=this.o.buffer,this.F=new Uint8Array(this.i),this.I=new DataView(this.i));return this.I}s(){throw Error("Not initialized");
}N(){throw Error("Not initialized");}S(){throw Error("Not initialized");}get J(){return this.U}get U(){const a={fd_write:(d,f,c,e)=>{let g=0;for(let p=0;p<c;p++){var h=f+8*p,k=this.view.getUint32(h,!0);h=this.view.getUint32(h+4,!0);k=this.h.slice(k,k+h);k.every(m=>0===m||10===m||13===m)||(k=(new TextDecoder).decode(k),console[1===d?"log":"error"](k));g+=h}this.view.setUint32(e,g,!0)},fd_fdstat_get:(d,f)=>{this.view.setUint8(f,0);this.view.setUint8(f+1,0);this.view.setBigUint64(f+8>>>3,18446744073709551615n,
!0);this.view.setBigUint64(f+16>>>3,18446744073709551615n,!0);return 0},clock_time_get:(d,f,c)=>{0===d?this.view.setBigUint64(c,1000000n*BigInt(Date.now()),!0):1===d?this.view.setBigUint64(c,BigInt(Math.floor(1E6*performance.now())),!0):this.view.setBigUint64(c,0n,!0);return 0},environ_get:(d,f)=>{console.log("environ_get",d,f);return 0},environ_sizes_get:(d,f)=>{this.view.setUint32(d,0,!0);this.view.setUint32(f,0,!0);return 0},random_get:(d,f)=>{d=this.h.subarray(d,d+f);if("undefined"!==typeof crypto&&
"function"===typeof crypto.getRandomValues)crypto.getRandomValues(d);else for(let c=0;c<f;c++)d[c]=256*Math.random()|0;return 0},__wasm_setjmp:()=>{}},b=new Map;x.forEach(d=>{a[d]=(f,c,e,g)=>{b.has(d)||b.set(d,0);const h=b.get(d);if(10<h)throw Error("limite "+d);b.set(d,h+1);console.log(d,f,c,e,g)}});return a}}
function A(a,b,d,f,c){if(33==b)return{G:a.g,key:d};if(34===b)return{G:a.g[d],key:c};if(35===b){let e=a.g[d];a=a.j(f,f+c).split(".");b=a.pop();a.forEach(g=>e=e[g]);return{G:e,key:b}}return null}
function B(a,b,d,f,c){if(b&2048)return B(a,b-2048,d,f,c)?1:0;if(b&4096)return Number(B(a,b-4096,d,f,c));if(2===b)return d;if(3===b)return c;if(4===b)return a.j(f,f+d);if(9===b){b=[];c=a.view;for(let e=0;e<d;e++)b.push(c.getFloat64(f,!0)),f+=8;return b}if(10===b)return b=[0,1,2,3].map(e=>a.view.getInt32(f+4*e,!0)),d=a.j(b[0],b[1]),b=a.j(b[2],b[3]),[...d.matchAll(new RegExp(b,"g"))][0];if(33==b)return a.g[d];if(34===b)return a.g[d][c];if(35===b){let e=a.g[d];a.j(f,f+c).split(".").forEach(g=>e=e[g]);
return e}if(38===b){let e=a.g[d];a.j(f,f+c).split(".").forEach(g=>{e=e[g].bind(e)});return e}if(37===b)return window.mem=a.g;if(1025===b)return ha(a.j(f,f+d));if(1026===b){const e=a.view,g=Array(6).fill(0).map((p,m)=>e.getInt32(f+4*m,!0)),h=a.j(g[0],g[1]),k=a.j(g[2],g[3]);return()=>xa(a,h,k,g[4])}if(1027===b)return ba}
class Ca extends Ba{constructor(){super();this.P.push(()=>this.A=z(this,"c03"),()=>z(this,"c04"),()=>z(this,"c05"),()=>this.u=z(this,"c06"));this.g=[];this.T=new TextDecoder;this.M=new TextEncoder;this.K=(a,b)=>{a=this.M.encode(a);400<=a.length&&(a=a.subarray(0,399));this.h.set(a,b);this.view.setUint8(b+a.length,0)};this.j=(a,b)=>this.T.decode(this.h.subarray(a,b));this.g[0]=window}get J(){return{...this.U,...this.$}}get $(){return{j01:this.aa.bind(this),j02:this.da.bind(this),j03:this.ba.bind(this),
j04:this.ha.bind(this),j05:this.ga.bind(this),j06:this.fa.bind(this),j07:this.write.bind(this),j08:this.ea.bind(this),j09:this.ia.bind(this),j10:this.Z.bind(this),j11:this.ca.bind(this)}}A(){throw Error("Not initialized");}u(){throw Error("Not initialized");}aa(a,b,d,f){(a=A(this,a,b,d,f))&&delete a.G[a.key]}da(a,b,d,f){(a=A(this,a,b,d,f))&&(a.G[a.key]={})}ba(a,b,d,f){(a=A(this,a,b,d,f))&&(a.G[a.key]=[])}ha(a,b,d,f){return B(this,a,b,d,f)}ga(a,b,d,f){return B(this,a,b,d,f)}fa(a,b,d,f,c,e){a=B(this,
a,b,d,f);a=this.M.encode(a);b=0;a.length>=e&&(b=c=this.s(a.length+1));this.h.set(a,c);this.h[c+a.length]=0;return b}ea(a,b,d,f,c){a=B(this,a,b,d,f);c&&this.view.setInt32(c,a?.byteLength??0,!0);if(!a)return 0;c=this.s(a.byteLength);this.h.set(new Uint8Array(a),c);return c}write(a,b,d,f,c,e,g,h){(a=A(this,a,b,d,f))&&(a.G[a.key]=B(this,c,e,g,h))}ia(a,b,d,f,c,e,g,h,k,p,m,n,t){a=B(this,a,b,d,f);0==c?t=a():(c=B(this,c,e,g,h),t=t&&Array.isArray(c)?a(...c):a(c));(k=A(this,k,p,m,n))&&(k.G[k.key]=t)}Z(a,b,
d,f,c,e,g,h,k,p,m,n,t,q,r,L,ja,Q,Ua){const ka=I=>{const y=A(this,t,q,r,L);y&&(y.G[y.key]=I);this.u(ja,0)};(async()=>{try{let y=!1,la=0;Q&&(la=setTimeout(()=>{y=!0;ka("timeout")},Q));const R=B(this,a,b,d,f);let S;if(0==c)S=await R();else{const T=B(this,c,e,g,h);S=Ua&&Array.isArray(T)?await R(...T):await R(T)}if(!y){Q&&clearTimeout(la);var I=A(this,k,p,m,n);I&&(I.G[I.key]=S);this.u(ja,1)}}catch(y){ka(y.name+": "+y.message)}})()}ca(a,b,d,f,c,e){a=new (B(this,a,b,d,f))(...(c?this.g[c]:[]));e&&(this.g[e]=
a)}};class Da extends Ca{};class Ea extends Da{constructor(){super();this.P.push(()=>this.l=z(this,"c07"),()=>this.R=z(this,"c08"),()=>z(this,"c09"),()=>z(this,"c10"),()=>z(this,"c11"))}l(){throw Error("Not initialized");}R(){throw Error("Not initialized");}};function C(a,b,d){return f=>{const c=a[f??""];void 0===c&&"string"===typeof f&&console.error(`${d} ${f}`);return c??b}}function D(a){const b=Object.fromEntries(Object.entries(a).map(([d,f])=>[f,d]));return d=>b[d]}
var E=D({arc:1,arcTo:2,bezierCurveTo:3,closePath:4,ellipse:5,lineTo:6,moveTo:7,quadraticCurveTo:8,rect:9,roundRect:10,addPath:11,clearRect:12,fillRect:13,strokeRect:14,getTransform:15,resetTransform:16,rotate:17,scale:18,setTransform:19,transform:20,translate:21,beginPath:22,clip:23,fill:24,isPointInPath:25,isPointInStroke:26,stroke:27,lineCap:28,lineDashOffset:29,lineJoin:30,lineWidth:31,miterLimit:32,getLineDash:33,setLineDash:34,drawImage:35,createImageData:36,getImageData:37,putImageData:38,isContextLost:39,
reset:40,restore:41,save:42,fillStyle:43,strokeStyle:44,V:45,createLinearGradient:46,createPattern:47,createRadialGradient:48,filter:49,globalAlpha:50,globalCompositeOperation:51,imageSmoothingEnabled:52,imageSmoothingQuality:53,getContextAttributes:54,shadowBlur:55,shadowColor:56,shadowOffsetX:57,shadowOffsetY:58,fillText:59,measureText:60,strokeText:61,direction:62,font:63,fontKerning:64,fontStretch:65,fontVariantCaps:66,letterSpacing:67,textAlign:68,textBaseline:69,textRendering:70,wordSpacing:71,
drawFocusIfNeeded:72,X:80,sa:81,va:82,Ba:83,ua:84,Aa:85,ma:100,pa:101,ka:102,la:103,oa:104,na:105});const F={copy:1,"source-over":2,"source-in":3,"source-out":4,"source-atop":5,"destination-over":7,"destination-in":8,"destination-out":9,"destination-atop":10,xor:11,lighter:12,multiply:14,screen:15,overlay:16,darken:17,lighten:18,"color-dodge":19,"color-burn":20,"hard-light":21,"soft-light":22,difference:23,exclusion:24,hue:25,saturation:26,color:27,luminosity:28};
var Fa=C(F,F["source-over"],"eglobalCompositeOperation"),Ga=D(F);const Ha={ra:0,round:1,za:2};var Ia=C(Ha,0,"eLineCap"),Ja=D(Ha);const Ka={wa:0,qa:1,round:2};var La=C(Ka,0,"eLineJoin"),Ma=D(Ka);D({repeat:0,"repeat-x":1,"repeat-y":2,"no-repeat":3});const Na={ya:0,ta:1};var Oa=C(Na,0,"eFillRule"),G=D(Na);
const Pa={[1]:{m:3,v:1,C:2},[2]:{m:5},[3]:{m:6},[4]:{},[5]:{m:4,v:1,C:3},[6]:{m:2},[7]:{m:2},[8]:{m:4},[9]:{m:4},[10]:{m:4,D:3},[11]:{B:1,D:3},[12]:{m:4},[13]:{m:4},[14]:{m:4},[16]:{},[17]:{C:1},[18]:{C:2},[19]:{m:6},[20]:{m:6},[21]:{m:2},[22]:{},[23]:{v:1},[24]:{v:1},[27]:{},[28]:{v:2},[29]:{L:1},[30]:{v:2},[31]:{C:1},[32]:{C:1},[34]:{H:8},[38]:{m:2,D:3,B:1},[40]:{},[41]:{},[42]:{},[43]:{L:4},[44]:{L:4},[50]:{L:1},[51]:{v:5},[55]:{C:1},[56]:{L:4},[57]:{C:1},[58]:{C:1},[59]:{},[61]:{},[62]:{},[63]:{},
[64]:{},[65]:{},[66]:{},[67]:{},[68]:{},[69]:{},[70]:{},[71]:{},[80]:{},[81]:{v:1,B:1},[82]:{v:1,B:1},[83]:{B:1},[100]:{size:1},[101]:{B:1,size:1},[102]:{},[103]:{}};class H extends DataView{constructor(a,b,d){super(a,b,d);this.l=new Uint8Array(this.buffer)}i(a,b){a:{var d=this.l,f=b??!1;b=-7;let c=f?1:0;f=f?-1:1;let e=d[a+c];c+=f;let g=e&(1<<-b)-1;e>>=-b;for(b+=5;0<b;)g=256*g+d[a+c],c+=f,b-=8;let h=g&(1<<-b)-1;g>>=-b;for(b+=10;0<b;)h=256*h+d[a+c],c+=f,b-=8;if(0===g)g=-14;else{if(31===g){a=h?NaN:Infinity*(e?-1:1);break a}h+=Math.pow(2,10);g-=15}a=(e?-1:1)*h*Math.pow(2,g-10)}return a}j(a,b,d){var f=this.l,c=d??!1;d=10;let e,g=16-d-1;const h=(1<<g)-1,k=h>>1,p=23===
d?Math.pow(2,-24)-Math.pow(2,-77):0;let m=c?0:1;const n=c?1:-1,t=0>b||0===b&&0>1/b?1:0;b=Math.abs(b);isNaN(b)||Infinity===b?(b=isNaN(b)?1:0,c=h):(c=Math.floor(Math.log(b)/Math.LN2),1>b*(e=Math.pow(2,-c))&&(c--,e*=2),b=1<=c+k?b+p/e:b+p*Math.pow(2,1-k),2<=b*e&&(c++,e/=2),c+k>=h?(b=0,c=h):1<=c+k?(b=(b*e-1)*Math.pow(2,d),c+=k):(b=b*Math.pow(2,k-1)*Math.pow(2,d),c=0));for(;8<=d;)f[a+m]=b&255,m+=n,b/=256,d-=8;c=c<<d|b;for(g+=d;0<g;)f[a+m]=c&255,m+=n,c/=256,g-=8;f[a+m-n]|=128*t}}
function Qa(a,b,d=0,f=b.byteLength){if(b!==a.h||d!==a.g.byteOffset||f!==a.g.byteLength)a.h=b,a.g=new H(b,d,f),a.o=!0}function J(a,b,d){b+=d;if(b>=a.g.byteLength){if(a.o)throw Error("Buffer overflow");d=new Uint8Array(a.g.buffer);a.h=new ArrayBuffer(Math.max(a.g.byteLength+500,b));a.g=new H(a.h);(new Uint8Array(a.h)).set(d)}}
class Ra{constructor(){this.h=new ArrayBuffer(500);this.g=new H(this.h);this.o=!1}get buffer(){return this.g.buffer}get byteLength(){return this.g.byteLength}get byteOffset(){return this.g.byteOffset}i(a,b){return this.g.i(a,b)}j(a,b,d){this.g.j(a,b,d)}getFloat32(a,b){return this.g.getFloat32(a,b)}setFloat32(a,b,d){J(this,a,4);this.g.setFloat32(a,b,d)}getFloat64(a,b){return this.g.getFloat64(a,b)}setFloat64(a,b,d){J(this,a,8);this.g.setFloat64(a,b,d)}getUint8(a){return this.g.getUint8(a)}setUint8(a,
b){J(this,a,1);this.g.setUint8(a,b)}getUint16(a,b){return this.g.getUint16(a,b)}setUint16(a,b,d){J(this,a,2);this.g.setUint16(a,b,d)}getUint32(a,b){return this.g.getUint32(a,b)}setUint32(a,b,d){J(this,a,4);this.g.setUint32(a,b,d)}getInt8(a){return this.g.getInt8(a)}setInt8(a,b){J(this,a,1);this.g.setInt8(a,b)}getInt16(a,b){return this.g.getInt16(a,b)}setInt16(a,b,d){J(this,a,2);this.g.setInt16(a,b,d)}getInt32(a,b){return this.g.getInt32(a,b)}setInt32(a,b,d){J(this,a,4);this.g.setInt32(a,b,d)}getBigInt64(a,
b){return this.g.getBigInt64(a,b)}setBigInt64(a,b,d){J(this,a,8);this.g.setBigInt64(a,b,d)}getBigUint64(a,b){return this.g.getBigUint64(a,b)}setBigUint64(a,b,d){J(this,a,8);this.g.setBigUint64(a,b,d)}};class K{constructor(a){this.g=a;this.h=[];const b=a.addColorStop.bind(a);a.addColorStop=(d,f)=>{this.addColorStop(d,f);b(d,f)};a._=this}addColorStop(a,b){this.h.push({offset:a,color:b});this.g.addColorStop(a,b)}}class M{constructor(a){this.g=a;this.data=null;this.h=[];const b=a.setTransform.bind(a);a.setTransform=d=>{this.setTransform(d);b(d)};a._=this}setTransform(a){this.g.setTransform(a);a&&this.h.push(a)}}
function N(a){if(!a)return-1;console.log("ref index",a);if(a instanceof Path2D)throw Error("not a Path2DArray");return-1}class Sa{constructor(){this.g=[]}};const O="default alias all-scroll auto cell col-resize context-menu copy crosshair e-resize ew-resize grab grabbing help move n-resize ne-resize nesw-resize ns-resize nw-resize nwse-resize no-drop none not-allowed pointer progress row-resize s-resize se-resize sw-resize text url w-resize wait zoom-in zoom-out".split(" ");var P=["lt_cursor$$module$2023$ploft$js_dev$src$frontend$0$domedit"],U=aa;P[0]in U||"undefined"==typeof U.execScript||U.execScript("var "+P[0]);
for(var V;P.length&&(V=P.shift());)P.length||void 0===O?U[V]&&U[V]!==Object.prototype[V]?U=U[V]:U=U[V]={}:U[V]=O;function W(a){const b=a.getContext("2d");b.X=()=>{b.fillRect(0,0,b.canvas.width,b.canvas.height)};return b}
function X(a){if(a instanceof OffscreenCanvas||a instanceof HTMLCanvasElement)return a=a.getContext("2d").getImageData(0,0,a.width,a.height),{width:a.width,height:a.height,data:a.data};if(a instanceof ImageBitmap){var b=new OffscreenCanvas(a.width,a.height);b.getContext("2d").drawImage(a,0,0);return X(b)}let d;a instanceof HTMLImageElement?(b=a.naturalWidth,d=a.naturalHeight):a instanceof HTMLVideoElement?(b=a.videoWidth,d=a.videoHeight):(b=a.width,d=a.height);b=new OffscreenCanvas(b,d);b.getContext("2d").drawImage(a,
0,0);return X(b)}function Ta(a){a=[...a.trim().replace(/^#/,"")].map(b=>parseInt(b,16));return[16*a[0]+a[1],16*a[2]+a[3],16*a[4]+a[5],255]}function Va(a){if(-1<a.indexOf("#"))a=Ta(a);else a:{const b=a.match(/[\d.]+/g)?.map(Number)??[];switch(b.length){case 3:b[3]=1;case 4:/%/.test(a)&&(b[3]/=100);b[3]=parseInt(255*b[3],10);a=b;break a}throw Error("invalid rgba",a);}return a}
function Wa(a){if(4!==a.length)throw Error();if(255===a[3])return"#"+a.map(b=>b.toString(16).padStart(2,"0")).join("").toUpperCase();a=a.slice();a[3]/=255;return`rgba(${a.join(",")} )`}function Xa(a){return`rgba(${a>>24&255}, ${a>>16&255}, ${a>>8&255}, ${((a&255)/255).toFixed(3)})`};function Y(a,b,d){b=(1<<b)-1;if((a|b)!==b)throw Error(`${a} > ${b}`);return(b&a)<<d}
function Z(a){a.F++;let b=a.size;a.h.setUint8(b,a.e);b++;const d=b,f=Pa[a.e];f||console.log(a.e);const c=Math.ceil((2*(f.m??0)+(f.H??0)+(f.D??0)+ +(f.v??0))/8);b+=c;let e=0,g=0;for(var h=0;h<(f.m??0);h++){var k=a.g[h]??0;if(Number.isInteger(k))if(256>Math.abs(k)){0<k?(a.h.setUint8(b,k),k=Y(0,2,g),g+=2,e|=k):(a.h.setUint8(b,-k),k=Y(1,2,g),g+=2,e|=k);b+=1;continue}else if(32768>Math.abs(k)){a.h.setInt16(b,k,!0);k=Y(2,2,g);g+=2;e|=k;b+=2;continue}a.h.setFloat32(b,k,!0);k=Y(3,2,g);g+=2;e|=k;b+=4}a.g.length=
0;for(h=0;h<(f.C??0);h++)a.h.j(b,a.i[h]??0,!0),b+=2;a.i.length=0;for(h=0;h<(f.L??0);h++)a.h.setUint8(b,a.l[h]??0),b+=1;a.l.length=0;for(h=0;h<(f.B??0);h++)a.h.setUint16(b,a.s[h]??0,!0),b+=2;a.s.length=0;for(h=0;h<(f.size??0);h++)b+=4;f.H&&(e|=Y(a.u.length,f.H,g),g+=f.H,a.u.forEach(p=>{a.h.setUint8(b,p);b+=1}),a.u.length=0);f.D&&(e|=Y(a.o.length,f.D,g),g+=f.D,a.o.forEach(p=>{a.h.setFloat32(b,p,!0);b+=4}),a.o.length=0);f.v&&(e|=Y(a.j,f.v,g),g+=f.v,a.j=0);if(0!=c)if(1==c)a.h.setUint8(d,e);else if(2==
c)a.h.setUint16(d,e,!0);else if(4>=c)a.h.setUint32(d,e,!0);else throw Error();a.size=b}class Ya{constructor(a){this.h=new Ra;this.B=new Sa;if(a instanceof ArrayBuffer){var b=this.h,d;if(!f)var f=a.byteLength;d||=0;J(b,0,f);b=new Uint8Array(b.h);a=new Uint8Array(a,d,f);b.set(a,0)}else"number"===typeof a&&(this.h.setUint8(0,a),this.size=5);this.g=[];this.l=[];this.s=[];this.u=[];this.o=[];this.i=[];this.A=this.F=0}get size(){return this.h.getUint32(1,!0)}set size(a){this.h.setUint32(1,a,!0)}};class Za{constructor(){this.h=new Ya(100);this.g=W(new OffscreenCanvas(200,200));this.canvas=this.g.canvas}arc(a,b,d,f,c,e){const g=this.h;g.e=1;g.g[0]=a;g.g[1]=b;g.g[2]=d;g.i[0]=f;g.i[1]=c;g.j=e?1:0;Z(g);this.g.arc(a,b,d,f,c,e)}arcTo(a,b,d,f,c){const e=this.h;e.e=2;e.g[0]=a;e.g[1]=b;e.g[2]=d;e.g[3]=f;e.g[4]=c;Z(e);this.g.arcTo(a,b,d,f,c)}bezierCurveTo(a,b,d,f,c,e){const g=this.h;g.e=3;g.g[0]=a;g.g[1]=b;g.g[2]=d;g.g[3]=f;g.g[4]=c;g.g[5]=e;Z(g);this.g.bezierCurveTo(a,b,d,f,c,e)}closePath(){const a=
this.h;a.e=4;Z(a);this.g.closePath()}ellipse(a,b,d,f,c,e,g,h){const k=this.h;k.e=5;k.g[0]=a;k.g[1]=b;k.g[2]=d;k.g[3]=f;k.i[0]=c;k.i[1]=e;k.i[2]=g;k.j=h?1:0;Z(k);this.g.ellipse(a,b,d,f,c,e,g,h)}lineTo(a,b){const d=this.h;d.e=6;d.g[0]=a;d.g[1]=b;Z(d);this.g.lineTo(a,b)}moveTo(a,b){const d=this.h;d.e=7;d.g[0]=a;d.g[1]=b;Z(d);this.g.moveTo(a,b)}quadraticCurveTo(a,b,d,f){const c=this.h;c.e=8;c.g[0]=a;c.g[1]=b;c.g[2]=d;c.g[3]=f;Z(c);this.g.quadraticCurveTo(a,b,d,f)}rect(a,b,d,f){const c=this.h;c.e=9;c.g[0]=
a;c.g[1]=b;c.g[2]=d;c.g[3]=f;Z(c);this.g.rect(a,b,d,f)}roundRect(a,b,d,f,c){const e=this.h;e.e=10;e.g[0]=a;e.g[1]=b;e.g[2]=d;e.g[3]=f;const g=[],h=k=>{"number"===typeof k.x&&g.push(k.x);"number"===typeof k.y&&g.push(k.y)};"number"===typeof c?g.push(c):Array.isArray(c)?c.forEach(k=>{"number"===typeof k?g.push(k):h(k)}):c&&h(c);g.forEach((k,p)=>e.o[p]=k);Z(e);this.g.roundRect(a,b,d,f,c)}addPath(a,b){const d=this.h;d.e=11;a=N(a);-1<a?(d.s[0]=a,b&&(d.o[0]=b.a,d.o[1]=b.b,d.o[2]=b.c,d.o[3]=b.d,d.o[4]=b.e,
d.o[5]=b.f),Z(d)):console.error(this.addPath.name)}clearRect(a,b,d,f){const c=this.h;c.e=12;c.g[0]=a;c.g[1]=b;c.g[2]=d;c.g[3]=f;Z(c);this.g.clearRect(a,b,d,f)}fillRect(a,b,d,f){const c=this.h;c.e=13;c.g[0]=a;c.g[1]=b;c.g[2]=d;c.g[3]=f;Z(c);this.g.fillRect(a,b,d,f)}strokeRect(a,b,d,f){const c=this.h;c.e=14;c.g[0]=a;c.g[1]=b;c.g[2]=d;c.g[3]=f;Z(c);this.g.strokeRect(a,b,d,f)}getTransform(){return this.g.getTransform()}resetTransform(){const a=this.h;a.e=16;Z(a);this.g.resetTransform()}rotate(a){const b=
this.h;b.e=17;b.i[0]=a;Z(b);this.g.rotate(a)}scale(a,b){const d=this.h;d.e=18;d.i[0]=a;d.i[1]=b;Z(d);this.g.scale(a,b)}setTransform(a,b,d,f,c,e){const g=this.h;g.e=19;"number"!==typeof a&&(b=a.b,d=a.c,f=a.d,c=a.e,e=a.f,a=a.a);g.g[0]=a??0;g.g[1]=b??0;g.g[2]=d??0;g.g[3]=f??0;g.g[4]=c??0;g.g[5]=e??0;Z(g);this.g.setTransform(a,b,d,f,c,e)}transform(a,b,d,f,c,e){const g=this.h;g.e=20;g.g[0]=a;g.g[1]=b;g.g[2]=d;g.g[3]=f;g.g[4]=c;g.g[5]=e;Z(g);this.g.transform(a,b,d,f,c,e)}translate(a,b){const d=this.h;d.e=
21;d.g[0]=a;d.g[1]=b;Z(d);this.g.translate(a,b)}beginPath(){const a=this.h;a.e=22;Z(a);this.g.beginPath()}clip(a,b){const d=this.h;d.e=23;let f=N(a);-1<f?(d.s[0]=f,d.e=81):"string"===typeof a&&(b=a,a=void 0);d.j=Oa(b);Z(d);a&&b?this.g.clip(a,b):a?this.g.clip(a):b?this.g.clip(b):this.g.clip()}fill(a,b){const d=this.h;d.e=24;let f=N(a);-1<f?(console.log("fillpath"),d.s[0]=f,d.e=82):"string"===typeof a&&(b=a,a=void 0);d.j=Oa(b);Z(d);a&&b?this.g.fill(a,b):a?this.g.fill(a):b?this.g.fill(b):this.g.fill()}isPointInPath(a,
b,d,f){return a instanceof Path2D?this.g.isPointInPath(a,b,d,f):this.g.isPointInPath(a,b,d)}isPointInStroke(a,b,d){return a instanceof Path2D?this.g.isPointInStroke(a,b,d):this.g.isPointInStroke(a,b)}stroke(a){const b=this.h;b.e=27;let d=N(a);-1<d&&(b.s[0]=d,b.e=83);Z(b);a?this.g.stroke(a):this.g.stroke()}get lineCap(){return this.g.lineCap}set lineCap(a){const b=this.h;b.e=28;b.j=Ia(a);Z(b);this.g.lineCap=a}get lineDashOffset(){return this.g.lineDashOffset}set lineDashOffset(a){const b=this.h;b.e=
29;b.g[0]=a;Z(b);this.g.lineDashOffset=a}get lineJoin(){return this.g.lineJoin}set lineJoin(a){const b=this.h;b.e=30;b.j=La(a);Z(b);this.g.lineJoin=a}get lineWidth(){return this.g.lineWidth}set lineWidth(a){const b=this.h;b.e=31;b.i[0]=a;Z(b);this.g.lineWidth=a}get miterLimit(){return this.g.miterLimit}set miterLimit(a){const b=this.h;b.e=32;b.g[0]=a;Z(b);this.g.miterLimit=a}getLineDash(){return this.g.getLineDash()}setLineDash(a){const b=this.h;b.e=34;this.g.setLineDash(a);if(a&&a.length){const d=
Math.max(...a);if(256>a.length&&256>d)a.forEach((f,c)=>b.l[c]=Math.trunc(f));else throw Error();}Z(b);this.g.setLineDash(a)}drawImage(a,b,d,f,c,e,g,h,k){const p=this.h;p.e=35;Z(p);"number"===typeof e?this.g.drawImage(a,b,d,f,c,e,g,h,k):"number"===typeof f?this.g.drawImage(a,b,d,f,c):this.g.drawImage(a,b,d)}createImageData(a,b){return this.g.createImageData(a,b)}getImageData(a,b,d,f){return this.g.getImageData(a,b,d,f)}putImageData(a,b,d,f,c,e,g){a=this.h;a.e=38;a.g[0]=b;a.g[1]=d;b=[f,c,e,g];for(d=
0;d<b.length;d++){f=b[d];if(void 0===f)break;a.o[d]=f}throw Error();}isContextLost(){return this.g.isContextLost()}reset(){const a=this.h;a.e=40;Z(a);this.g.reset()}restore(){const a=this.h;a.e=41;Z(a);this.g.restore()}save(){const a=this.h;a.e=42;Z(a);this.g.save()}get fillStyle(){return this.g.fillStyle}set fillStyle(a){const b=this.h;b.e=43;if("string"===typeof a)this.g.fillStyle=a,b.l=Va(this.g.fillStyle);else{b.e=84;let d=N(a);-1<d&&(b.s[0]=d);if(a instanceof K||a instanceof M)this.g.fillStyle=
a.g;else throw Error();}Z(b)}get strokeStyle(){return this.g.strokeStyle}set strokeStyle(a){const b=this.h;b.e=44;if("string"===typeof a)this.g.strokeStyle=a,b.l=Va(this.g.strokeStyle);else{b.e=85;let d=N(a);0<=d&&(b.s[0]=d);if(a instanceof K||a instanceof M)this.g.fillStyle=a.g;else throw Error();}Z(b)}V(a,b,d){const f=this.g.V(a,b,d);let c=new K(f);c.F=b;c.I=d;c.A=a;return f}createLinearGradient(a,b,d,f){const c=this.g.createLinearGradient(a,b,d,f);let e=new K(c);e.i=a;e.j=d;e.l=b;e.o=f;return c}createPattern(a,
b){var d=this.g.createPattern(a,b??"");d=new M(d);if(a){a instanceof VideoFrame&&console.error("async toImageBuffer VideoFrame");a=X(a);d.data=a.data;d.height=a.height;d.width=a.width;if(b)throw Error();d.i=0}return d}createRadialGradient(a,b,d,f,c,e){var g=this.g.createRadialGradient(a,b,d,f,c,e);g=new K(g);g.i=a;g.j=f;g.l=b;g.o=c;g.s=d;g.u=e;return g}get filter(){return this.g.filter}set filter(a){const b=this.h;b.e=49;console.error("implemntar filter",a);Z(b);this.g.filter=a}get globalAlpha(){return this.g.globalAlpha}set globalAlpha(a){const b=
this.h;b.e=50;b.l[0]=Math.trunc(255*a);Z(b);this.g.globalAlpha=a}get globalCompositeOperation(){return this.g.globalCompositeOperation}set globalCompositeOperation(a){const b=this.h;b.e=51;b.j=Fa(a);Z(b);this.g.globalCompositeOperation=a}get shadowBlur(){return this.g.shadowBlur}set shadowBlur(a){const b=this.h;b.e=55;b.g[0]=a;Z(b);this.g.shadowBlur=a}get shadowColor(){return this.g.shadowColor}set shadowColor(a){const b=this.h;b.e=57;this.g.shadowColor=a;b.l=Va(this.g.shadowColor);Z(b)}get shadowOffsetX(){return this.g.shadowOffsetX}set shadowOffsetX(a){const b=
this.h;b.e=57;b.g[0]=a;Z(b);this.g.shadowOffsetX=a}get shadowOffsetY(){return this.g.shadowOffsetY}set shadowOffsetY(a){const b=this.h;b.e=58;b.g[0]=a;Z(b);this.g.shadowOffsetY=a}fillText(a,b,d,f){const c=this.h;c.e=59;Z(c);this.g.fillText(a,b,d,f)}strokeText(a,b,d,f){const c=this.h;c.e=61;Z(c);this.g.strokeText(a,b,d,f)}measureText(a){return this.g.measureText(a)}get direction(){return this.g.direction}set direction(a){const b=this.h;b.e=62;Z(b);this.g.direction=a}get font(){return this.g.font}set font(a){const b=
this.h;b.e=63;Z(b);this.g.font=a}get fontKerning(){return this.g.fontKerning}set fontKerning(a){const b=this.h;b.e=64;Z(b);this.g.fontKerning=a}get fontStretch(){return this.g.fontStretch}set fontStretch(a){const b=this.h;b.e=65;Z(b);this.g.fontStretch=a}get fontVariantCaps(){return this.g.fontVariantCaps}set fontVariantCaps(a){const b=this.h;b.e=66;Z(b);this.g.fontVariantCaps=a}get letterSpacing(){return this.g.letterSpacing}set letterSpacing(a){const b=this.h;b.e=67;Z(b);this.g.letterSpacing=a}get textAlign(){return this.g.textAlign}set textAlign(a){const b=
this.h;b.e=68;Z(b);this.g.textAlign=a}get textBaseline(){return this.g.textBaseline}set textBaseline(a){const b=this.h;b.e=69;Z(b);this.g.textBaseline=a}get textRendering(){return this.g.textRendering}set textRendering(a){const b=this.h;b.e=70;Z(b);this.g.textRendering=a}get wordSpacing(){return this.g.wordSpacing}set wordSpacing(a){const b=this.h;b.e=71;Z(b);this.g.wordSpacing=a}X(){const a=this.h;a.e=80;Z(a)}};var $a=D({xa:1,Ca:2});function ab(a){a.width=a.h.width=a.h.offsetWidth;a.height=a.h.height=a.h.offsetHeight}function bb(a,b,d){a.size=b;a.F=d;a.u=a.g.h;b&&(a.l=a.g.h.subarray(d,d+a.size),b=new Uint8ClampedArray(a.l),a.I=new ImageData(b,a.width,a.height))}function cb(a,b){if(a.g.h!=a.u||a.F!==b)a.u=a.g.h,a.l=a.g.h.subarray(b,b+a.size);a.I.data.set(a.l);a.o.putImageData(a.I,0,0)}
class db{constructor(a,b,d){console.log("csw",d);this.g=a;this.i=d;this.h=b;this.o=W(b);this.F=this.size=0;a=b.offsetWidth;d=b.offsetHeight;b.width=a;b.height=d;this.width=a;this.height=d;ab(this);const f=(c,e)=>this.g.T.decode(this.g.h.subarray(c,c+e));this.M=[(c,e)=>bb(this,c,e),()=>{window.requestAnimationFrame(this.s.bind(this))},c=>{(this.h??document.body).style.cursor=O[c]??"default"},c=>cb(this,c),(c,e)=>{Qa(this.K.h,this.g.Y,c,e);c=this.K;e=this.o;for(var g=0;g<c.size;){var h=c;h.A++;h.l.length=
h.u.length=h.i.length=h.o.length=h.g.length=h.s.length=0;var k=g;h.e=h.h.getUint8(g);g++;var p=g,m=Pa[h.e];if(void 0===m)console.error("parmet nd ",h.e),console.log("pinit",k,g),console.log(h.h.buffer);else{m||console.log("ectx",h.e,E(h.e));var n=Math.ceil(((m.v??0)+(m.H??0)+(m.D??0)+2*(m.m??0))/8);k=0;if(0!=n)if(1==n)k=h.h.getUint8(p);else if(2==n)k=h.h.getUint16(p,!0);else if(4>=n)k=h.h.getUint32(p,!0);else throw Error();g+=n;p=0;for(n=0;n<(m.m??0);n++){var t=k>>p&3;p+=2;0===t?(h.g[n]=h.h.getUint8(g),
g+=1):1===t?(h.g[n]=-h.h.getUint8(g),g+=1):2===t?(h.g[n]=h.h.getInt16(g,!0),g+=2):3===t&&(h.g[n]=h.h.getFloat32(g,!0),g+=4)}for(n=0;n<(m.C??0);n++)h.i[n]=h.h.i(g,!0),g+=2;for(n=0;n<(m.L??0);n++)h.l[n]=h.h.getUint8(g),g+=1;for(n=0;n<(m.B??0);n++)h.s[n]=h.h.getUint16(g,!0),g+=2;m.size&&(g+=4);if(m.H)for(n=k>>p&(1<<m.H)-1,p+=m.H,t=0;t<n;t++)h.u[t]=h.h.getUint8(g),g+=1;if(m.D)for(n=k>>p&(1<<m.D)-1,p+=m.D,t=0;t<n;t++)h.o[t]=h.h.getFloat32(g),g+=4;m.v&&(h.j=k>>p&(1<<m.v)-1)}if(12!==c.e)if(1===c.e)e.arc(c.g[0],
c.g[1],c.g[2],c.i[0],c.i[1],c.j?!0:!1);else if(2===c.e)e.arcTo(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4]);else if(3===c.e)e.bezierCurveTo(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4],c.g[5]);else if(4===c.e)e.closePath();else if(5===c.e)e.ellipse(c.g[0],c.g[1],c.g[2],c.g[3],c.i[0],c.i[1],c.i[2],c.j?!0:!1);else if(6===c.e)e.lineTo(c.g[0],c.g[1]);else if(7===c.e)e.moveTo(c.g[0],c.g[1]);else if(8===c.e)e.quadraticCurveTo(c.g[0],c.g[1],c.g[2],c.g[3]);else if(9===c.e)e.rect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(10===c.e)e.roundRect(c.g[0],
c.g[1],c.g[2],c.g[3],c.o);else if(12===c.e)e.clearRect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(13===c.e)e.fillRect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(14===c.e)e.strokeRect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(16===c.e)e.resetTransform();else if(17===c.e)e.rotate(c.i[0]);else if(18===c.e)e.scale(c.i[0],c.i[1]);else if(19===c.e)e.setTransform(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4],c.g[5]);else if(20===c.e)e.transform(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4],c.g[5]);else if(21===c.e)e.translate(c.g[0],c.g[1]);
else if(22===c.e)e.beginPath();else if(23===c.e)(h=G(c.j))?e.clip(h):e.clip();else if(81===c.e)h=c.B.g[c.s[0]].path,(m=G(c.j))?e.clip(h,m):e.clip(h);else if(24===c.e)(h=G(c.j))?e.fill(h):e.fill();else if(82===c.e)h=c.B.g[c.s[0]].path,(m=G(c.j))?e.fill(h,m):e.fill(h);else if(27===c.e)e.stroke();else if(83===c.e)e.stroke(c.B.g[c.s[0]].path);else if(28===c.e)e.lineCap=Ja(c.j);else if(29===c.e)e.lineDashOffset=c.l[0];else if(30===c.e)e.lineJoin=Ma(c.j);else if(31===c.e)e.lineWidth=c.i[0];else if(32===
c.e)e.miterLimit=c.i[0];else if(34===c.e)c.l.length&&e.setLineDash(c.l);else if(38===c.e)console.error("WRITE PUT IMAGEDATA");else if(40===c.e)e.reset();else if(41===c.e)e.restore();else if(42===c.e)e.save();else if(43===c.e)e.fillStyle=Wa(c.l);else if(84===c.e)console.warn("fazer fillstyleStyle2");else if(44===c.e)e.strokeStyle=Wa(c.l);else if(85===c.e)console.warn("fazer strokeStyle2");else if(50===c.e)e.globalAlpha=c.l[0]/255;else if(51===c.e)e.globalCompositeOperation=Ga(c.j);else if(55===c.e)e.shadowBlur=
c.g[0];else if(56===c.e)e.shadowColor=Wa(c.l);else if(57===c.e)e.shadowOffsetX=c.g[0];else if(58===c.e)e.shadowOffsetY=c.g[0];else if(49===c.e)console.log("set filter");else if(59!==c.e&&61!==c.e)if(80===c.e)e.fillRect(0,0,e.canvas.width,e.canvas.height);else if(62!==c.e&&63!==c.e&&64!==c.e&&65!==c.e&&66!==c.e&&67!==c.e&&68!==c.e&&69!==c.e&&70!==c.e&&71!==c.e&&100!==c.e)throw console.error(g,"FALTA FAZER",E(c.e),c.e),Error();}},(...c)=>{var e=this.o,g=c[c.length-1];c=c.slice(0,-1);switch(g){case 1:e.arc(c[0],
c[1],c[2],c[3],c[4],c[5]?!0:!1);break;case 2:e.arcTo(c[0],c[1],c[2],c[3],c[4]);break;case 3:e.bezierCurveTo(c[0],c[1],c[2],c[3],c[4],c[5]);break;case 4:e.closePath();break;case 5:e.ellipse(c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]?!0:!1);break;case 6:e.lineTo(c[0],c[1]);break;case 7:e.moveTo(c[0],c[1]);break;case 8:e.quadraticCurveTo(c[0],c[1],c[2],c[3]);break;case 9:e.rect(c[0],c[1],c[2],c[3]);break;case 10:console.warn("play round rect");e.roundRect(c[0],c[1],c[2],c[3]);break;case 12:e.clearRect(c[0],
c[1],c[2],c[3]);break;case 13:e.fillRect(c[0],c[1],c[2],c[3]);break;case 14:e.strokeRect(c[0],c[1],c[2],c[3]);break;case 16:e.resetTransform();break;case 17:e.rotate(c[0]);break;case 18:e.scale(c[0],c[1]);break;case 19:e.setTransform(c[0],c[1],c[2],c[3],c[4],c[5]);break;case 20:e.transform(c[0],c[1],c[2],c[3],c[4],c[5]);break;case 21:e.translate(c[0],c[1]);break;case 22:e.beginPath();break;case 23:(c=G(c[0]))?e.clip(c):e.clip();break;case 81:console.warn("play clip path");break;case 24:(c=G(c[0]))?
e.fill(c):e.fill();break;case 82:console.warn("play fill path");break;case 27:e.stroke();break;case 83:console.warn("play stroke path");break;case 28:e.lineCap=Ja(c[0]);break;case 29:e.lineDashOffset=c[0];break;case 30:e.lineJoin=Ma(c[0]);break;case 31:e.lineWidth=c[0];break;case 32:e.miterLimit=c[0];break;case 34:console.warn("play line dash");break;case 38:console.warn("play putImageData");break;case 40:e.reset();break;case 41:e.restore();break;case 42:e.save();break;case 43:e.fillStyle=Xa(c[0]);
break;case 84:console.warn("play fillstyleStyle2");break;case 44:e.strokeStyle=Xa(c[0]);break;case 85:console.warn("play strokeStyle2");break;case 50:e.globalAlpha=c[0]/255;break;case 51:e.globalCompositeOperation=Ga(c[0]);break;case 55:e.shadowBlur=c[0];break;case 56:e.shadowColor=Xa(c[0]);break;case 57:e.shadowOffsetX=c[0];break;case 58:e.shadowOffsetY=c[0];break;case 49:console.warn("play filter");break;case 59:g=f(c[0],c[1]);c[4]?e.fillText(g,c[2],c[3],c[4]):e.fillText(g,c[2],c[3]);break;case 61:g=
f(c[0],c[1]);c[4]?e.strokeText(g,c[2],c[3],c[4]):e.strokeText(g,c[2],c[3]);break;case 63:c=f(c[0],c[1]);e.font=c;break;case 80:e.fillRect(0,0,e.canvas.width,e.canvas.height);break;case 62:console.warn("play direction");break;case 64:console.warn("play fontKerning");break;case 65:console.warn("play fontStrech");break;case 66:console.warn("play fontVariantCaps");break;case 67:console.warn("play letterSpacing");break;case 68:console.warn("play textAlign");break;case 69:console.warn("play textBaseline");
break;case 70:console.warn("play textRendering");break;case 71:console.warn("play wordSpacing");break;case 100:break;default:console.warn(c,"FALTA FAZER",E(g),g)}}];this.J=this.g.A();this.g.g[this.J]=this.M;this.K=new Ya;window.addEventListener("resize",this.A.bind(this));this.A();if("none"!==b.style.pointerEvents){window.requestAnimationFrame(this.s.bind(this));eb(this);const c=this.g.A(),e=this.g.A();window[$a(1)]=()=>{const g=this.g.view.getInt32(this.j+20,!0);this.g.R(g,1,c,e);return this.g.g[e]};
window[$a(2)]=g=>{const h=this.g.view.getInt32(this.j+20,!0);this.g.g[c]=g;this.g.R(h,2,c,e);return this.g.g[e]}}}A(){ab(this);this.j=this.g.l(6,this.i,this.width,this.height,0,this.J);let a=this.g.view.getInt32(this.j,!0),b=this.g.view.getInt32(this.j+4,!0);bb(this,a,b)}get N(){return!!this.g.view.getInt32(this.j+8,!0)}s(a){(a=this.g.l(7,this.i,0,0,0,a))&&cb(this,a);this.N&&window.requestAnimationFrame(this.s.bind(this))}}
var eb=a=>{function b(d){return d.buttons??(void 0!==d.button?1<<d.button:0)}a.h.addEventListener("mousedown",d=>{a.g.l(0,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)});a.h.addEventListener("mouseup",d=>{a.g.l(1,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)});a.h.addEventListener("mousemove",d=>{a.g.l(2,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)});a.h.addEventListener("wheel",d=>{a.g.l(3,a.i,d.offsetX,d.offsetY,b(d),d.deltaY)},{passive:!0});a.h.addEventListener("mouseenter",d=>{a.g.l(4,a.i,d.offsetX,d.offsetY,
b(d),d.timeStamp)});a.h.addEventListener("mouseleave",d=>{a.g.l(5,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)})};async function fb(a,b,d){if(d){var f=W(b),c=W(d);window.ctx1=f;window.canvas=b;window.mem=a.g;window.ctx2=c;await (new w("stg.mandala")).i();d.width=b.width=b.offsetWidth;d.height=b.height=b.offsetHeight;new Za;f=0;new db(a,b,f++);new db(a,d,f++)}};document.addEventListener("DOMContentLoaded",async function(){let a=new Ea;await Aa(a);var b=f=>{const c=document.createElement("canvas");c.style.position="fixed";c.style.top="0";c.style.left="0";c.style.height="100vh";c.style.width="100vw";c.style.zIndex=f;document.getElementById("dmain")?.appendChild(c);return c};const d=b("1");b=b("2");b.style.pointerEvents="none";fb(a,d,b)});}).call(this);
