(function(){const l=new Map,q=l.delete.bind(l),r=new BroadcastChannel("ib");r.onmessage=a=>{a=a.data;1===a.m&&(l.get(a.n)?.close(),q(a.n))};l.delete=a=>{r.postMessage({m:1,n:a});return q(a)};
async function t(a,b){var d=l.get(a);if(d&&!b)return d;let c;b&&(d=await t(a),c=d.version+1,d.close());return new Promise((e,g)=>{let f=!1,h=!1;setTimeout(()=>{f||g(Error(`indexedDB timeout: bloqueado: ${h?"essa aba":"outra"} (${a})`))},100);const k=indexedDB.open(a,c);k.onsuccess=m=>{f=!0;m=m.target.result;l.set(a,m);e(m)};k.onerror=m=>{f=!0;g(m.target.error)};k.onupgradeneeded=m=>{f=!0;m=m.target.result;b&&b(m)};k.onblocked=()=>{h=!0}})}
async function aa(a,b){let d=await t(a);d.objectStoreNames.contains(b)||(d.close(),d=await t(a,c=>{c.createObjectStore(b)}));return d}async function ba(a,b){let d=await t(a);d.objectStoreNames.contains(b)&&(d.close(),d=await t(a,c=>{c.deleteObjectStore(b);console.log("apagado")}));return d}async function v(a,b,d,...c){const e=a.i.transaction([a.h],b).objectStore(a.h)[d](...c);return new Promise((g,f)=>{e.onsuccess=h=>{g(h.target.result)};e.onerror=h=>{f(h.target.error)}})}
class x{constructor(a){const [b,d]=a.split(".");this.g=b;this.h=d}get i(){return l.get(this.g)}async j(){return await aa(this.g,this.h)}async get(a){return await v(this,"readonly","get",a)}async set(a,b){await v(this,"readwrite","put",b,a)}async s(a){await v(this,"readwrite","delete",a)}async l(){await v(this,"readwrite","clear")}async o(){return await v(this,"readwrite","getAllKeys")}async B(){await ba(this.g,this.h)}async v(){this.i.close();l.delete(this.g);return new Promise((a,b)=>{const d=indexedDB.deleteDatabase(this.g);
d.onsuccess=()=>{a()};d.onerror=c=>{b(c.target.error)}})}}function ca(a){a=new x(a);const b=[];b[0]=a.j.bind(a);b[1]=a.get.bind(a);b[2]=a.set.bind(a);b[3]=a.s.bind(a);b[4]=a.l.bind(a);b[5]=a.o.bind(a);b[6]=a.B.bind(a);b[7]=a.v.bind(a);return b};const y="fd_advise fd_allocate fd_datasync fd_fdstat_set_flags fd_fdstat_set_rights fd_filestat_get fd_filestat_set_size fd_filestat_set_times fd_pread fd_pwrite fd_read fd_readdir fd_renumber fd_sync fd_tell path_create_directory path_filestat_get path_filestat_set_times path_link path_open path_readlink path_remove_directory path_rename path_symlink path_unlink_file poll_oneoff sched_yield random_get sock_accept sock_recv sock_send sock_shutdown __wasm_longjmp __wasm_setjmp_test args_get args_sizes_get clock_res_get fd_close fd_prestat_get fd_prestat_dir_name fd_seek proc_exit".split(" ");
async function da(a,b={}){a=new Response(new Blob([a],{type:"application/wasm"}));return await WebAssembly.instantiateStreaming(a,b)}console.log("DEV MODE",!0);function A(a,b){window.exp=a.F.instance.exports;return a.F.instance.exports[b]}
async function ea(a,b){let d=0;const c=async()=>{var e={wasi_snapshot_preview1:a.B,env:a.B};try{a.F=await da(b,e)}catch(g){return(e=String(g).match(/"(.*?)"\s*"(.*?)"/))?e[2]:null}return null};for(;100>d;){let e=await c();if(e)y.push(e),d++;else break}0<d&&(console.log("new imports demmand",d),console.log(y));a.J.forEach(e=>e());a.M()}async function fa(a){if(!a.F){var b=await fetch(`${"teste.wasm"}?v=${Date.now()}`);b.ok&&(b=await b.arrayBuffer(),await ea(a,b))}}
class ha{constructor(){this.J=[()=>{this.l=A(this,"memory");this.i=this.l.buffer;this.s=new Uint8Array(this.i);this.v=new DataView(this.i)},()=>this.G=A(this,"c01"),()=>A(this,"c02"),()=>this.M=A(this,"_start")]}get S(){return this.l.buffer}get g(){this.l.buffer!==this.i&&(this.i=this.l.buffer,this.s=new Uint8Array(this.i),this.v=new DataView(this.i));return this.s}get view(){this.l.buffer!==this.i&&(this.i=this.l.buffer,this.s=new Uint8Array(this.i),this.v=new DataView(this.i));return this.v}G(){throw Error("Not initialized");
}M(){throw Error("Not initialized");}get B(){return this.N}get N(){const a={fd_write:(b,d,c,e)=>{let g=0;for(let k=0;k<c;k++){var f=d+8*k,h=this.view.getUint32(f,!0);f=this.view.getUint32(f+4,!0);h=this.g.slice(h,h+f);h.every(m=>0===m||10===m||13===m)||(h=(new TextDecoder).decode(h),console[1===b?"log":"error"](h));g+=f}this.view.setUint32(e,g,!0)},fd_fdstat_get:(b,d)=>{this.view.setUint8(d,0);this.view.setUint8(d+1,0);this.view.setBigUint64(d+8>>>3,18446744073709551615n,!0);this.view.setBigUint64(d+
16>>>3,18446744073709551615n,!0);return 0},clock_time_get:(b,d,c)=>this.view.setBigUint64(c,1000000n*BigInt(Date.now()),!0),environ_get:(b,d)=>{console.log("environ_get",b,d);return 0},environ_sizes_get:(b,d)=>{this.view.setUint32(b,0,!0);this.view.setUint32(d,0,!0);return 0}};y.forEach(b=>{a[b]=(d,c,e,g)=>{console.log(b,d,c,e,g)}});return a}}
function B(a,b,d,c,e){if(33==b)return{H:a.h,key:d};if(34===b)return{H:a.h[d],key:e};if(35===b){let g=a.h[d];a=a.o.decode(a.g.subarray(c,c+e)).split(".");b=a.pop();a.forEach(f=>g=g[f]);return{H:g,key:b}}return null}
function C(a,b,d,c,e){if(2===b)return d;if(3===b)return e;if(4===b)return a.o.decode(a.g.subarray(c,c+d));if(33==b)return a.h[d];if(34===b)return a.h[d][e];if(35===b){let g=a.h[d];a.o.decode(a.g.subarray(c,c+e)).split(".").forEach(f=>g=g[f]);return g}if(1025==b)return ca(a.o.decode(a.g.subarray(c,c+d)))}
class ia extends ha{constructor(){super();this.J.push(()=>this.P=A(this,"c03"),()=>A(this,"c04"),()=>A(this,"c05"),()=>this.K=A(this,"c06"));this.h=[];this.o=new TextDecoder;this.U=new TextEncoder;this.h[0]=window}get B(){return{...this.N,...this.V}}get V(){return{j01:this.W.bind(this),j02:this.Z.bind(this),j03:this.X.bind(this),j04:this.ca.bind(this),j05:this.ba.bind(this),j06:this.aa.bind(this),j07:this.write.bind(this),j08:this.$.bind(this),j09:this.da.bind(this),j10:this.T.bind(this),j11:this.Y.bind(this)}}P(){throw Error("Not initialized");
}K(){throw Error("Not initialized");}W(a,b,d,c){(a=B(this,a,b,d,c))&&delete a.H[a.key]}Z(a,b,d,c){(a=B(this,a,b,d,c))&&(a.H[a.key]={})}X(a,b,d,c){(a=B(this,a,b,d,c))&&(a.H[a.key]=[])}ca(a,b,d,c){return C(this,a,b,d,c)}ba(a,b,d,c){return C(this,a,b,d,c)}aa(a,b,d,c,e,g){a=C(this,a,b,d,c);a=this.U.encode(a);b=0;a.length>=g&&(b=e=this.G(a.length+1));this.g.set(a,e);this.g[e+a.length]=0;return b}$(a,b,d,c,e){a=C(this,a,b,d,c);e&&this.view.setInt32(e,a?.byteLength??0,!0);if(!a)return 0;e=this.G(a.byteLength);
this.g.set(new Uint8Array(a),e);return e}write(a,b,d,c,e,g,f,h){(a=B(this,a,b,d,c))&&(a.H[a.key]=C(this,e,g,f,h))}da(a,b,d,c,e,g,f,h,k,m,n,p,w){a=C(this,a,b,d,c);0==e?w=a():(e=C(this,e,g,f,h),w=w&&Array.isArray(e)?a(...e):a(e));(k=B(this,k,m,n,p))&&(k.H[k.key]=w)}T(a,b,d,c,e,g,f,h,k,m,n,p,w,ta,ua,va,X,J,wa){const Y=z=>{const u=B(this,w,ta,ua,va);u&&(u.H[u.key]=z);console.log(z);this.K(X,0)};(async()=>{try{let u=!1,Z=0;J&&(Z=setTimeout(()=>{u=!0;Y("timeout")},J));const K=C(this,a,b,d,c);let L;if(0==
e)L=await K();else{const M=C(this,e,g,f,h);L=wa&&Array.isArray(M)?await K(...M):await K(M)}if(!u){J&&clearTimeout(Z);var z=B(this,k,m,n,p);z&&(z.H[z.key]=L);this.K(X,1)}}catch(u){Y(u.name+": "+u.message)}})()}Y(a,b,d,c,e,g){a=new (C(this,a,b,d,c))(...(e?this.h[e]:[]));g&&(this.h[g]=a)}};class ja extends ia{};class ka extends ja{constructor(){super();this.J.push(()=>this.j=A(this,"c07"),()=>A(this,"c08"),()=>A(this,"c10"),()=>A(this,"c11"))}j(){throw Error("Not initialized");}};function D(a,b,d){return c=>{const e=a[c??""];void 0===e&&"string"===typeof c&&console.error(`${d} ${c}`);return e??b}}function E(a){const b=Object.fromEntries(Object.entries(a).map(([d,c])=>[c,d]));return d=>b[d]}
var la=E({arc:1,arcTo:2,bezierCurveTo:3,closePath:4,ellipse:5,lineTo:6,moveTo:7,quadraticCurveTo:8,rect:9,roundRect:10,addPath:11,clearRect:12,fillRect:13,strokeRect:14,getTransform:15,resetTransform:16,rotate:17,scale:18,setTransform:19,transform:20,translate:21,beginPath:22,clip:23,fill:24,isPointInPath:25,isPointInStroke:26,stroke:27,lineCap:28,lineDashOffset:29,lineJoin:30,lineWidth:31,miterLimit:32,getLineDash:33,setLineDash:34,drawImage:35,createImageData:36,getImageData:37,putImageData:38,
isContextLost:39,reset:40,restore:41,save:42,fillStyle:43,strokeStyle:44,R:45,createLinearGradient:46,createPattern:47,createRadialGradient:48,filter:49,globalAlpha:50,globalCompositeOperation:51,imageSmoothingEnabled:52,imageSmoothingQuality:53,getContextAttributes:54,shadowBlur:55,shadowColor:56,shadowOffsetX:57,shadowOffsetY:58,fillText:59,measureText:60,strokeText:61,direction:62,font:63,fontKerning:64,fontStretch:65,fontVariantCaps:66,letterSpacing:67,textAlign:68,textBaseline:69,textRendering:70,
wordSpacing:71,drawFocusIfNeeded:72,O:80,pa:81,ua:82,Ea:83,ta:84,Da:85,ga:100,ja:101,ea:102,fa:103,ia:104,ha:105});const F={copy:1,"source-over":2,"source-in":3,"source-out":4,"source-atop":5,"destination-over":7,"destination-in":8,"destination-out":9,"destination-atop":10,xor:11,lighter:12,multiply:14,screen:15,overlay:16,darken:17,lighten:18,"color-dodge":19,"color-burn":20,"hard-light":21,"soft-light":22,difference:23,exclusion:24,hue:25,saturation:26,color:27,luminosity:28};
var ma=D(F,F["source-over"],"eglobalCompositeOperation"),na=E(F);const oa={na:0,round:1,Ca:2};var pa=D(oa,0,"eLineCap"),qa=E(oa);const ra={ya:0,ma:1,round:2};var sa=D(ra,0,"eLineJoin"),xa=E(ra);E({repeat:0,"repeat-x":1,"repeat-y":2,"no-repeat":3});const ya={Aa:0,sa:1};var za=D(ya,0,"eFillRule"),G=E(ya);
const Aa={[1]:{m:3,u:1,C:2},[2]:{m:5},[3]:{m:6},[4]:{},[5]:{m:4,u:1,C:3},[6]:{m:2},[7]:{m:2},[8]:{m:4},[9]:{m:4},[10]:{m:4,D:3},[11]:{A:1,D:3},[12]:{m:4},[13]:{m:4},[14]:{m:4},[16]:{},[17]:{C:1},[18]:{C:2},[19]:{m:6},[20]:{m:6},[21]:{m:2},[22]:{},[23]:{u:1},[24]:{u:1},[27]:{},[28]:{u:2},[29]:{L:1},[30]:{u:2},[31]:{C:1},[32]:{C:1},[34]:{I:8},[38]:{m:2,D:3,A:1},[40]:{},[41]:{},[42]:{},[43]:{L:4},[44]:{L:4},[50]:{L:1},[51]:{u:5},[55]:{C:1},[56]:{L:4},[57]:{C:1},[58]:{C:1},[59]:{},[61]:{},[62]:{},[63]:{},
[64]:{},[65]:{},[66]:{},[67]:{},[68]:{},[69]:{},[70]:{},[71]:{},[80]:{},[81]:{u:1,A:1},[82]:{u:1,A:1},[83]:{A:1},[100]:{size:1},[101]:{A:1,size:1},[102]:{},[103]:{}};class H extends DataView{constructor(a,b,d){super(a,b,d);this.l=new Uint8Array(this.buffer)}i(a,b){a:{var d=this.l,c=b??!1;b=-7;let e=c?1:0;c=c?-1:1;let g=d[a+e];e+=c;let f=g&(1<<-b)-1;g>>=-b;for(b+=5;0<b;)f=256*f+d[a+e],e+=c,b-=8;let h=f&(1<<-b)-1;f>>=-b;for(b+=10;0<b;)h=256*h+d[a+e],e+=c,b-=8;if(0===f)f=-14;else{if(31===f){a=h?NaN:Infinity*(g?-1:1);break a}h+=Math.pow(2,10);f-=15}a=(g?-1:1)*h*Math.pow(2,f-10)}return a}j(a,b,d){var c=this.l,e=d??!1;d=10;let g,f=16-d-1;const h=(1<<f)-1,k=h>>1,m=23===
d?Math.pow(2,-24)-Math.pow(2,-77):0;let n=e?0:1;const p=e?1:-1,w=0>b||0===b&&0>1/b?1:0;b=Math.abs(b);isNaN(b)||Infinity===b?(b=isNaN(b)?1:0,e=h):(e=Math.floor(Math.log(b)/Math.LN2),1>b*(g=Math.pow(2,-e))&&(e--,g*=2),b=1<=e+k?b+m/g:b+m*Math.pow(2,1-k),2<=b*g&&(e++,g/=2),e+k>=h?(b=0,e=h):1<=e+k?(b=(b*g-1)*Math.pow(2,d),e+=k):(b=b*Math.pow(2,k-1)*Math.pow(2,d),e=0));for(;8<=d;)c[a+n]=b&255,n+=p,b/=256,d-=8;e=e<<d|b;for(f+=d;0<f;)c[a+n]=e&255,n+=p,e/=256,f-=8;c[a+n-p]|=128*w}}
function Ba(a,b,d=0,c=b.byteLength){if(b!==a.h||d!==a.g.byteOffset||c!==a.g.byteLength)a.h=b,a.g=new H(b,d,c),a.o=!0}function I(a,b,d){b+=d;if(b>=a.g.byteLength){if(a.o)throw Error("Buffer overflow");d=new Uint8Array(a.g.buffer);a.h=new ArrayBuffer(Math.max(a.g.byteLength+500,b));a.g=new H(a.h);(new Uint8Array(a.h)).set(d)}}
class Ca{constructor(){this.h=new ArrayBuffer(500);this.g=new H(this.h);this.o=!1}get buffer(){return this.g.buffer}get byteLength(){return this.g.byteLength}get byteOffset(){return this.g.byteOffset}i(a,b){return this.g.i(a,b)}j(a,b,d){this.g.j(a,b,d)}getFloat32(a,b){return this.g.getFloat32(a,b)}setFloat32(a,b,d){I(this,a,4);this.g.setFloat32(a,b,d)}getFloat64(a,b){return this.g.getFloat64(a,b)}setFloat64(a,b,d){I(this,a,8);this.g.setFloat64(a,b,d)}getUint8(a){return this.g.getUint8(a)}setUint8(a,
b){I(this,a,1);this.g.setUint8(a,b)}getUint16(a,b){return this.g.getUint16(a,b)}setUint16(a,b,d){I(this,a,2);this.g.setUint16(a,b,d)}getUint32(a,b){return this.g.getUint32(a,b)}setUint32(a,b,d){I(this,a,4);this.g.setUint32(a,b,d)}getInt8(a){return this.g.getInt8(a)}setInt8(a,b){I(this,a,1);this.g.setInt8(a,b)}getInt16(a,b){return this.g.getInt16(a,b)}setInt16(a,b,d){I(this,a,2);this.g.setInt16(a,b,d)}getInt32(a,b){return this.g.getInt32(a,b)}setInt32(a,b,d){I(this,a,4);this.g.setInt32(a,b,d)}getBigInt64(a,
b){return this.g.getBigInt64(a,b)}setBigInt64(a,b,d){I(this,a,8);this.g.setBigInt64(a,b,d)}getBigUint64(a,b){return this.g.getBigUint64(a,b)}setBigUint64(a,b,d){I(this,a,8);this.g.setBigUint64(a,b,d)}};class N{constructor(a){this.g=a;this.h=[];const b=a.addColorStop.bind(a);a.addColorStop=(d,c)=>{this.addColorStop(d,c);b(d,c)};a._=this}addColorStop(a,b){this.h.push({offset:a,color:b});this.g.addColorStop(a,b)}}class O{constructor(a){this.g=a;this.data=null;this.h=[];const b=a.setTransform.bind(a);a.setTransform=d=>{this.setTransform(d);b(d)};a._=this}setTransform(a){this.g.setTransform(a);a&&this.h.push(a)}}
function P(a){if(!a)return-1;console.log("ref index",a);if(a instanceof Path2D)throw Error("not a Path2DArray");return-1}class Da{constructor(){this.g=[]}};function Ea(){return Object.fromEntries(Object.entries(Fa).map(([a,b])=>[b,a]))}const Fa={default:0,ka:1,"all-scroll":2,la:3,oa:4,"col-resize":5,"context-menu":6,qa:7,ra:8,"e-resize":9,"ew-resize":10,va:11,wa:12,xa:13,move:14,"n-resize":15,"ne-resize":16,"nesw-resize":17,"ns-resize":18,"nw-resize":19,"nwse-resize":20,"no-drop":21,za:22,"not-allowed":23,Ba:24,progress:25,"row-resize":26,"s-resize":27,"se-resize":28,"sw-resize":29,text:30,url:31,"w-resize":32,wait:33,"zoom-in":34,"zoom-out":35};
let Ga=null;function Q(a){const b=a.getContext("2d");b.O=()=>{b.fillRect(0,0,b.canvas.width,b.canvas.height)};return b}
function R(a){if(a instanceof OffscreenCanvas||a instanceof HTMLCanvasElement)return a=a.getContext("2d").getImageData(0,0,a.width,a.height),{width:a.width,height:a.height,data:a.data};if(a instanceof ImageBitmap){var b=new OffscreenCanvas(a.width,a.height);b.getContext("2d").drawImage(a,0,0);return R(b)}let d;a instanceof HTMLImageElement?(b=a.naturalWidth,d=a.naturalHeight):a instanceof HTMLVideoElement?(b=a.videoWidth,d=a.videoHeight):(b=a.width,d=a.height);b=new OffscreenCanvas(b,d);b.getContext("2d").drawImage(a,
0,0);return R(b)}function Ha(a){a=[...a.trim().replace(/^#/,"")].map(b=>parseInt(b,16));return[16*a[0]+a[1],16*a[2]+a[3],16*a[4]+a[5],255]}function S(a){if(-1<a.indexOf("#"))a=Ha(a);else a:{const b=a.match(/[\d.]+/g)?.map(Number)??[];console.log(a);switch(b.length){case 3:b[3]=1;case 4:/%/.test(a)&&(b[3]/=100);b[3]=parseInt(255*b[3],10);console.log(b);a=b;break a}throw Error("invalid rgba",a);}return a}
function T(a){if(4!==a.length)throw Error();if(255===a[3])return"#"+a.map(b=>b.toString(16).padStart(2,"0")).join("").toUpperCase();a=a.slice();a[3]/=255;return`rgba(${a.join(",")} )`};function U(a,b,d){b=(1<<b)-1;if((a|b)!==b)throw Error(`${a} > ${b}`);return(b&a)<<d}
function V(a){a.G++;let b=a.size;a.h.setUint8(b,a.e);b++;const d=b,c=Aa[a.e];c||console.log(a.e);const e=Math.ceil(((c.u??0)+(c.I??0)+(c.A??0)+(c.D??0)+2*(c.m??0))/8);b+=e;for(var g=0;g<(c.C??0);g++)a.h.j(b,a.i[g]??0,!0),b+=2;a.i.length=0;for(g=0;g<(c.L??0);g++)a.h.setUint8(b,a.l[g]??0),b+=1;a.l.length=0;for(g=0;g<(c.A??0);g++)a.h.setUint16(b,a.s[g]??0,!0),b+=2;let f=g=a.s.length=0;c.u&&(g|=U(a.j,c.u,f),f+=c.u,a.j=0);c.I&&(g|=U(a.v.length,c.I,f),f+=c.I,a.v.forEach(k=>{a.h.setUint8(b,k);b+=1}),a.v.length=
0);c.D&&(g|=U(a.o.length,c.D,f),f+=c.D,a.o.forEach(k=>{a.h.setFloat32(b,k,!0);b+=4}),a.o.length=0);for(let k=0;k<(c.m??0);k++){var h=a.g[k]??0;if(Number.isInteger(h))if(256>Math.abs(h)){0<h?(a.h.setUint8(b,h),h=U(0,2,f),f+=2,g|=h):(a.h.setUint8(b,h),h=U(1,2,f),f+=2,g|=h);b+=1;continue}else if(32768>Math.abs(h)){a.h.setInt16(b,h,!0);h=U(2,2,f);f+=2;g|=h;b+=2;continue}a.h.setFloat32(b,h,!0);h=U(3,2,f);f+=2;g|=h;b+=4}a.g.length=0;if(0!=e)if(1==e)a.h.setUint8(d,g);else if(2==e)a.h.setUint16(d,g,!0);else if(4>=
e)a.h.setUint32(d,g,!0);else throw Error();a.size=b}
class Ia{constructor(a){this.h=new Ca;this.A=new Da;if(a instanceof ArrayBuffer){var b=this.h,d;if(!c)var c=a.byteLength;d||=0;I(b,0,c);b=new Uint8Array(b.h);a=new Uint8Array(a,d,c);b.set(a,0)}else"number"===typeof a&&(this.h.setUint8(0,a),this.size=5);this.g=[];this.l=[];this.s=[];this.v=[];this.o=[];this.i=[];this.F=this.G=0}get size(){return this.h.getUint32(1,!0)}set size(a){this.h.setUint32(1,a,!0)}get B(){return this.h.buffer.slice(0,this.size)}};class Ja{constructor(){this.h=new Ia(100);this.g=Q(new OffscreenCanvas(200,200));this.canvas=this.g.canvas}arc(a,b,d,c,e,g){const f=this.h;f.e=1;f.g[0]=a;f.g[1]=b;f.g[2]=d;f.i[0]=c;f.i[1]=e;f.j=g?1:0;V(f);this.g.arc(a,b,d,c,e,g)}arcTo(a,b,d,c,e){const g=this.h;g.e=2;g.g[0]=a;g.g[1]=b;g.g[2]=d;g.g[3]=c;g.g[4]=e;V(g);this.g.arcTo(a,b,d,c,e)}bezierCurveTo(a,b,d,c,e,g){const f=this.h;f.e=3;f.g[0]=a;f.g[1]=b;f.g[2]=d;f.g[3]=c;f.g[4]=e;f.g[5]=g;V(f);this.g.bezierCurveTo(a,b,d,c,e,g)}closePath(){const a=
this.h;a.e=4;V(a);this.g.closePath()}ellipse(a,b,d,c,e,g,f,h){const k=this.h;k.e=5;k.g[0]=a;k.g[1]=b;k.g[2]=d;k.g[3]=c;k.i[0]=e;k.i[1]=g;k.i[2]=f;k.j=h?1:0;V(k);this.g.ellipse(a,b,d,c,e,g,f,h)}lineTo(a,b){const d=this.h;d.e=6;d.g[0]=a;d.g[1]=b;V(d);this.g.lineTo(a,b)}moveTo(a,b){const d=this.h;d.e=7;d.g[0]=a;d.g[1]=b;V(d);this.g.moveTo(a,b)}quadraticCurveTo(a,b,d,c){const e=this.h;e.e=8;e.g[0]=a;e.g[1]=b;e.g[2]=d;e.g[3]=c;V(e);this.g.quadraticCurveTo(a,b,d,c)}rect(a,b,d,c){const e=this.h;e.e=9;e.g[0]=
a;e.g[1]=b;e.g[2]=d;e.g[3]=c;V(e);this.g.rect(a,b,d,c)}roundRect(a,b,d,c,e){const g=this.h;g.e=10;g.g[0]=a;g.g[1]=b;g.g[2]=d;g.g[3]=c;const f=[],h=k=>{"number"===typeof k.x&&f.push(k.x);"number"===typeof k.y&&f.push(k.y)};"number"===typeof e?f.push(e):Array.isArray(e)?e.forEach(k=>{"number"===typeof k?f.push(k):h(k)}):e&&h(e);f.forEach((k,m)=>g.o[m]=k);V(g);this.g.roundRect(a,b,d,c,e)}addPath(a,b){const d=this.h;d.e=11;a=P(a);-1<a?(d.s[0]=a,b&&(d.o[0]=b.a,d.o[1]=b.b,d.o[2]=b.c,d.o[3]=b.d,d.o[4]=b.e,
d.o[5]=b.f),V(d)):console.error(this.addPath.name)}clearRect(a,b,d,c){const e=this.h;e.e=12;e.g[0]=a;e.g[1]=b;e.g[2]=d;e.g[3]=c;V(e);this.g.clearRect(a,b,d,c)}fillRect(a,b,d,c){const e=this.h;e.e=13;e.g[0]=a;e.g[1]=b;e.g[2]=d;e.g[3]=c;V(e);this.g.fillRect(a,b,d,c)}strokeRect(a,b,d,c){const e=this.h;e.e=14;e.g[0]=a;e.g[1]=b;e.g[2]=d;e.g[3]=c;V(e);this.g.strokeRect(a,b,d,c)}getTransform(){return this.g.getTransform()}resetTransform(){const a=this.h;a.e=16;V(a);this.g.resetTransform()}rotate(a){const b=
this.h;b.e=17;b.i[0]=a;V(b);this.g.rotate(a)}scale(a,b){const d=this.h;d.e=18;d.i[0]=a;d.i[1]=b;V(d);this.g.scale(a,b)}setTransform(a,b,d,c,e,g){const f=this.h;f.e=19;"number"!==typeof a&&(b=a.b,d=a.c,c=a.d,e=a.e,g=a.f,a=a.a);f.g[0]=a??0;f.g[1]=b??0;f.g[2]=d??0;f.g[3]=c??0;f.g[4]=e??0;f.g[5]=g??0;V(f);this.g.setTransform(a,b,d,c,e,g)}transform(a,b,d,c,e,g){const f=this.h;f.e=20;f.g[0]=a;f.g[1]=b;f.g[2]=d;f.g[3]=c;f.g[4]=e;f.g[5]=g;V(f);this.g.transform(a,b,d,c,e,g)}translate(a,b){const d=this.h;d.e=
21;d.g[0]=a;d.g[1]=b;V(d);this.g.translate(a,b)}beginPath(){const a=this.h;a.e=22;V(a);this.g.beginPath()}clip(a,b){const d=this.h;d.e=23;let c=P(a);-1<c?(d.s[0]=c,d.e=81):"string"===typeof a&&(b=a,a=void 0);d.j=za(b);V(d);a&&b?this.g.clip(a,b):a?this.g.clip(a):b?this.g.clip(b):this.g.clip()}fill(a,b){const d=this.h;d.e=24;let c=P(a);-1<c?(console.log("fillpath"),d.s[0]=c,d.e=82):"string"===typeof a&&(b=a,a=void 0);d.j=za(b);console.log("fill",this.g.fillStyle);V(d);a&&b?this.g.fill(a,b):a?this.g.fill(a):
b?this.g.fill(b):this.g.fill()}isPointInPath(a,b,d,c){return a instanceof Path2D?this.g.isPointInPath(a,b,d,c):this.g.isPointInPath(a,b,d)}isPointInStroke(a,b,d){return a instanceof Path2D?this.g.isPointInStroke(a,b,d):this.g.isPointInStroke(a,b)}stroke(a){const b=this.h;b.e=27;let d=P(a);-1<d&&(b.s[0]=d,b.e=83);V(b);a?this.g.stroke(a):this.g.stroke()}get lineCap(){return this.g.lineCap}set lineCap(a){const b=this.h;b.e=28;b.j=pa(a);V(b);this.g.lineCap=a}get lineDashOffset(){return this.g.lineDashOffset}set lineDashOffset(a){const b=
this.h;b.e=29;b.g[0]=a;V(b);this.g.lineDashOffset=a}get lineJoin(){return this.g.lineJoin}set lineJoin(a){const b=this.h;b.e=30;b.j=sa(a);V(b);this.g.lineJoin=a}get lineWidth(){return this.g.lineWidth}set lineWidth(a){const b=this.h;b.e=31;b.i[0]=a;V(b);this.g.lineWidth=a}get miterLimit(){return this.g.miterLimit}set miterLimit(a){const b=this.h;b.e=32;b.g[0]=a;V(b);this.g.miterLimit=a}getLineDash(){return this.g.getLineDash()}setLineDash(a){const b=this.h;b.e=34;this.g.setLineDash(a);if(a&&a.length){const d=
Math.max(...a);if(256>a.length&&256>d)a.forEach((c,e)=>b.l[e]=Math.trunc(c));else throw Error();}V(b);this.g.setLineDash(a)}drawImage(a,b,d,c,e,g,f,h,k){const m=this.h;m.e=35;V(m);"number"===typeof g?this.g.drawImage(a,b,d,c,e,g,f,h,k):"number"===typeof c?this.g.drawImage(a,b,d,c,e):this.g.drawImage(a,b,d)}createImageData(a,b){return this.g.createImageData(a,b)}getImageData(a,b,d,c){return this.g.getImageData(a,b,d,c)}putImageData(a,b,d,c,e,g,f){a=this.h;a.e=38;a.g[0]=b;a.g[1]=d;b=[c,e,g,f];for(d=
0;d<b.length;d++){c=b[d];if(void 0===c)break;a.o[d]=c}throw Error();}isContextLost(){return this.g.isContextLost()}reset(){const a=this.h;a.e=40;V(a);this.g.reset()}restore(){const a=this.h;a.e=41;V(a);this.g.restore()}save(){const a=this.h;a.e=42;V(a);this.g.save()}get fillStyle(){return this.g.fillStyle}set fillStyle(a){const b=this.h;b.e=43;if("string"===typeof a)this.g.fillStyle=a,b.l=S(this.g.fillStyle);else{b.e=84;let d=P(a);-1<d&&(b.s[0]=d);if(a instanceof N||a instanceof O)this.g.fillStyle=
a.g;else throw Error();}V(b)}get strokeStyle(){return this.g.strokeStyle}set strokeStyle(a){const b=this.h;b.e=44;if("string"===typeof a)this.g.strokeStyle=a,b.l=S(this.g.strokeStyle);else{b.e=85;let d=P(a);0<=d&&(b.s[0]=d);if(a instanceof N||a instanceof O)this.g.fillStyle=a.g;else throw Error();}V(b)}R(a,b,d){const c=this.g.R(a,b,d);let e=new N(c);e.F=b;e.G=d;e.B=a;return c}createLinearGradient(a,b,d,c){const e=this.g.createLinearGradient(a,b,d,c);let g=new N(e);g.i=a;g.j=d;g.l=b;g.o=c;return e}createPattern(a,
b){var d=this.g.createPattern(a,b??"");d=new O(d);if(a){a instanceof VideoFrame&&console.error("async toImageBuffer VideoFrame");a=R(a);d.data=a.data;d.height=a.height;d.width=a.width;if(b)throw Error();d.i=0}return d}createRadialGradient(a,b,d,c,e,g){var f=this.g.createRadialGradient(a,b,d,c,e,g);f=new N(f);f.i=a;f.j=c;f.l=b;f.o=e;f.s=d;f.v=g;return f}get filter(){return this.g.filter}set filter(a){const b=this.h;b.e=49;console.error("implemntar filter",a);V(b);this.g.filter=a}get globalAlpha(){return this.g.globalAlpha}set globalAlpha(a){const b=
this.h;b.e=50;b.l[0]=Math.trunc(255*a);V(b);this.g.globalAlpha=a}get globalCompositeOperation(){return this.g.globalCompositeOperation}set globalCompositeOperation(a){const b=this.h;b.e=51;b.j=ma(a);V(b);this.g.globalCompositeOperation=a}get shadowBlur(){return this.g.shadowBlur}set shadowBlur(a){const b=this.h;b.e=55;b.g[0]=a;V(b);this.g.shadowBlur=a}get shadowColor(){return this.g.shadowColor}set shadowColor(a){const b=this.h;b.e=57;this.g.shadowColor=a;b.l=S(this.g.shadowColor);V(b)}get shadowOffsetX(){return this.g.shadowOffsetX}set shadowOffsetX(a){const b=
this.h;b.e=57;b.g[0]=a;V(b);this.g.shadowOffsetX=a}get shadowOffsetY(){return this.g.shadowOffsetY}set shadowOffsetY(a){const b=this.h;b.e=58;b.g[0]=a;V(b);this.g.shadowOffsetY=a}fillText(a,b,d,c){const e=this.h;e.e=59;V(e);this.g.fillText(a,b,d,c)}strokeText(a,b,d,c){const e=this.h;e.e=61;V(e);this.g.strokeText(a,b,d,c)}measureText(a){return this.g.measureText(a)}get direction(){return this.g.direction}set direction(a){const b=this.h;b.e=62;V(b);this.g.direction=a}get font(){return this.g.font}set font(a){const b=
this.h;b.e=63;V(b);this.g.font=a}get fontKerning(){return this.g.fontKerning}set fontKerning(a){const b=this.h;b.e=64;V(b);this.g.fontKerning=a}get fontStretch(){return this.g.fontStretch}set fontStretch(a){const b=this.h;b.e=65;V(b);this.g.fontStretch=a}get fontVariantCaps(){return this.g.fontVariantCaps}set fontVariantCaps(a){const b=this.h;b.e=66;V(b);this.g.fontVariantCaps=a}get letterSpacing(){return this.g.letterSpacing}set letterSpacing(a){const b=this.h;b.e=67;V(b);this.g.letterSpacing=a}get textAlign(){return this.g.textAlign}set textAlign(a){const b=
this.h;b.e=68;V(b);this.g.textAlign=a}get textBaseline(){return this.g.textBaseline}set textBaseline(a){const b=this.h;b.e=69;V(b);this.g.textBaseline=a}get textRendering(){return this.g.textRendering}set textRendering(a){const b=this.h;b.e=70;V(b);this.g.textRendering=a}get wordSpacing(){return this.g.wordSpacing}set wordSpacing(a){const b=this.h;b.e=71;V(b);this.g.wordSpacing=a}O(){const a=this.h;a.e=80;V(a)}};function Ka(a,b,d){a.size=b;a.j=d;a.v=a.g.g;a.l=a.g.g.subarray(d,d+a.size);b=new Uint8ClampedArray(a.l);a.G=new ImageData(b,a.width,a.height);a.j&&W(a,a.j)}function W(a,b){if(a.g.g!=a.v||a.j!==b)a.v=a.g.g,a.l=a.g.g.subarray(b,b+a.size);a.G.data.set(a.l);a.F.putImageData(a.G,0,0)}
class La{constructor(a,b,d){console.log("csw",d);this.g=a;this.i=d;this.h=b;this.F=Q(b);this.j=this.size=0;this.width=b.offsetWidth;this.height=b.offsetHeight;this.M=[(c,e)=>Ka(this,c,e),()=>{window.requestAnimationFrame(this.s.bind(this))},c=>{var e=this.h;Ga||=Ea();(e??document.body).style.cursor=Ga[c]??"default"},c=>W(this,c),(c,e)=>{Ba(this.K.h,this.g.S,c,e);c=this.K;e=this.F;for(var g=0;g<c.size;){var f=c;f.F++;f.l.length=f.v.length=f.i.length=f.o.length=f.g.length=f.s.length=0;var h=g;f.e=f.h.getUint8(g);
g++;var k=g,m=Aa[f.e];if(void 0===m)console.error("parmet nd ",f.e),console.log("pinit",h,g),console.log(f.h.buffer);else{m||console.log("ectx",f.e,la(f.e));var n=Math.ceil(((m.u??0)+(m.I??0)+(m.A??0)+(m.D??0)+2*(m.m??0))/8);h=0;if(0!=n)if(1==n)h=f.h.getUint8(k);else if(2==n)h=f.h.getUint16(k,!0);else if(4>=n)h=f.h.getUint32(k,!0);else throw Error();g+=n;for(k=0;k<(m.C??0);k++)f.i[k]=f.h.i(g,!0),g+=2;for(k=0;k<(m.L??0);k++)f.l[k]=f.h.getUint8(g),g+=1;for(k=0;k<(m.A??0);k++)f.s[k]=f.h.getUint16(g,
!0),g+=2;m.size&&(g+=4);k=0;m.u&&(f.j=h>>k&(1<<m.u)-1,k+=m.u);if(m.I){n=h>>k&(1<<m.I)-1;k+=m.I;for(var p=0;p<n;p++)f.v[p]=f.h.getUint8(g),g+=1}if(m.D)for(n=h>>k&(1<<m.D)-1,k+=m.D,p=0;p<n;p++)f.o[p]=f.h.getFloat32(g),g+=4;for(n=0;n<(m.m??0);n++)p=h>>k&3,k+=2,0===p?(f.g[n]=f.h.getUint8(g),g+=1):1===p?(f.g[n]=-f.h.getUint8(g),g+=1):2===p?(f.g[n]=f.h.getInt16(g,!0),g+=2):3===p&&(f.g[n]=f.h.getFloat32(g,!0),g+=4)}if(12!==c.e)if(1===c.e)e.arc(c.g[0],c.g[1],c.g[2],c.i[0],c.i[1],c.j?!0:!1);else if(2===c.e)e.arcTo(c.g[0],
c.g[1],c.g[2],c.g[3],c.g[4]);else if(3===c.e)e.bezierCurveTo(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4],c.g[5]);else if(4===c.e)e.closePath();else if(5===c.e)e.ellipse(c.g[0],c.g[1],c.g[2],c.g[3],c.i[0],c.i[1],c.i[2],c.j?!0:!1);else if(6===c.e)e.lineTo(c.g[0],c.g[1]);else if(7===c.e)e.moveTo(c.g[0],c.g[1]);else if(8===c.e)e.quadraticCurveTo(c.g[0],c.g[1],c.g[2],c.g[3]);else if(9===c.e)e.rect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(10===c.e)e.roundRect(c.g[0],c.g[1],c.g[2],c.g[3],c.o);else if(12===c.e)e.clearRect(c.g[0],
c.g[1],c.g[2],c.g[3]);else if(13===c.e)e.fillRect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(14===c.e)e.strokeRect(c.g[0],c.g[1],c.g[2],c.g[3]);else if(16===c.e)e.resetTransform();else if(17===c.e)e.rotate(c.i[0]);else if(18===c.e)e.scale(c.i[0],c.i[1]);else if(19===c.e)e.setTransform(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4],c.g[5]);else if(20===c.e)e.transform(c.g[0],c.g[1],c.g[2],c.g[3],c.g[4],c.g[5]);else if(21===c.e)e.translate(c.g[0],c.g[1]);else if(22===c.e)e.beginPath();else if(23===c.e)(f=G(c.j))?e.clip(f):
e.clip();else if(81===c.e)f=c.A.g[c.s[0]].path,(m=G(c.j))?e.clip(f,m):e.clip(f);else if(24===c.e)(f=G(c.j))?e.fill(f):e.fill();else if(82===c.e)f=c.A.g[c.s[0]].path,(m=G(c.j))?e.fill(f,m):e.fill(f);else if(27===c.e)e.stroke();else if(83===c.e)e.stroke(c.A.g[c.s[0]].path);else if(28===c.e)e.lineCap=qa(c.j);else if(29===c.e)e.lineDashOffset=c.l[0];else if(30===c.e)e.lineJoin=xa(c.j);else if(31===c.e)e.lineWidth=c.i[0];else if(32===c.e)e.miterLimit=c.i[0];else if(34===c.e)c.l.length&&e.setLineDash(c.l);
else if(38===c.e)console.error("WRITE PUT IMAGEDATA");else if(40===c.e)e.reset();else if(41===c.e)e.restore();else if(42===c.e)e.save();else if(43===c.e)e.fillStyle=T(c.l);else if(84===c.e)console.warn("fazer fillstyleStyle2");else if(44===c.e)e.strokeStyle=T(c.l);else if(85===c.e)console.warn("fazer strokeStyle2");else if(50===c.e)e.globalAlpha=c.l[0]/255;else if(51===c.e)e.globalCompositeOperation=na(c.j);else if(55===c.e)e.shadowBlur=c.g[0];else if(56===c.e)e.shadowColor=T(c.l);else if(57===c.e)e.shadowOffsetX=
c.g[0];else if(58===c.e)e.shadowOffsetX=c.g[0];else if(49===c.e)console.log("set filter");else if(59!==c.e&&61!==c.e)if(80===c.e)e.fillRect(0,0,e.canvas.width,e.canvas.height);else if(62!==c.e&&63!==c.e&&64!==c.e&&65!==c.e&&66!==c.e&&67!==c.e&&68!==c.e&&69!==c.e&&70!==c.e&&71!==c.e&&100!==c.e)throw console.error(g,"FALTA FAZER",la(c.e),c.e),Error();}}];this.J=this.g.P();this.g.h[this.J]=this.M;this.K=new Ia;window.addEventListener("resize",this.B.bind(this));this.B();"none"!==b.style.pointerEvents&&
(window.requestAnimationFrame(this.s.bind(this)),Ma(this))}B(){this.width=this.h.width=this.h.offsetWidth;this.height=this.h.height=this.h.offsetHeight;this.o=this.g.j(6,this.i,this.width,this.height,0,this.J);this.size=this.g.view.getInt32(this.o,!0);this.j=this.g.view.getInt32(this.o+4,!0);this.size&&this.j&&Ka(this,this.size,this.j)}get N(){return!!this.g.view.getInt32(this.o+8,!0)}s(a){(a=this.g.j(7,this.i,0,0,0,a))&&W(this,a);this.N&&window.requestAnimationFrame(this.s.bind(this))}}
var Ma=a=>{function b(d){return d.buttons??(void 0!==d.button?1<<d.button:0)}a.h.addEventListener("mousedown",d=>{a.g.j(0,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)});a.h.addEventListener("mouseup",d=>{a.g.j(1,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)});a.h.addEventListener("mousemove",d=>{a.g.j(2,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)});a.h.addEventListener("wheel",d=>{a.g.j(3,a.i,d.offsetX,d.offsetY,b(d),d.deltaY)},{passive:!0});a.h.addEventListener("mouseenter",d=>{a.g.j(4,a.i,d.offsetX,d.offsetY,
b(d),d.timeStamp)});a.h.addEventListener("mouseleave",d=>{a.g.j(5,a.i,d.offsetX,d.offsetY,b(d),d.timeStamp)})};async function Na(a,b,d){if(d){var c=Q(b),e=Q(d);window.ctx1=c;window.canvas=b;window.mem=a.h;window.ctx2=e;var g=new x("stg.mandala");await g.j();d.width=b.width=b.offsetWidth;d.height=b.height=b.offsetHeight;var f=new Ja;await async function(h){h.fillStyle="white";h.O();h.fillStyle="pink";h.fillRect(300,200,400,100);h.strokeStyle="brown";h.lineWidth=10;h.strokeRect(400,300,200,600);h.fillStyle="rgba(255,255,0,0.8)";h.beginPath();h.arc(600,300,150,0,3*Math.PI/2);h.closePath();h.stroke();h.fill();
h instanceof Ja&&(await g.set("bvg4",f.h.B),console.log("ESCREVEU"))}(f);d=0;new La(a,b,d++)}};document.addEventListener("DOMContentLoaded",async function(){let a=new ka;await fa(a);var b=()=>{const c=document.createElement("canvas");c.style.position="fixed";c.style.top="0";c.style.left="0";c.style.height="100vh";c.style.width="100vw";document.getElementById("dmain")?.appendChild(c);return c};const d=b("1");b=b("2");b.style.pointerEvents="none";Na(a,d,b)});}).call(this);
